### ISSUE TITLE
Question regarding scheme pages

### ISSUE THREAD

**Issue by Snapy** [uBlock-LLC/uBlock#1007]
I was just wondering if for example the opera-scheme was useful on non Opera browers or if it is a scheme shared between all browsers like behind-the-scene. Same question regarding chrome-extension-scheme on non Chromium browsers. Also are there any other existing schemes.

**Comment by gorhill** [comment]
I am guessing `opera-scheme` is encountered only on Opera. Some may be shared, like the `chrome-scheme` (Chromium, Firefox, Opera). Some applies to all browsers, like `data-scheme`, `file-scheme`.

The `-scheme` "hostnames" are just a trick used by uBlock to enable working on web page which URL does not have a formal hostname. uBlock in such case uses the scheme part of the URL to create a fake hostname, so that features such as whitelisting or dynamic filtering can work.

**Comment by Snapy** [comment]
Thanks. It was to be sure I could remove some whitelisted schemes safely.
