### ISSUE TITLE
http://hosts-file.net/download/hosts.txt adding error

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#1065]
uBlock can't add http://hosts-file.net/download/hosts.txt, it seems to just ignore it.
I know it has almost 700,000 hostnames, but can you add it right?

**Comment by gorhill** [comment]
That file is over 30 MB, no way I will ever add this to the package. If you are on Chromium, setup a local server to host it, if you are on Firefox, save the file locally and then you can add it as a `file:///` URL.

**Comment by mikhaelkh** [comment]
I know there is no point of adding it to package, But why when I add a custom URL http://hosts-file.net/download/hosts.txt, it can't process it? The list updates monthly.

**Comment by gorhill** [comment]
Timeout? There is a timeout in uBlock so that it does not spin forever waiting for whatever is being downloaded. Removing this timeout is not an option, I can't cripple uBlock for that one extreme case.

**Comment by Mikey1993** [comment]
@gorhill But what can be done to support huge filter lists, is to allow only the users who checked the "I am an advanced user" in the settings, to set their preferred timeout on the "3rd-party filters"/"Settings" tab.

There is a little sense in not allowing users to use huge filter lists if they want to, specifically when there is no real programmatic issue with it.

**Comment by gorhill** [comment]
I am not a fan of "yet another setting" as easy solution for everything.

**Comment by Mikey1993** [comment]
@gorhill So basically these users are condemned to be less secure?

I think this is the tradeoff - tracking isn't something that easy to solve and very nasty thing as we all know, but these little things like updating a huge filter lists is an easy thing to support/fix at the end.

Isn't this is the master goal of uBlock?

If there is another prettier solution which doesn't involve a new setting, excuse me for ranting.
Otherwise, this is really not advancing the protection of privacy.

**Comment by gorhill** [comment]
> **condemned** to be less secure

Hyperbole. Accomplishes nothing. This is getting silly.

Where have you seen a widespread recommendation to install that huge file as hosts file as first step to make a computer significantly more secure?

If a user **really** worry about raising uBlock's strictness, the first step is not to to feed it that huge file, the first step is to use default-deny, i.e. to assume not everything nasty in existence is compiled into that one file and thus it can be blindly relied upon. Default-deny assumes everything is unwanted, which covers way more than just what is in that huge file.

But if an advanced user really want to use it:

Chromium:
![c](https://cloud.githubusercontent.com/assets/585534/6766612/28435b7c-cfe3-11e4-81ce-98862995f1db.png)

Firefox: can be added as `file:///[...]/Downloads/hosts/hosts.txt`.

Then this advanced user is free to download the zip version of that 30 MB file whener he feels like it's worth it (or set a cron job for it), instead of having the silly situation of uBlock thinking it needs to update it every 4-5 days.

**Comment by gorhill** [comment]
Also for the record: the storage used by the extension when pulling this file shoots beyond 100 MB.

**Comment by Mikey1993** [comment]
>  Also for the record: the storage used by the extension when pulling this file shoots beyond 100 MB.

Case closed.
Sorry.
