### ISSUE TITLE
whitelist for firefox

### ISSUE THREAD

**Issue by typhoon71** [uBlock-LLC/uBlock#1086]
I noticed last build (0.9.2.1 xpi for firefox) adds some stuff in the whitelist:

behind-the-scene
chrome-extension-scheme
chrome-scheme
opera-scheme
www.fufox.net

I read the release note but as far I understand they should not be needed on firefox.
Is it correct? Can they be removed "safely"?
If so can yo umake that they aren't added for the firefox version?

**Comment by gorhill** [comment]
`fufox.net` is something you added, it's not part of any uBlock's default.

`behind-the-scene` and `chrome-scheme` are needed on Firefox.

`chrome-scheme` whitelist web pages which URL resemble `chrome://[...]` -- this occurs often on Firefox, for addons for example.

`behind-the-scene` is to prevent uBlock from filtering behind the scene network requests. It is not recommended to remove unless you understand exactly all the consequences of doing so. [Required reading](https://github.com/gorhill/uBlock/wiki/Behind-the-scene-network-requests). Blocking behind-the-scene network requests has the potential to cripple seriously a browser, including preventing Firefox from downloading important data. If you are curious about what is going behind the scene, open the network request log, and select "Behind the scene", and let the tab open for a long period: you will have a sense of the network requests being fired in the background by the browser and/or installed addons, etc.

The others whitelist directives aren't used for Firefox, but if ever you import your uBlock settings onto another browser, it's good to keep them in order to ensure uBlock won't interfere with stuff which is not expected to be filtered by default. There is no harm to keep these whitelist directives in there.

**Comment by typhoon71** [comment]
OK, thanks.
