### ISSUE TITLE
Selected domains no longer appears in the popup

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1096]
The domain I have selected (allow, block, noop) no longer appear in the popup after I refreshed the page.
For example, for **github.com**, here's the rules I have:

```
github.com avatars0.githubusercontent.com * noop
github.com avatars1.githubusercontent.com * noop
github.com avatars2.githubusercontent.com * noop
github.com avatars3.githubusercontent.com * noop
github.com camo.githubusercontent.com * noop
github.com raw.githubusercontent.com * noop
```

I can't see any of these rules in the popup, the only domains I see are **github.com** and **google-analytics.com**.

**Version:** 0.9.2.3-dev.1 (same with 0.9.2.0) (Default lists + Default deny)
**Browser:** Opera 30.0.1812.0 (dev)
**OS:** Windows 7 64-bit
**Other extensions:** BetterTTV, Download Chrome Extension, F.B. Purity for Facebook, Google Dictionary (by Google), Imagus, LastPass, Reddit Enhancement Suite

**Comment by gorhill** [comment]
The popup will be populated only with domains/hostnames for which network requests occurred. For example, if no network requests occurred for `avatars1.githubusercontent.com`, it won't appear in the popup.

**Comment by ghost** [comment]
On this page, I'm supposed to see at least avatars*.githubusercontent.com and that's not the case.

Another example, same problem with Twitter, twitter need twimg.com for working properly, so I have added the rule `twitter.com twimg.com * noop` and I can't see the domain in the popup either.

**Comment by gorhill** [comment]
> On this page, I'm supposed to see at least avatars*.githubusercontent.com and that's not the case

I tried Twitter and `twimg.com` was in the popup -- but then there were images in the stream. Aside the expected behavior I mention above, I cannot reproduce what you mention.

I tried `github.com` and I could see very well all `avatar*.githubusercontent.com`.

You need to give me a case I can reproduce.

Check that network requests for images are not blocked before they reach the uBlock. Also, check whether these network requests are not made in the behind-the-scene scope. I see you are using Opera 30, which is a dev version I believe, so see if you have the same issue with Opera 28.

**Comment by ghost** [comment]
I have made a backup, restore from default settings then restore from my backup, nothing more, and now everything looks fine. No idea what happened..

Edit: Ok, so the problem is still here when I enable **FRA: EasyList Liste FR**, no problem without this list.

**Comment by gorhill** [comment]
Look in the request log, on twitter.com, if there are images in the twitter stream, you should see requests to `twimg.com`. Blocked or not, all network requests are reported in the popup. If they are not reported it's because they didn't reach uBlock.

**Comment by ghost** [comment]
Without EasyList FR, I can see request to `twimg.com`, with this list enabled, no request from twimg.

**Comment by chrisaljoudi** [comment]
It's probably that the script/frame that causes the requests to `twimg.com` is being blocked, so they never get the chance to occur.

**Comment by gorhill** [comment]
With or without EasyList FR, I can't reproduce.

**Comment by gorhill** [comment]
I will need a screenshot of the request log after forcing a refresh of `twitter.com`.:
- Open request log for twitter.com.
- Refresh twiiter.com.
- I want to see the output of the request log.

**Comment by ghost** [comment]
The list need to be up-to-date, no problem with the outdated list. I will take screenshot ASAP.

**Comment by ghost** [comment]
Here's the screenshot with List FR enabled: https://i.imgur.com/JH2iZy0.jpg

**Comment by gorhill** [comment]
Can I have the URL also? Transcribing from the image would be tedious.

**Comment by ghost** [comment]
https://twitter.com/DotPolitics/status/581143091702292480

**Comment by gorhill** [comment]
Thanks. I can't exactly reproduce but I definitely found a problem.

**Comment by gorhill** [comment]
There is a bad filter in EasyList FR, `||^$third-party`: I can't even make sense of that filter. The `||` is to anchor to somewhere in the hostname. `^` is a separator. So this makes no sense. The end result is that all 3rd-party requests are blocked.

Now the reason why uBlock does not report `twimg.com` is because the above filter, unexpected, causes an exception to be thrown. So I fixed this, and I will push the fix asap, but still, I don't know why that filter exists, it makes no sense.

**Comment by gorhill** [comment]
Fixed with d83ade9e2cceb988b6360583839559e83ec40c8f.

**Comment by ghost** [comment]
Glad you fixed it, thanks for your time. ;)

**Comment by smed79** [comment]
Hi; 
mistakenly added (maybe i am tired), really sorry for this false positive.
Fixed: https://hg.adblockplus.org/listefr/rev/db2fe3afe901#l1.12

Please report any issue on our forum: https://forums.lanik.us/viewforum.php?f=91 (not need registration ).

Med.
