### ISSUE TITLE
Not blocking PornHub ads

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1115]
I also remember that AdBlock wasn't blocking either. I don't know if this is allowed to post 18+ links, but anyway here's an example. Ads in right and at the bottom.

tinyurl.com/ogu2jk7

Ads come from brengoro.com

**Comment by dashed** [comment]
I think posting 18+ links is fine. I've seen folks do it all the time over at https://github.com/rg3/youtube-dl

**Comment by gorhill** [comment]
I don't maintain filter lists. You need to report this to whoever maintain filter lists. For EasyList, this is where: https://forums.lanik.us/viewforum.php?f=62.

**Comment by jcosentino** [comment]
I think the ads on pornhub.com are related to html5 canvas / fingerprinting, since the ads do get by Easylist (regardless of ADP, uBlock, etc.). When I experiment blocking readout or faking readout, the ads are gone when readout is blocked, but text appears when it is simply faked.

EDIT:
I just tried default deny for 3rd parties, and the ads were gone.
Any video will do, but here are three screenshots I took:
https://imgur.com/lZmKD4V,UnFFI0F,GTnZn6i#2
Take not of the descriptions.

I never toggled any of the 3rd party blocking options in uBlock, and depend on blocking filters and NoScript to block trackers.
EDIT: This tracker was causing the ads to load:
cdn1b.static.pornhub.phncdn.com; If this is disabled, then videos not not load.

**Comment by gorhill** [comment]
You have a specific URL for which I am supposed to see an "ads to the right of all videos"? I use default-deny for 3rd parties, and with just these two rules I do not see ads to the right:

    www.pornhub.com phncdn.com * noop
    www.pornhub.com rncdn3.com * noop

**Comment by tancrackers** [comment]
I just tried default deny for 3rd parties, and the ads were gone.
Any video will do, but here are three screenshots I took:
https://imgur.com/lZmKD4V,UnFFI0F,GTnZn6i#2

I never toggled any of the 3rd party blocking options in uBlock, and
depend on blocking filters and NoScript to block trackers. I emailed you
and edited my post because I don't know if you replied on github, or if
you just emailed me.

**Comment by Blutgang** [comment]
@tancrackers Uh...why would you block `cdn1b.static.pornhub.phncdn.com` with dynamic filtering? Wouldn't that cause the css to not load at all?

Hm...the ad is blocked if I create this filter: `||zenkreka.com^$third-party` or `||zenkreka.com^`. I'm pretty sure the P.H. guys will scan EasyList everyday to get around adblockers. (if EasyList does add this filter to their list)

**Edit**: I do not see the ad to the right of P.H. if I use default-deny and this ruleset.

```
* * 3p block
* * 3p-frame block
www.pornhub.com phncdn.com * noop
www.pornhub.com rncdn3.com * noop
```
