### ISSUE TITLE
Tooltips element picker page + Columns + Column sorting

### ISSUE THREAD

**Issue by Bloggerss** [uBlock-LLC/uBlock#1130]
take a look at the screenshot.

reason: didnt know what the buttons are for. especially there are two reload buttons which confused me.

cosmetic request: widen the filte field

besides: wouldnt it be nice to have captions for columns? if they could be sortable that would be great too

![element picker](https://cloud.githubusercontent.com/assets/11684711/6899862/8bda2c90-d6f2-11e4-99e1-58fca4dce351.png)

**Comment by Betsy25** [comment]
+1

**Comment by sn260591** [comment]
Good idea. Also, would not be bad to display the hidden objects on the list.

**Comment by Bloggerss** [comment]
display hidden objects: +1
i remember myself i was looking for them the first times

**Comment by gorhill** [comment]
Re. "sortable":

This would requires a much non-trivial code, and since the request log is real time, this could be expensive CPU-wise given that some pages may fire a lot of network requests even after the page is fully loaded.

Convinced me sortable is really useful, with **concrete** cases, not imaginary ones.

**Comment by gorhill** [comment]
Also, please stop throwing feature requests here. Some of them are already filed elsewhere. I want narrow, well defined issues which are have a chance to be closed, not an infinite or vague laundry lists which are impossible to mark as closed.
