### ISSUE TITLE
settings UI won't display, other weirdness

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#1132]
ff 36.0.4
ub 0.9.2.3

clicking the title bar of the pop-up UI will not display the settings UI
the console is showing an error sometimes, but i didn't copy it here because it doesn't happen all the time and it does not seem reliable (it changes)

another thing i have noticed which seems to coincide with this error is that a white-listed domain (power button off) is not necessarily white-listed - it may or may not be. if it is not, one or more refreshes seems to do the job

0.9.2.1 seemed to work ok, so i'll revert back to it for now

**Comment by atomGit** [comment]
the white-listed domain issue mentioned above exists in the current dev build also (30-March)

**Comment by atomGit** [comment]
i'm using 12bytes.org to test the white-listing problem, but i have not been able to come up with a reliable scenario to reproduce it - i thought it may have had something to do with browser cache, but now i'm not sure

i'll post some console messages shortly

**Comment by atomGit** [comment]
ok, when the site (http://12bytes.org/) is not white-listed, i'm seeing expected errors in the console:
"Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src 'unsafe-eval' *")."

these errors are because the JS for the slider is being blocked, as expected

the problem is that, sometimes, the errors remain when i white-list the domain - so it's as if uB simply is not white-listing the domain, or ignoring the domain in the white-list until the page is refreshed a few times

still, i cannot get the problem to reoccur on-demand - it seems random - and given what i've said, it seems like it may well be a browser cache issue

**Comment by gorhill** [comment]
Ok, the issue reported here is confusing.

> settings UI won't display

What about this? Now you are talking about javascript disabled for a specific site. Was this really ever an issue?

> white-listed domain (power button off) is not necessarily white-listed

Then

> i'm seeing expected errors in the console:
> "Content Security Policy: The page's settings blocked the loading of a resource at self ("script-src 'unsafe-eval' *")."

So you didn't provide any details about what are **all** your settings which differ from the default ones.

I need a clear picture of what you are doing, it's impossible for me to address vague issues.

See: https://github.com/gorhill/uBlock/blob/master/CONTRIBUTING.md#what-to-include, if this is followed precisely when the issue is opened the first time, this saves a lot of time to all.
