### ISSUE TITLE
[Chrome] "Block all popups" also blocks "open link in new tab"

### ISSUE THREAD

**Issue by F4z** [uBlock-LLC/uBlock#1143]
When I set to block all popups on site I can't open link in new tab/window.
![ublock](https://cloud.githubusercontent.com/assets/11742596/6928972/c48282c6-d7f7-11e4-9b1f-8da6d883218b.gif)

**Comment by gorhill** [comment]
Don't block all popups?

There is no reliable way to detect whether a tab is really opened by the user or not. The idea is to use "block all popups" as a last resort for when they are not filtered by the filter lists.

So by design.

**Comment by F4z** [comment]
I reported this because in Firefox it works properly, so if I good understand in browsers based on Chromium isn't possible.
Thank you for answer.

**Comment by gorhill** [comment]
@F4z I didn't notice the issue was marked "Chrome". I think in Firefox there is more information about whether a tab is opened by the user or not. In Chromium, there is a bit of information, but I do not think it distinguishes between a link clicked by a user, or a link for which a click event is triggered by a script. I will investigate further.

**Comment by gorhill** [comment]
Yeah, unfortunately not possible with Chromium to distinguish reliably whether a new tab/window is the result of a user right-clicking to open a link or the result of clicking anywhere on a page caused the new tab/window to open unexpectedly. Browser limitation.

Workaround is to right-click, copy URL address, paste in address bar.
