### ISSUE TITLE
[Discussion/Not-A-Bug] ownership transfer

### ISSUE THREAD

**Issue by lewisje** [uBlock-LLC/uBlock#1153]
I don't know whether this is temporary, but in case it isn't, most of the links to GitHub issues are broken now (just change `/gorhill/` to `/chrisaljoudi/` to load the issue links again).

**Comment by Betsy25** [comment]
gorhill & Deathamns simply pulled it, without any single explanation.

**Comment by lewisje** [comment]
Also, it looks like donations are finally sought; maybe with them, uBlock for Firefox could start auto-updating from Aljoudi's server when AMO is too slow.

The annoying thing is that a separate Chrome Web Store entry was made, so uBlock won't auto-update to 0.9.3.0

**Comment by chrisaljoudi** [comment]
@lewisje indeed, I plan to move the Firefox port over to use my server soon.

**Comment by chrisaljoudi** [comment]
@lewisje I apologize for the inconvenience regarding the Chrome Web Store — I'm aware.

It was gorhill's decision not to transfer the web store extension entry.

**Comment by Betsy25** [comment]
@chrisaljoudi Good idea.
.. and I might be a little rude thinking, but all non-issues posted, related to 3rd party lists ? Close Em !

**Comment by lewisje** [comment]
Will something similar happen to uMatrix?

**Comment by chrisaljoudi** [comment]
@lewisje I don't know whether gorhill will continue to maintain uMatrix, but I certainly can't take on uMatrix development at this point anyway (I have to have enough time to earn money for food, etc.).

**Comment by chrisaljoudi** [comment]
@Betsy25 yep, a cleanup of issues is soon to be underway.

**Comment by d48e2b388911** [comment]
While I don't have a problem with supporting developers. This quick transition to accepting donations is a little suspicious. I'm sure there is a logical explanation for all this but it sure is strange. Can we get a comment on the future of this project?

**Comment by chrisaljoudi** [comment]
@d48e2b388911 uBlock will always be free and open-source. Always.

Since I became the Safari maintainer, I've always accepted donations (because I have to do my own hosting for the update manifests and serving all the updates — and that costs money).

gorhill decided to transfer ownership — the reason is not known to me.

Since that happened — in addition to the fact that I'm about to start serving uBlock for Firefox from my server — the links to donate are now visible on the main project page, as well.

**Comment by muhasturk** [comment]
Why did you add lots of donate button almost everywhere? 

On the other hand, you said on your website that "MADE WITH LOVE AND CARE BY CHRIS.". As you know this not **NOT** true

**Comment by chrisaljoudi** [comment]
@muhasturk 

> Why did you add lots of donate button almost everywhere?

The changes are in progress. I'm sorry things aren't perfect — it's only been a few hours since the ownership transfer, and I'm working as hard as I can to make sure things are smooth.

I've cleaned up some of the extraneous donation buttons. 

Your patience is appreciated.

**Comment by alejandrolemus** [comment]
It would be nice if we stop accusing/abusing devs in here. I know changes were sudden and without explanation, but as I far as I know, @chrisaljoudi is not to blame, he just accepted the transfer @gorhill proposed.
As a matter of fact, it wouldn't surprise me if @gorhill dropped the project because he was too tired of dealing with people demanding/arguing over their favorite features (I know I would). 
Hopefully we will have more info soon. In the meantime people, remember these guys are doing all the development for free.

**Comment by lewisje** [comment]
@alejandrolemus wins this thread.

**Comment by spaghetti2514** [comment]
Without any kind of explanation from @gorhill given, I'm kind of suspecting an April Fools joke here

**Comment by DomT4** [comment]
Let's not scream at the new dev until he's had more than 20 minutes to actually get everything changed over. If it's like almost any other open-source project, It's hardly likely people are going to start suddenly plowing money into it regardless.

**Comment by lwatsondev** [comment]
"Joke" would imply it's funny.

**Comment by chrisaljoudi** [comment]
@spaghetti2514 [I thought about that, too](https://github.com/chrisaljoudi/uBlock/commit/6850fa0a262b8772a502c92750fe7a5bf74515f0#commitcomment-10530840) (in fact, I was quite stressed because I couldn't figure out whether it was serious or not) — but I don't know.

Transferring the repository ownership is pretty drastic, I'd say, but still.

**Comment by spaghetti2514** [comment]
> Transferring the repository ownership is pretty drastic, I'd say, but still.

Well I'm sure gorhill trusts you plenty enough for that, and the ~~joke~~ prank wouldn't seem real with anything less

**Comment by chrisaljoudi** [comment]
@spaghetti2514 yep. We'll find out soon-enough, I guess.

**Comment by ghost** [comment]
I'm guessing gorhill was overwhelmed by the massive increase in issues due to more browsers being supported so he's making sure that he only gets the Chrome issues with his own page.

**Comment by Betsy25** [comment]
Unfortunately this is no April fools, people.
http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-33#post-2476324

**Comment by ghost** [comment]
@chrisaljoudi 

Will the Firefox version be dropped from AMO? Simply signed and updated off-site, is that the idea?

**Comment by chrisaljoudi** [comment]
@kintpuash I don't have control over the AMO entry (I believe @Deathamns does).

But yes, the idea is to sign it and update it off-site (just like Safari) so everyone gets the updates quite quickly.

**Comment by ghost** [comment]
@chrisaljoudi Deathamns appears to have remove his account from uBlock on AMO. Only gorhill remains.

I'm puzzled why the other devs wouldn't at least create a smooth transition. Thanks for hanging in there btw.

**Comment by ghost** [comment]
@chrisaljoudi Sounds solid but I'm also for concurrently mirroring it on AMO for discoverability purposes.

**Comment by ghost** [comment]
@procrastinator7 @chrisaljoudi 

My reading of AMO guidelines, an extension hosted on AMO cannot independently update code? Should also continue to use the same identifier.

**Comment by pik** [comment]
I've never commented or contributed to uBlock before - but I've used software gorhill has made for a while now. It's really sad to see him move on, and I really appreciate everything he's done.

**Comment by ghost** [comment]
@kintpuash I wasn't aware of that. Too bad. 
Thank you for the continued dedication, @chrisaljoudi.

**Comment by ElDani82** [comment]
Raymond has added @AlexVallat as a developer over at AMO after he [requested of him](https://github.com/chrisaljoudi/uBlock/pull/1150#issuecomment-88879093) to take it over. I hope there won't be two separate Firfox project as well, so I hope you can find some common ground, @chrisaljoudi.

Anyway, in the midst of all this chaos, I wish to sincerely thank you for your willingness to continue with this project after its inventor and lead developer chose to leave.

**Comment by gitarra** [comment]
I want to thank @gorhill for creating this amazing addon and making it what it is, its sad to see you leave. The amount of hate and toxiticity this altruistic project has gained from some people is despicable, I understand that with the additional popularity gained from the Firefox crowd etc it has become too burdensome to maintain. Its unthankful work which some people take for granted with arrogance.

I'm just happy to see that ublock isnt dying and seems to be in good hands. Thanks to @AlexVallat as well for the willingness to pick up the Firefox version at AMO, as you seem to be knowledgeable of the Firefox addon ecosystem. I just hope the Firefox version wont stagnate due to all this, there are some of us who are immensely thankful, even though it always wouldnt seem like it.

Cheers, and thank you **_all**_ for your hard work.

**Comment by harshanvn** [comment]
@gitarra :+1:  Well Said! Cant say it better!

**Comment by gitarra** [comment]
Here's to hope the word gets out and we'll see some new interested contributors to help the project stay afloat. :soon: :beers:

**Comment by chrisaljoudi** [comment]
@gitarra The project _will_ stay afloat. Promise. :)

**Comment by hackel** [comment]
The way gorhill was so adamant about removing himself from the project makes me wonder of it wasn't for legal reasons. He mentioned possibly releasing his own version. I hope he isn't intending to complete with a closed-source alternative. That would explain his secrecy on the change as well.

**Comment by Betsy25** [comment]
@hackel
 afaik gorhill **never** wanted the project to become a monetary thing in the first place, nor was there any legal reason, so no, nothing of all that, I guess he just wanted to make this extension his (fantastic) puppy, spending time programming (in which he's superior), he just got tired of the enormous amount of "issues" being posted not related to the extension but rather about 3rd party lists and other non-issues, I guess it takes a whole crew of knowledged programmers in order to keep improving an extention which should run on all known flavors of all known browsers, simply impossible on your own, let alone, also replying and helping in countless "issue" tickets every single day.

Perfectly understandable. If he would have been threatened from anybody related to a commercial/concurrent tool, he wouldn't keep his extension for Chrome only either.

**Comment by RandomAcronym** [comment]
@hackel that part about closing the source code, read in the right context, is just the kind of comment that makes is seem like all gorhill's hard work is taken for granted. 
 (ex. Now that you stopped giving me free stuff all the time you are going to charge me now aren't you!)
But reast easy because this is a GPL licensed project and no one person can change that, not even gorhill. (Everyone involved would need to agree on a new license)

**Comment by dandv** [comment]
From https://github.com/gorhill/uBlock#about:

> Free. Open source. For users by users. **No donations sought.**

And to quote gorhill's probable reason for leaving [from the WildersSecurity forum](http://www.wilderssecurity.com/threads/ublock-a-lean-and-fast-blocker.365273/page-33#post-2476324), though he never gave any specific reason [when he requested to be removed as a collaborator](https://github.com/chrisaljoudi/uBlock/commit/6850fa0a262b8772a502c92750fe7a5bf74515f0#commitcomment-10530773):

> The more you give, the more many act as if you owed them even more. This is what ground me down in the long run. If the project has any intrinsic value, it will survive. The move was a huge relief for me. I have been postponing this for long now, thinking things might improve. They did not, from my point of view.

**Comment by RandomAcronym** [comment]
@hackel All he's done is fork this git with "issues" disabled. It's still GPL

**Comment by kurtextrem** [comment]
> I consider uBlock here to be feature-complete. I will keep maintaining the project here though so as to ensure it works just fine. If I add anything new, it will be because I decide to do so, for my own coding pleasure, as I do not accept any feature requests.

 ^ that states his opinion also.

**Comment by asantos3** [comment]
I guess I will comment here instead of submitting another issue.

@chrisaljoudi, why not creating a uBlock github organization with a few core developers like you, @AlexVallat and a few others? This would ensure that this mess doesn't come back when someone wants to get out.

**Comment by dashed** [comment]
I'm seriously suggesting for a name change. On the Chrone web store, many folks won't know why there are two extensions with the same name, and which of the two they should be using: https://chrome.google.com/webstore/search/ublock

Many won't be scouring on GitHub issues anytime soon to find out.

This is a fantastic extension, and @gorhill has done an amazing job. With the recent events that has happened, this fork, now spearheaded by @chrisaljoudi, cannot move forward in development and grow without an identity/name change. 

---

Just pick any name.

Maybe pick your next favourite SI prefix other than `micro-`: https://en.wikipedia.org/wiki/Metric_prefix#List_of_SI_prefixes

My suggestion: **mblock** / **macroblock**

---

Also, I like @asantos3's suggestion on creating a GitHub org.

**Comment by dandv** [comment]
Agree with @Dashed. The whole ownership story is confusing, and users should be presented with a succinct version of it.

**Comment by goetzc** [comment]
I agree with the last three of you @asantos3, @Dashed, @dandv 

An GitHub organization would avoid such problems in the future, both for the users and developers involved and using this software.

As for the name, nano is a popular prefix. But uBlock+ or uBlock Plus are also options someone is gonna use in some fork, as there are already [some old forks](https://github.com/chrisaljoudi/uBlock/wiki/Forks-and-%22forks%22-of-uBlock).

**Comment by RandomAcronym** [comment]
I suggest vBlock, as it (Nv) is the next letter in the Greek alphabet after Mu.

**Comment by kurtextrem** [comment]
I wouldn't recommend uBlock+ / uBlock Plus as it first of all copies Adblock Plus and second it is kinda uncool for gorhill, as it leaves the impression chris' uBlock is superior.
I vote for vBlock.

Edit: Actually, gorhill is changing his uBlock: https://github.com/gorhill/uBlock "uBlock₀" (uBlock origin)

**Comment by asantos3** [comment]
We already got NoScript, why not YesBlock?

**Comment by RandomAcronym** [comment]
Because I had nothing better to do; Here is my first attempt at a "vBlock" logo. I'll work on it some more if @chrisaljoudi is interested. 
![vblock](https://cloud.githubusercontent.com/assets/2810488/7037207/e5b25eba-dd6c-11e4-8b22-a336eae1f53f.png)

**Comment by rusvnc** [comment]
Thanks to @chrisaljoudi and of course to @gorhill for all their hard work. It is very much appreciated by the majority of users, I am sure. 

I am not at all bothered by donation requests and suspect most reasonable people are not. A few people feel so entitled that other people should work for them for free without so much as being able to request a donation! Hello -- if that's how you feel, go make your own software and stop complaining! 

I don't know why @gorhill transferred uBlock but I will probably continue to use his version, while installing the present versions for my other browsers.

**Comment by chrisaljoudi** [comment]
http://youtu.be/_D1TpddtVUA

**Comment by dandv** [comment]
OK, so what is the TL;DR about the state of the two projects, 2.5 years later?

I'm curious what motivated @gorhill to come back to [developing uBlock](https://github.com/gorhill/uBlock), after feeling overwhelmed in April 2015.

**Comment by lewisje** [comment]
I guess he was frustrated with how slowly Aljoudi was working on it, and he had some more ideas to tinker around with.
