### ISSUE TITLE
Should side ad space on outlook.com be collapsing?

### ISSUE THREAD

**Issue by RyanJanak** [uBlock-LLC/uBlock#1158]
The ad is blocked, but the space is still there. Should it be collapsing or is there some way to make it collapse?

Safari 8.0.4 | uBlock 0.9.2.3
![screenshot](http://i.imgur.com/jJgFPY8.png)

**Comment by chrisaljoudi** [comment]
@RyanJanak Hi!

Well, it does actually collapse the element that's the right column. However, `outlook.com` actually styles the "middle" content column to leave `160px` on the right:

![CSS right](http://cl.ly/aURr/Image%202015-04-01%20at%209.57.42%20PM.png)

Not much that can be done about this since it would require adding custom CSS.

Sorry about that.
