### ISSUE TITLE
Import last commit by gorhill

### ISSUE THREAD

**Issue by kurtextrem** [uBlock-LLC/uBlock#1178]
This isn't ported into this repo:
https://github.com/gorhill/uBlock/commit/465c4b65232a2d8e548e14ef3c77b138f937c3b2

**Comment by d4k0** [comment]
+1

**Comment by Betsy25** [comment]
+1

**Comment by kurtextrem** [comment]
There are some more now.
@chrisaljoudi

**Comment by chrisaljoudi** [comment]
@kurtextrem @Betsy25 @d4k0 

Thank you; I'm aware of the commits. There's a whole bunch of work I'm doing right now on my local branch — and since it includes improvements to the UI and general ease-of-use (see [the two milestones](https://github.com/chrisaljoudi/uBlock/milestones)), I deemed it wise to test all of those changes thoroughly before pushing them into `master`.

**Comment by kurtextrem** [comment]
Ok, sounds good.
