### ISSUE TITLE
[Chrome] Dashboard will not come to front, if it was already opened  earlier..

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#118]
As the title says, if the settings menu is already opened, and if you try to open settings window from another tab either by clicking settings bar/statistics button from uBlock UI, it will not come forward. As a side effect, below issues are spawned -
    - Behind the tab, another settings window will be openend.
    - Once you go to settings window, And you cannot go to your normal browsing tab (incognito window), it will not come to foreground. Settings window will come foreground instead. In this case, i either close settings window or minimize it, to go back to by browsing tab.

All this issues are observed when browsing in incognito. Browser is Chrome stable version on Windows 8.1

**Comment by fysics** [comment]
Some additional details based on my experience:

When **not** browsing in incognito, behavior is completely as expected.

When browsing incognito, launching uBlock settings spawns a new tab in a non-incognito window regardless of whether it is necessary. This new tab is not given focus. I think it can be agreed that on some level this is not expected behavior. 

I guess the real question here is: **What _should_ expected behavior be for adjusting settings while browsing incognito?**

**Comment by harshanvn** [comment]
> This new tab is not given focus.

hmm this is strange. I did not encounter this behavior. When you open settings window for the first time, from incognito window, behavior is as expected, i.e., settings window will be opened in normal window and focus is given to it. And then if you try to open the settings window from another tab (incognito), another instance of the settings window will be spawned instead of reusing the existing one, which i believe is not expected..

> What should expected behavior be for adjusting settings while browsing incognito?

The behavior should mimic the chrome's own settings window when it is opened thru wrench menu

**Comment by harshanvn** [comment]
118

**Comment by gorhill** [comment]
Fixed in 86ac9763b0a655987361958f1b47c44b9924e709.

**Comment by harshanvn** [comment]
Thanks!
