### ISSUE TITLE
Suggested ad-blocks

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1180]
I want to make my Adblock Plus-compatible filter called Ad-free libre web (please see https://gna.org/users/david_hedlund), part of uBlocks  3rd-party filters (chrome://ublock/content/dashboard.html). It does not have to be enabled, just having it there would be useful.

**Comment by ghost** [comment]
I'm getting a 403 on the adult list?

**Comment by davidhedlund** [comment]
@kintpuash I just uploaded it. I'll let you know when Its available.

**Comment by ghost** [comment]
Cool. I can see the benefit of a dedicated list as they are relentlessly tough to block.

**Comment by lewisje** [comment]
Are you also posting about these lists on the Adblock Plus forum? They sound like good candidates to add to SubscriptionList.

**Comment by davidhedlund** [comment]
@lewisje Thank you very much, thats a good idea.

**Comment by davidhedlund** [comment]
@lewisje Why does it not suit EasyList? I posted in the EasyList forum about one of the filters but got no feedback.

**Comment by lewisje** [comment]
Sorry, "SubscriptionList" is just the internal name that the Adblock Plus project uses for the page "[Known Adblock Plus Subscriptions](https://adblockplus.org/en/subscriptions)"; also, you might want to use a static filename for your lists, rather than putting the upload date in the filename.

Now I wasn't aware that you wanted your filters to be incorporated into EasyList, I thought you just wanted to publish standalone subscriptions.

**Comment by davidhedlund** [comment]
@lewisje Standalone is fine for me. I'm completely new with Adblock Plus.

**Comment by davidhedlund** [comment]
@lewisje I asked for help here https://adblockplus.org/forum/viewtopic.php?f=4&t=29400

**Comment by chrisaljoudi** [comment]
@lewisje @davidhedlund so, are these meant to be separate lists or just to be added to EasyList?

**Comment by davidhedlund** [comment]
Separate list.
