### ISSUE TITLE
Opera hasn't been updated with v0.9.3

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#1191]
As title says.
Thanks.

**Comment by bwat47** [comment]
Opera reviews all updates to addons on their addons page so versions are usually behind compared to the version on the chrome web store.

**Comment by bwat47** [comment]
looks like gorhill's version is the only version on opera's addon site atm (the chrome web store has gorhill's and chrisaljoudi's versions).  afaik he is still maintaining his own chrome version (and probably the opera one as well since its just the chrome extension repackaged). 

It should be noted that opera's addon site has a pretty stringent review process (all addon updates are reviewed by opera) so its usually a few versions behind the chrome webstore version.

**Comment by Mikey1993** [comment]
@gorhill, can you please update us on this?
Thanks.

**Comment by gorhill** [comment]
> opera's addon site has a pretty stringent review process

It's because of the longer time it take to review that I prefer to be sure that whatever version I post on Opera is free of bad bugs -- as I can't post emergency fixes. Only with time I can have confirmation that there is no crippling bug is in there.
