### ISSUE TITLE
update wiki to point to new repo location

### ISSUE THREAD

**Issue by mmlb** [uBlock-LLC/uBlock#1198]
The wiki still points to the old `gorhill` locations. I have sed'ed them out along with some white space EOL/EOF fixes. How would you like to consume them? I don't think this kind of mass-change should have just been pushed/edited by a drive-by-committer.

**Comment by Betsy25** [comment]
I made a few pull requests addressing these, however nothing was done with them, that's why I rebased my fork on girhill's repo, since I honestly don't expect much more change in this abandoned repo.
If only good programmers like @AlexVallat could pull their fixes into gorhill's repo, we still would have a straw of hope on a good, and maintained product where actual programming is the main objective.

**Comment by ghost** [comment]
@Betsy25 

> in this abandoned repo

You are aware that yesterday was Easter?

**Comment by ImSpecial** [comment]
@Betsy25 
It's retardedness like this why gorhill quit in the first place.

**Comment by LocutusX** [comment]
@Betsy25 Yeah, let me just echo what the others are saying - GTFO, or STFU.

People like YOU cause open source projects to die.

**Comment by chrisaljoudi** [comment]
> abandoned

Wow.

---

This is now resolved in wiki/[4b09bfdd](https://github.com/chrisaljoudi/uBlock/wiki/_history). Thanks a lot, @mmlb, for your help! It's deeply appreciated.
