### ISSUE TITLE
Update localized AMO descriptions

### ISSUE THREAD

**Issue by Ede123** [uBlock-LLC/uBlock#1221]
Just noticed that the German translation (others possibly, too) of the add-on description on addons.mozilla.org still points to gorhill's repository.

The localized descriptions should be updated.

**Comment by AlexVallat** [comment]
What a total pain, there are a _lot_ of localized descriptions! I've updated them now, thanks for reporting this.

**Comment by Ede123** [comment]
@AlexVallat: Don't you use Crowdin for those translations anymore? Since these strings are outdated, too...

**Comment by Ede123** [comment]
As it seems the ublock project on Crowdin still belongs to gorhill you should probably remove the link, create an own project and adjust the link or figure something out with gorhill...

**Comment by gorhill** [comment]
I asked Crowdin if they can fork/duplicate, they said it is not possible.

So this will have to be a new project on Crowdin. I could do it and give you manager's rights, probably best if you guys do it, because projects on Crowdin need approval, and you would have to point at the project on github.

One thing I would do differently is to change the format of description files. Text files cannot be uploaded to update a specific translation, this means the changes cannot be done externally. This is really a crippling limitation -- people can't submit pull requests for the description files.

The supported formats are listed [here](https://crowdin.com/page/tour/supported-formats), some of the ones which can't be uploaded are listed [here](https://support.crowdin.com/for-project-managers/best-practices/uploading-existing-translations/) (at the bottom). So using instead a format which allows upload saves a lot of time. This would just require a script to generate a text file from the translation files.

**Comment by AlexVallat** [comment]
@chrisaljoudi: This is probably worth creating a new issue for, depending on how you want to handle localisation?

As far as the AMO listing specifically goes, even if we aren't using Crowdin, I'm not sure removing the link is the right thing to do. The way I read it, that link is providing credit to those contributors on Crowdin who have provided work.
