### ISSUE TITLE
[Firefox] chrismatic.io Untrusted Connection

### ISSUE THREAD

**Issue by 5t3f4n** [uBlock-LLC/uBlock#1227]
This is not an issue with uBlock so I apologize in advance, but I don't know where else to post.
https://chrismatic.io/  reports <b>This Connection is Untrusted</b> in Firefox. It works fine in Safari.

![image](http://i.imgur.com/o5a7XPd.png)

System: OS X 10.10.3 (14D131)
Browser: Firefox 37.0.1 running in "safe mode"

**Comment by SW1FT** [comment]
Certificate problems. Do you have Kaspersky Internet Security by any chance?

**Comment by 5t3f4n** [comment]
No I do not have any kind of security software. Note that it works fine in Safari.
Shouldn't a certificate issue affect all browsers? And all people?

**Comment by SW1FT** [comment]
Certificate issues affect single browsers. I was talking about KIS because I had a similar issue with Firefox only and it was a certificate that I needed from Kaspersky to access some websites.
Regarding your issue, I suggest deleting cert8.db file located in \AppData\Roaming\Mozilla\Firefox\Profiles\PROFILE-NAME or simply resetting Firefox.

**Comment by chrisaljoudi** [comment]
Probably have the old certificate in cache. Can you try force reloading/emptying cache?

**Comment by 5t3f4n** [comment]
@SW1FT I don't have an \AppData\ because I'm not on Windows, which is evident from my original post. Appreciate the effort, but please at least read the whole post. It's not that long. I did, however, remove cert8.db from where my Firefox profile is actually located but it did not help.

@chrisaljoudi Yes I've tried reloading without cache and manually clearing everything as well. No difference.

Is there anything else I can do to troubleshoot short of starting with a fresh Firefox install/profile? It worked fine just a few days ago. The issue may or may not have surfaced after updating to 10.10.3.

**Comment by gitarra** [comment]
The server doesnt include intermediate certificates in the certificate chain.

You can see the issue here:
https://www.ssllabs.com/ssltest/analyze.html?d=chrismatic.io

It isnt an issue on your end.

Edit: Actually removing the cert database of Firefox would cause this issue, as you wouldnt have those intermediate certificates cached anymore. The reason we can connect to the site is that we have those missing certificates already cached in Firefox.

**Comment by chrisaljoudi** [comment]
Oops. Fixing.

**Comment by chrisaljoudi** [comment]
Fixed.

**Comment by chrisaljoudi** [comment]
Thanks for pointing this out!

**Comment by 5t3f4n** [comment]
Can confirm it's working as expected now.

gitarra:  thanks for explaining.
chrisaljoudi:  thanks for fixing.

**Comment by gitarra** [comment]
No problem :+1:
