### ISSUE TITLE
Feature request: hiding domains in ublock list

### ISSUE THREAD

**Issue by smlx** [uBlock-LLC/uBlock#1269]
Thanks for working on ublock. It's great!

I use ublock to filter 3rd-party requests by default. Of course, that means that visiting a new site can break stuff (e.g. I need to enable a CDN domain or something).

There are also some 3rd-party domains which I _never_ want to enable: google-analytics.com, newrelic.com etc.

It would be great if I could hide these "known bad" domains in the ublock drop-down list because it would greatly narrow the list of 3rd-party domains to try enabling in order to fix a site.

Maybe they could be hidden behind a single click-to-expand "known bad" button or something similar?

**Comment by atomGit** [comment]
personally i think that's a bad idea - for example, you hide a host that you're sure you never want to allow, then run into a site where it's required for the site to function - this can be the case even for a site that uses google analytics - now you scratch your head trying to figure out why the site is broken because you've hidden the domain

this just adds more complexity in my opnion

**Comment by smlx** [comment]
Do you have an example site which breaks without google analytics?

> ...now you scratch your head trying to figure out why the site is broken...

This is already the case for anyone blocking 3rd party domains by default - this feature would make it **easier** to figure out why the site is broken!

**Comment by atomGit** [comment]
> Do you have an example site which breaks without google analytics?

no, but i know that some exist - even some of the filter sets whitelist google analytics for particular domains that would break without it

> This is already the case for anyone blocking 3rd party domains by default  ...

how so?  if you set a block rule for a domain, whether it be by setting a default block policy or blocking the specific domain, the domain still appears in the list in the pop-up, whereas it is hidden from the list and required for the site to function, you wouldn't know what the problem is without checking the network log

**Comment by gorhill** [comment]
> an example site which breaks without google analytics

Search `google-analytics` in https://github.com/gorhill/uBlock/blob/master/assets/ublock/unbreak.txt, https://github.com/gorhill/uBlock/blob/master/assets/thirdparties/easylist-downloads.adblockplus.org/easyprivacy.txt.

**Comment by smlx** [comment]
@gorhill Ah thanks for the correction; I hadn't realised that google analytics could break sites in that way.

@atomGit It wouldn't be completely hidden, just behind an expandable menu. Most of the time such tracking domains are irrelevant and only seeing CDNs, SaaS etc. domains in the main list makes it that much easier to figure out which is required to fix the site.
