### ISSUE TITLE
Currently using µBlock together with HTTP Switchboard.

### ISSUE THREAD

**Issue by skudo12** [uBlock-LLC/uBlock#127]
I followed your suggestion in "The road ahead" issue in HTTPSB. You only mentioned there to disable parsing of ABP filters and all ABP Compatible filters in HTTPSB. However you did not mention about disable hosts based filter in µBlock [example is the Hosts file ad server list]. Should I disable them and let HTTPSB to do the blocking?

**Comment by gorhill** [comment]
I have no reference opinion about this.

HTTPSB blocks with 100% certainty. In uBlock, an exception filter somewhere can always counter, for good (to fix a page breakage) or bad (if you want to block completely with 100% certainty a hostname, say google-analytics.com).

Hostname-based blacklisted filters are quite well optimized in HTTPSB and uBlock (same data structure), since it doesn't depend on finding a pattern, but rather looking up tokens, so to have these lists both selected in HTTPSB and uBlock I don't see this as a performance issue.

Personally I enable these hosts in both HTTPSB and uBlock. If I disable HTTPSB, uBlock can still pick up most of these blacklisted sites, while sort of guaranteeing pages won't break.

Thinking of it, malware domains could be disabled in uBlock, and let HTTPSB do that part, since there are low likelyhood these will ever be hit, so no need to have them being enforced on both extensions, even less so if safebrowsing is enabled in Chromium (or derivatives).

**Comment by skudo12** [comment]
Thanks for the input. I'll try what you suggest. About malware domains, I am even thinking of disabling it in both µBlock and HTTP Switchboard.

**Comment by ghost** [comment]
> About malware domains, I am even thinking of disabling it in both µBlock and HTTP Switchboard.

Hm, why would you do that? If using safebrowsing makes this list really
redundant is not sure. And keeping it enabled doesn't hurt on the other
hand.
