### ISSUE TITLE
Preferences not shown if no window is visible

### ISSUE THREAD

**Issue by TraderStf** [uBlock-LLC/uBlock#1282]
On Mac Safari, if you click the checkbox it does not show the preferences if there is no window already opened and visible (not minimized in the Dock).

Some extensions show (un-minimized) the minized window, not uBlock.

<i>Safari opens a new URL in a minimized window and un-minimized it... stupid as you quit the site where it was... must do a ~option-backward to restore the previous site in a new window.</i>

**Comment by 5t3f4n** [comment]
Can reproduce. However, I have not been able to find another extension that doesn't behave the same way. So this may or may not be an issue with Safari and not the extension. Can you give an example of one that works the way you want it to?

On another note…
Having a checkbox to display the preferences is an ugly workaround to begin with. I would suggest replacing that with a proper button, but I suspect that's not possible due to Safari limitations. If that's the cause it should just be removed entirely. A checkbox suggests you're enabling/disabling something, and the random nature of its state (depending on how many times you've opened the preferences from there) only adds to the confusion.
