### ISSUE TITLE
Further development for Firefox

### ISSUE THREAD

**Issue by TennoDiablo** [uBlock-LLC/uBlock#1287]
Just a little question.

As you may know, addons for Firefox have to be signed from version 41.0 onwards, otherwise you can´t install them. Also the development of Adblock Edge won´t continue, so I switched to µBlock after I could solve my problems with YouTube and Bing. This might be a stupid question, I know (sorry for that), but I just want to make sure that I don´t have to look for a new alternative a few months later. I´m also a little confused because AMO always lists a much older version (atm it´s 0.9.1 instead of 0.9.4.5) and the addon is marked there just as "ok" for know.

So: Is µBlock already signed or do you plan to stop developing for Firefox?

**Comment by 5t3f4n** [comment]
This has been talked about here #764 and here #1166. It is my understanding that the AMO version will be signed by default, at least once it gets final review status.

Could we get a confirmation from @AlexVallat on this?

**Comment by AlexVallat** [comment]
The AMO version will always lag significantly behind the latest version, due to the length of the review process. The current latest release is [0.9.3.5](https://github.com/chrisaljoudi/uBlock/releases/tag/0.9.3.5) which has been already submitted for review to AMO and is, at present, at position 92 of 104 in the queue.

There are no plans to stop developing for Firefox, and release versions will continue to be submitted to AMO (and consequently signed by AMO).

There is an open question for signed development versions, we don't know quite how that is going to play out yet. Ideally they would also be made available as signed by AMO, but it is not yet clear what processes AMO will have in place for this. If it turns out to be impossible to produce AMO-signed builds in an automated and timely fashion, then we may have to say that only releases are signed, and dev builds will require a version of Firefox that does not require signing (like the Developer Edition).

**Comment by TennoDiablo** [comment]
Okay, I understand, thanks for your help. :)
