### ISSUE TITLE
[Firefox] Can't watch France 24 Live with ublock activated

### ISSUE THREAD

**Issue by logos88** [uBlock-LLC/uBlock#1289]
I can't watch France 24 Live with ublock activated. It never starts the video. All the filters and rules are the ones that comes in default.
http://www.france24.com/en/livefeed/

**Comment by gorhill** [comment]
> All the filters and rules are the ones that comes in default

Work fine from here using defaults settings, Chromium 41/Firefox 37.

**Comment by logos88** [comment]
I have tried in Opera with the default rules and there it works correctly. But in Firefox it doesn't works. When I turn off ublock in Firefox then the video is loaded. I don't know why.

**Comment by chrisaljoudi** [comment]
@logos88 but you are able to watch it with uBlock disabled?

**Comment by logos88** [comment]
yes, if I disable uBlock I can watch it @chrisaljoudi

**Comment by logos88** [comment]
I have tried to disable all the other extensions but it's still the same

**Comment by hairycactus** [comment]
@logos88 — Could it be one or more of your filter-lists making the France 24 Live video take a longer time to load in Firefox, such that it appears not working ? How long did you wait at the page ?

I just saw uBlock 0.9.3.5 at AMO & installed it in my Firefox. I am able to watch the live video feed at the France 24 Live webpage. Likewise when I try with uBlock₀ 0.9.4.5 enabled instead.

**For uBlock/ uBlock₀ tested separately with France 24 Live:**
The only "unusual" observation is the relatively long waiting time taken for the video to load. (This could be due to my slowish connection.) It shows a black blank screen for 5–10 secs, followed by a "spinning circle" screen for 25–30 secs. After that, the video plays normally.

**With uBlock/ uBlock₀ disabled:**
No blank black screen, spinning circle" screen for 5–7 secs, followed by the live video feed which plays normally.

My specs: FF 33.1.1 (x86), Adobe Flash 17.0.0.169 plugin (x86), Win 7 SP1 (x64), non-EU IP address, slowish connection (50–80 KB/s).

**Comment by logos88** [comment]
I have just solved it. It wasn't the time, I have tested waiting a few minutes and nothing. I use Linux, and for the flash player I use "fresh player plugin" to be able to use the chromium Pepper Plugin API in Firefox. I have discovered that "fresh player plugin" wasn't updated to the last version, and when I have updated it the video has started to work perfectly again even with ublock activated.

I don't know why the last version allowed me to watch the video when I had ublock disabled and didn't allow me when it was enabled. It's weird.

Sorry for the inconvenience, I didn't want to trouble you because something related to my flash version. And thanks for the help!
