### ISSUE TITLE
Opera Store link

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#1296]
gorhill/uBlock and chrisaljoudi/uBlock have the same link to Opera Store in Readme.md, it seems you have to create new extension there

**Comment by DaAwesomeP** [comment]
The Opera store says version 9.4.5, which is odd since the real latest release is 9.3.5.

You can install it manually by downloading the latest Chrome ZIP from the releases page and extracting it. Then go to the Opera extensions manager and click the Developer Mode button. Then click load unpacked extension and navigate to and select the `uBlock.chromium` folder. It should now install the latest version. _Be sure to disable the old one!_

**Comment by mikhaelkh** [comment]
@DaAwesomeP, that's because it is by gorhill. Chrisaljoudi must create new extension but he is not very responsive.

**Comment by chrisaljoudi** [comment]
@mikhaelkh it's not about responsiveness — it's just that moving from maintaining two browsers and stores (Safari and Chrome) to three isn't quite the top thing on the todo list.

**Comment by mikhaelkh** [comment]
Yep, sending all Opera user to wrong repository — clearly not top priority to fix))

**Comment by DaAwesomeP** [comment]
You might add a somewhere note about installing the latest version to Opera manually as I did above.
