### ISSUE TITLE
Add GNU Privacy filters

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1301]
See:

gorhill/uBlock@c6cb4345f2b2696784ad89faf911416560f91df0

Good filter list to add for the community (I already added it to my own uBlock install)

**Comment by lewisje** [comment]
I found that it broke Raw Story, but it's still a decent list, as if Fanboy were maintaining a "Super Enhanced" tracking list.

**Comment by davidhedlund** [comment]
@lewisje @metaphoricgirrafe That is counter productive as that filter is merged from EasyList, EasyPrivacy, and Fanboy Social.

http://gnuzilla.gnu.org/filters/blacklist.txt is generated from http://gnuzilla.gnu.org/filters/retriever/

http://gnuzilla.gnu.org/filters/retriever/update.sh using:
- https://easylist-downloads.adblockplus.org/easylist.txt
- https://easylist-downloads.adblockplus.org/easyprivacy.txt
- https://easylist-downloads.adblockplus.org/fanboy-social.txt

**Comment by ghost** [comment]
@davidhedlund 

uBlock parses filters, so in theory no overlap.

**Comment by lewisje** [comment]
@davidhedlund I guess then there was a faulty filter the last time that script retrieved them, because I use EasyList, EasyPrivacy, and Fanboy's Annoyances (which includes the Social Blocking List), and Raw Story's layout was fine before and after the Gnuzilla list was enabled but broken while it was enabled; I just checked again and uBlock has no updates suggested for any of the lists, Raw Story is broken while GnuZilla is enabled, and it's not broken when GnuZilla is disabled.

I think it's because that script is oversimplifying some of the filters; I noticed the offending filter `||netdna-cdn.com^$third-party` in Gnuzilla but not _quite_ in any of the source lists, although all three of them do have filters dealing with netdna-cdn.com

**Comment by davidhedlund** [comment]
@metaphoricgirrafe @kintpuash @lewisje http://gnuzilla.gnu.org/filters/blacklist.txt is now updated with these lines thanks to Rubén Rodríguez:

! Partially based (taking only url based, third-party filters) on:
! https://easylist-downloads.adblockplus.org/easylist.txt
! https://easylist-downloads.adblockplus.org/easyprivacy.txt
! https://easylist-downloads.adblockplus.org/fanboy-social.txt
! Check http://gnuzilla.gnu.org/filters/retriever/ for the whole source.

**Comment by ghost** [comment]
@davidhedlund Thanks I didn't know it was based on those sources.

Though I still think http://gnuzilla.gnu.org/filters/blacklist.txt is worthy as it does not merge the hundreds of exception rules from the other filters.

E.g. EasyPrivacy has the rule `@@||lg.com^*/foresee/foresee-trigger.js` but the GNUzilla filters doesn't make the exception.

From the privacy perspective I think the GNUzilla filters are the way to go.

**Comment by chrisaljoudi** [comment]
Fixed in ac76e42207d4cd7eaacb0e0ef9624a4f49f1b062.

**Comment by davidhedlund** [comment]
@chrisaljoudi Which version of uBlock will add the GNU Privacy filters?

**Comment by lewisje** [comment]
next release; gorhill already did it in uBlock Origin

**Comment by davidhedlund** [comment]
@lewisje What's next release version?

Are uBlock Origin and uBlock synced in development?

**Comment by lewisje** [comment]
They're not synched, and the next release version is whenever chrisaljoudi decides to turn the current codebase into a release.

**Comment by davidhedlund** [comment]
@lewisje @chrisaljoudi I didn't find the GNU Privacy filters in uBlock 0.9.4.0.
