### ISSUE TITLE
bring back per-site switches and strict domain blocking

### ISSUE THREAD

**Issue by wolftune** [uBlock-LLC/uBlock#1306]
I don't understand why per-site switches and strict domain blocking were removed instead of just making them something advanced users could choose to enable.

**Comment by lewisje** [comment]
Use uBlock Origin then; I guess chrisaljoudi just wants to make this extra ~user-friendly~ (a.k.a. less powerful).

**Comment by wolftune** [comment]
I disagree. I really _like_ the user-friendly aspects, and I don't mind if he doesn't add more complexity. But should keep working functionality and just keep it for advanced users if it seems too complex for beginners.

My view is that the per-site switches should _perhaps_ be advanced-only but I somewhat like the domain blocking as default. Only I don't care enough to make a big deal about it. I just think keeping them opt-in is better than removing.

**Comment by gorhill** [comment]
The rationale behind strict blocking was to actually protect **less** advanced users, as reported in #1013 ("phishing trick").

Similarly, to be able to block obnoxious popups at the click of a mouse for when no static filters exist yet for popups on a site is to help **less** advanced users, the alternative being having to craft static filters such as `||example.com^$popup` option.

Same with the cosmetic filtering switch, which is more convenient than having to come up with a filter such as `||example.com^$elemhide`.

Removing the per-site switch features benefit ABP (and other blockers) in my opinion, by removing an edge to uBlock which was useful to **less** advanced users.

**Comment by wolftune** [comment]
@gorhill I agree with you, that's convincing. I like the per-site switch stuff and the hard domain blocking by default. @chrisaljoudi can we please bring these things back?

**Comment by chrisaljoudi** [comment]
https://chrismatic.io/ublock/philosophy/

**Comment by wolftune** [comment]
@chrisaljoudi Thanks for the reference, mostly that is fair. I'm not saying this needs to be a democracy or my requests honored. I appreciate that my request is welcome to be made.

I don't understand specifically why per-site switches aren't something the average user would like. Either the average user will not want to do _anything_ besides have the plugin installed _or_ they will want to easily achieve particular aims such as "whitelist this one site for popups but not for other things". In other words, I think of it as the desire of the average user being "block absolutely all tracking and all ads except when I need to let something through to do a function I care about (ideally this is all perfectly automatic with no need to manage it myself, of course)".

I also think enough users would like hard domain blocking that keeping it as an _option_ makes sense.

My overall feeling is: _implementing_ these things might not fit the main goal, but that doesn't justify removing them when they are already implemented. So, that's why I'm _requesting_ that they be retained as _options_.

Thanks for your time.

**Comment by spongbros** [comment]
I install uBlock with malware domain and shock site filter lists enabled on the browsers of friends and relatives. With strict blocking, all undesirable sites are blocked before they have a chance to load, keeping users of all skill levels safe without fuss or fury. I can't speak for every single user of uBlock but for my use case, this is the most important and desirable function of a blocker. I used to use a combination of µBlock and µMatrix to block websites but relatives quickly became frustrated with false positives (which weren't easy to correct or bypass for less tech-savvy users in µMatrix); with uBlock's implementation of strict blocking, the blocking notification became user-friendly and easy enough to bypass while still providing a necessary deterrent to convince them to not continue to the blocked site.

Due to its continued support of strict domain blocking, I am in the process of switching everyone to uBlock Origin where possible. However, my main browser is Safari; uBlock Origin doesn't have a Safari version so I'm stuck with a blocker that doesn't do what it needs to do to provide a safe, worry-free web browsing experience.

Whether or not strict domain blocking is reinstated, thank you for taking this feedback into consideration.

**Comment by atomGit** [comment]
i agree with the OP and would add that the average user might not expect a site to load that is on the malware list, for example, expecting it to be blocked instead

since there was a prompt when connecting to a blocked site, i don't see how removing this behavior is any more user-friendly and, in fact, it may be the opposite since it was nice to know that a potentially malicious site was blocked which would further discourage creating allow/noop rules for it whereas, without the block notice, they may be more likely to allow content

**Comment by ghost** [comment]
I agree, strict blocking should be the sane default, and the per-site switches available **at least** as an advanced option, though they're not that complicated to just include by default, IMO.

Is there any way to block all popups on a certain site right now with the per-site switches gone? `||thepiratebay.se^$popup` doesn't do anything.

**Comment by ghost** [comment]
`|http$popup,domain=thepiratebay.se`

**Comment by ghost** [comment]
Thanks!

**Comment by wolftune** [comment]
Thanks for keeping this open for consideration. I changed the title not to specify advanced as @gorhill is convincing in pointing out that these functions are actually important for non-advanced users.

Strict blocking is comparable in some ways to Apple's requirements for signed devs for installing programs but is more legit as this is from the users. When Apple blocks the install of an unrecognized app (because it wasn't from a signed developer), people don't say "WTF Apple!" usually. They say, "oh, I dunno what this is, but sounds bad, nevermind, close, cancel". This actually hurts free/lbre/open apps and pushes everyone into the App Store, which is something I find troubling. But in our case, the block lists are done by the community. So, if some site is a malicious or tracking or advertising thing, then strict blocking isn't going to result in regular users feeling annoyed at uBlock; instead, they will decide to leave the site in question — which is almost always what we want to promote. Sites that get on blocklists are there for good reasons in almost all cases.

Now, having said that, I think the UI could be better so that the experience of per-site switching and of strict domain blocking is actually a better experience for average users. No rush, but please consider bringing these back sometime. Thanks

**Comment by rnc** [comment]
I would agree - I would like to see them back. Further, taking NoScript UI as an example, the ability to be able to specify 'Temporarily allow foo.com" is extremely useful - it allows me to work out whether that site is required. I could imagine a similar facility for UBlock.

**Comment by wolftune** [comment]
@rnc uBlock already has the "temporarily allow" function, it's just only in the advanced UI, and it's using the color coded stuff rather than text.
