### ISSUE TITLE
RSS icon in Google Alerts is blocked

### ISSUE THREAD

**Issue by sojusnik** [uBlock-LLC/uBlock#1308]
Hi,

when uBlock is active, the RSS icon in [Google Alerts](https://www.google.at/alerts) isn't present ([picture](http://i.imgur.com/Qtb88Xe.png)). Only after deactivating uBlock, the icon is [back again](http://i.imgur.com/NM43O0c.png).

What is the proper way to debug which list is causing this?

Best!

**Comment by lewisje** [comment]
First, watch this: https://github.com/chrisaljoudi/uBlock/wiki/The-network-request-logger

Then, search for the offending filters within your subscriptions; unfortunately, you'll need to open each list one-by-one because the Request Logger doesn't yet tell you which subscription each filter came from: https://github.com/chrisaljoudi/uBlock/issues/1232

**Comment by 5t3f4n** [comment]
Do you have any non-default preference or filters?

I know Fanboy's lists have some very generic filters for anything with rss in it, so unless you're using default filters only I would start by checking those.

**Comment by sojusnik** [comment]
@5t3f4n 
Indeed. I activated some lists to prevent tracking. I'll have a close look on them, thanks!
