### ISSUE TITLE
Force uBlock to be On

### ISSUE THREAD

**Issue by spec1re** [uBlock-LLC/uBlock#1341]
We deploy Firefox and uBlock for all our users, but some website suggest them to turn it off and unfortunately they do, instead to just whitelist that particular site.

Is there any way to force uBlock to be always on, maybe via mozilla.cfg and lockPref? Couldn't find anything in about:config.

Thanks in advanced.

**Comment by anewuser** [comment]
Just teach your users to use the [large power button](https://github.com/chrisaljoudi/uBlock/wiki/Quick-guide:-popup-user-interface#the-large-power-button). That will turn it off only for the current site.

**Comment by spec1re** [comment]
Sorry but that's not an option, to teach them to not do anything is like a never-ending story and you know it. :( Still sometimes, unfortunately uBlock is off, how to make it on without disturb the users? Where is the setting stored, that tells firefox uBlock is on or off? 

Any help is much appreciated.

**Comment by anewuser** [comment]
@spec1re why are you relying on browser extensions, anyway? You should be blocking ads on the server/proxy side.

**Comment by ghost** [comment]
@spec1re, maybe you need something like this https://addons.mozilla.org/en-US/firefox/addon/public-fox/ (also search for "kiosk" in AMO)

**Comment by chrisaljoudi** [comment]
I don't know of a way to do this (@AlexVallat: do you?). I did come across this [similar discussion](https://support.mozilla.org/en-US/questions/976357), though, which might be helpful.

In any case, this doesn't seem like something that uBlock is responsible for (if I understand what you're asking correctly) — rather seems like a Firefox issue. Am I misunderstanding?

**Comment by AlexVallat** [comment]
If what you are asking for is a way to prevent users from disabling an add-on from the add-ons page, I'm pretty sure that's not possible, by design. Your best bet would probably be some sort of kiosk or parental controls software as @gwarser suggested, but I've no experience with any of them so can't recommend anything specifically.

**Comment by spec1re** [comment]
Anyhow a bit more control for admins would be nice, control over on/off - filters - whitelist etc., so we can deploy default settings with the initial setup.

atm I'm editing eg. background.js and filter-lists.json in the xpi, but this is not very handy, moving thins to about:config would be nice.

**Comment by gorhill** [comment]
> bit more control for admins would be nice

~~I suppose uBlock could read a fixed JSON file at **install** time from its installation package (`/defaults.json`), which JSON file would be exactly matching its backup format (so its content can be generated using the _Backup_ button), and use the content of that JSON to initialize itself. By default it would be empty -- meaning behave as of now, otherwise it would just use the content to fill its default settings.~~

**Edit:** Never mind, that would not work, one can't modify a package on Chromium, and I suspect this will be the case with FF too soon with signed packages. (Maybe `vAPI.localStorage` to store defaults...?)
