### ISSUE TITLE
Fails to load youtube object in chrome

### ISSUE THREAD

**Issue by akarapatis** [uBlock-LLC/uBlock#1360]
When plugin enabled in the following link it fails to load the youtube object:

http://tedxtalks.ted.com/video/TEDxACADEMY-Toli-Lerios-The-Sil

uBlock 0.9.4.0
Chrome Version 42.0.2311.135 (64-bit)
OS: Ubuntu 14.04 64bit
Default settings

**Comment by chrisaljoudi** [comment]
The following filter is in EasyPrivacy:

```
_stats.js?
```

which causes the page to break (due to its reliance on a script named `magnify_stats.js`).

The solution to make TEDx work again is to add an exception filter; something like:

```
@@||ted.com^/*/magnify_stats.js$script,domain=ted.com
```

However, this is an issue with EasyPrivacy, not uBlock itself. [I've reported it to the list maintainers](https://forums.lanik.us/viewtopic.php?f=64&t=22626), so this should be fixed soon via an update to the list.

**Comment by akarapatis** [comment]
Thx for the reply. I also show the log that a rule was blocking but didn't how to fix it. 
I 'll keep an eye in the future and see if similar things occur from the filters.
Thx

**Comment by ryanbr** [comment]
https://hg.adblockplus.org/easylist/rev/0d171ac67cfa
