### ISSUE TITLE
XPath parent element

### ISSUE THREAD

**Issue by davidhedlund** [uBlock-LLC/uBlock#1369]
Forum spam is common but can be prevented by blocking specific text (ex "Spam goes here" or "`<div>User bar*</div>`" below). Can uBlock do that?

Example:

```
<div>User foo: I think I just solve it.</div>
<div>User bar: Excellent!

Spam goes here</div>
```

**Comment by ghost** [comment]
Element hiding is done by injecting CSS before the page loads.

There is no CSS selector for "text content matching". Adding support for such a feature would require javascript (search for all elements, then search for the text in them) instead of CSS, would be VERY slow (would noticeably slow down page loading), and would violate the adblock CSS format.

Therefore this isn't doable and will probably never be added.

Defeating spam is the job of the site owners, not addons.

**Comment by seanrand** [comment]
If you want to filter based on specific words contained in text e.g. "spam", this is not possible to do with uBlock, which uses the [AdBlock Plus filter syntax for element hiding](https://adblockplus.org/en/filters#elemhide).

To expand on this a bit, there [was a draft for a `:contains()` selector in CSS3](http://www.w3.org/TR/2001/CR-css3-selectors-20011113/#content-selectors) which would have made this possible, but the proposal apparently [didn't make it into the specs](http://www.w3.org/TR/css3-selectors/#content-selectors).
Extending AdBlock Plus's filter syntax to allow XPaths would make this sort of filtering possible, but neither AdBlock Plus or uBlock support this [due to performance and other reasons](https://adblockplus.org/forum/viewtopic.php?p=5963#p5963).

**Comment by davidhedlund** [comment]
@seanrand @ublockuser Thank you guys.

**Comment by ghost** [comment]
@davidhedlund Ublock Origin now implements :has() and :xpath() selectors. The latter can be used to block elements by content.
https://github.com/gorhill/ublock/wiki/static-filter-syntax#xpath

**Comment by davidhedlund** [comment]
@victortoulouse Thank you.

However, gorhill blocked me after I issued a [related bug](https://github.com/gorhill/uBlock/issues/2017) in uBO.

**Comment by davidhedlund** [comment]
https://github.com/gorhill/uBlock/issues/2017

**Comment by davidhedlund** [comment]
@victortoulouse 

> pornhub.com##:xpath(/html/body/div[12]/div/div[6]/div[3]/div[2]/div[1]/ul/li[5]/div/div/div[1]/a/div/i[@class="premiumIcon"])

This will find the Premium thumb as described in https://github.com/gorhill/uBlock/issues/2017 but how do I block the parent <li> of it?

Any help is deeply appreciated as I've spent hours on this issue.

**Comment by davidhedlund** [comment]
@victortoulouse Solved: `pornhub.com##:xpath(//i[@class="premiumIcon tooltipTrig"]/ancestor::li)`

**Comment by davidhedlund** [comment]
@gwarser [Issue](https://github.com/gorhill/uBlock/issues/2017) to remove premium thumbs in pornhub.com solved here

> `pornhub.com##:xpath(//i[@class="premiumIcon tooltipTrig"]/ancestor::li)`

**Comment by davidhedlund** [comment]
@gorhill [Issue](https://github.com/gorhill/uBlock/issues/2017) to remove premium thumbs in pornhub.com solved here

> `pornhub.com##:xpath(//i[@class="premiumIcon tooltipTrig"]/ancestor::li)`

**Comment by davidhedlund** [comment]
[Issue](https://github.com/gorhill/uBlock/issues/2017) to remove premium thumbs in pornhub.com solved here

> `pornhub.com##:xpath(//i[@class="premiumIcon tooltipTrig"]/ancestor::li)`
