### ISSUE TITLE
Change of ownership

### ISSUE THREAD

**Issue by marsfan** [uBlock-LLC/uBlock#1375]
Hi,
First off I am sorry that this does not fully follow your guidelines, but I do not have an account for reddit, which is the other cited place to get answers.

I am a bit confused over the whole change of leadership thing with uBlock. So Chris is now the lead dev, but this ublock still exists. Why did this happen and which repo should I use to download the newest and most feature rich (but still resource light) version of ublock? Also, what is the advantage of using the other repo?

Also, maybe you could leave this issue up so that people have a single place to clarify all of the possible confusion.

**Comment by 5t3f4n** [comment]
https://github.com/chrisaljoudi/uBlock/issues/1153#issuecomment-89716858
https://github.com/chrisaljoudi/uBlock/commit/6850fa0a262b8772a502c92750fe7a5bf74515f0

**Comment by marsfan** [comment]
Thanks for finally pointing me in the rightdirection . What is the advantage of ublock origin over ublock?

**Comment by 5t3f4n** [comment]
There is no straight answer to that as each project will most likely appeal to different people. But your question has been asked many times before so I suggest you take a moment and read some pages and do some searches.

> lthough both projects are essentially the same as of 0.9.3.0, they will probably start to diverge as time goes (update: they already [started to diverge](https://github.com/chrisaljoudi/uBlock/issues/1259) feature-wise).

https://github.com/gorhill/uBlock
https://github.com/chrisaljoudi/uBlock/

**Comment by ghost** [comment]
@Marsfan Both projects share important bug fixes with each other and the blocking core is the same, so they're equally effective blockers. The only difference is features and philosophy. Gorhill's version (uBlock Origin) is conservative and feature-complete, whereas chris is actively editing the GUI to make it cleaner and easier for beginners, and is open to hearing good feature suggestions.

In short: Both projects are practically the same. I'd pick Chris's version simply because it's getting nice improvements in user experience and he's a better UI designer in general. The only change that kinda sucked was the removal of the "per-site switches" which were used for blocking all popups on the current site, but perhaps they will be re-added someday if a nicer GUI location can be found for them. I am guessing they were taken out because they were a confusing eyesore at the bottom of the uBlock window and weren't used very often (since the regular blocking already takes care of most popup stuff).

**Comment by marsfan** [comment]
Thank you everyone for giving me some advice. I'm not sure if I can @ mention someone not it bUt here it goes  
@chrisaljoudi can you add some of the info from this to the reader for ublock?

**Comment by lewisje** [comment]
I prefer uBlock Origin because it's more featureful (like it still _has_ the per-site switches, and also domain-based strict blocking, which Chris took out for some reason).

**Comment by chrisaljoudi** [comment]
Closing (unless there's a reason to keep it open).

Discussion is still totally fine — just didn't want to have this as an "open issue".
