### ISSUE TITLE
Legacy Firefox toolbar icon is not displayed in pop-up status bars

### ISSUE THREAD

**Issue by PlasmaMiasma** [uBlock-LLC/uBlock#1377]
In addition to main windows, the legacy Firefox (in this case, Pale Moon) uBlock toolbar icon should also be displayed in pop-ups.

For example, the icon is not displayed in the pop-up opened by the "Listen Live" button at the top of [this page](http://www.jazzfm.com/).

**Comment by AlexVallat** [comment]
There's really not much we can do about this, Palemoon is not displaying _any_ toolbar buttons in the pop-up window. It won't even show any custom toolbars you've created, or any customization at all.

If you need to configure settings for a pop-up window like that then what I would suggest would be to open the request log (either through add-on settings, or through the button from any normal window), then use the drop-down to pick the "Jazz FM Radioplayer" tab. The button at the top right of the network log (looks like a bar chart) will then show the menu that would have appeared if you clicked the uBlock button.

**Comment by ghost** [comment]
@ParticleMon, as a work-around, you can go to `about:config` and set preference `dom.disable_window_open_feature.toolbar` to true to stop pop-ups from hiding your toolbar.

**Comment by PlasmaMiasma** [comment]
I had spoken in error and have updated the title accordingly: I didn't mean pop-up toolbar but pop-up _status bar_.

@AlexVallat, first, thanks for your work in adding legacy Firefox support. Other add-on icons display in pop-up status bars but uBlock's does not.

@one23, thanks for the about:config workaround. Even though I don't (typically) want toolbars in pop-ups, enabling that pref does add the uBlock icon to the status bar.

**Comment by PlasmaMiasma** [comment]
@AlexVallat, if verified, may this issue be reopened?

**Comment by AlexVallat** [comment]
@ParticleMon I've just checked, and as far as I can tell PaleMoon doesn't display customizations to the status bar in popup windows either. I tried adding a few buttons to the status bar (as well as uBlock), and none of them showed up in the popup.

If I'm mistaken, and the issue is actually uBlock specific, then this can be reopened. Otherwise, it seems to be the intended behaviour of PaleMoon - all customizations are removed from popup windows.

**Comment by PlasmaMiasma** [comment]
@AlexVallat My experience differs. I have four add-ons with status bar icons and each except uBlock displays in pop-ups, even with `dom.disable_window_open_feature.toolbar` disabled.

**Comment by AlexVallat** [comment]
Perhaps they are add-ons that modify the status bar directly, rather than providing a standard customizable button that can be placed on the status bar if desired? If they are modifying the status bar directly then it is their own responsibility to obey the PaleMoon settings and remove themselves from popup windows.

The intention from PaleMoon seems quite clear: unless `dom.disable_window_open_feature.toolbar` is set true, customisations to toolbars and the status bar should not apply to popups.
