### ISSUE TITLE
Request: Easier Exclusions and rules

### ISSUE THREAD

**Issue by rayman89** [uBlock-LLC/uBlock#1403]
Could you add the functionality to right click the list of blocked elements (chrome://ublock/content/devtools.html) on the page to add it to the exceptions/rules?

**Comment by unikitty37** [comment]
It would also be handy if activated element hiding rules showed up so that we could add those to the exceptions.

For example, on daringfireball.net, if you have an exception for the Deck network in your filters:

```
@@||decknetwork.net
```

the Deck ad is still hidden by a third-party filter injecting a `display: none !important` for `#SidebarTheDeck, .ad.super`.

Being able to spot this is happening without spending ages in Firebug would be helpful.

Being able to override this rule with a click would be even better, especially since I _still_ haven't found the correct syntax to use — I thought `#@##SidebarTheDeck^$important` would do it, but no joy…

Overriding existing rules is probably the one area where the Firefox version of Adblock Plus still wins over uBlock :)

**Comment by rayman89** [comment]
I agree with tinyclanger. Also now firefox fixed what caused adblock excessive memory consumption on firefox nightly which kinda eliminates ublock advantage over adblock
