### ISSUE TITLE
One uBlock - many cotributors

### ISSUE THREAD

**Issue by Piter432** [uBlock-LLC/uBlock#1405]
Currently there's two uBlock's - uBlock by Chris (Chromium-based browsers) and Alex (Firefox-based browsers) and uBlock Origin by original uBlock creator - @gorhill 

I think it's stupid that there are two uBlocks. I think should be one uBlock, but with many cotributors:
Chris - Head of uBlock (as for now), adding features
Alex - Head of uBlock for Firefox (fixes, UI, etc. as for now)
Gorhill - Fixing bugs of uBlock and head of uBlock's translation on Crowdin (as for now in uBlock Origin)

I've read on ublock.org that the uBlock Development Team will add features as opposed to gorhill's uBlock Origin. Funny, so why site-based switches was removed, hmm? This is "adding features" you called?

**Comment by 5t3f4n** [comment]
Merging back to a single uBlock would definitely benefit the users.
We wouldn't have to choose between feature-completion (uBlock Origin) and UI polish (uBlock).
But they split for a reason, and I don't think much has changed in that regard. Maybe some time in the future when the extension(s) are more mature and bug reports and feature requests are less frequent, they will consider merging again. But that day is probably not today.

Though I know one of gorhill's intents when forking was to not have to deal with the issues tracker, but he reversed his stance on that shortly after and now he's checking **two** issues trackers instead of one… So I think there's something to be won here for everyone.

One idea would be to have "janitors" put appropriate labels on all issues so the developers would know where to look. That way gorhill wouldn't have to waste precious time reading the umpteenth "site x is broken because of filter y" that could've been spent fixing actual bugs.

gorhill on Chromium & core, Chris on Safari & UX and Alex on Firefox & legacy?
Sounds like a dream team.

**Comment by chrisaljoudi** [comment]
I agree with most of what you're saying — that said, I've done everything within my control and have offered a reunite several times. I'm closing this issue, but feel free to keep discussing.

Also, @AlexVallat isn't maintaining his "own" uBlock — it is this uBlock. The fact that he has a fork of the repo doesn't mean it's a separate release.

**Comment by AlexVallat** [comment]
Just to confirm what Chris said, I am maintaining the main branch, uBlock, for Firefox. The fact that I have a fork of the repo is just an organizational thing, the way that github works. I may occasionally do work on that fork and produce test builds, but any changes will be either merged back to here or discarded, depending on the success of the testing!

**Comment by davidhedlund** [comment]
@AlexVallat Can you please mention this in your description for your repo?

**Comment by AlexVallat** [comment]
@davidhedlund Fair enough. Given the 300-odd other forks github reports I didn't think anything special was required, but I suppose that as my name is on the Firefox AMO listing it might be best to avoid confusion.

**Comment by chrisaljoudi** [comment]
@AlexVallat alternatively, feel free to just use a branch on this main repo — you can release test builds as you deem fit, too.

**Comment by AlexVallat** [comment]
Thanks @chrisaljoudi - in general I'll prefer to work on a branch on the main repo, but I don't see any good way of releasing test builds without them appearing as releases on the releases page. So I'll stick to using my fork for that, in the rare occasions it is required.

**Comment by chrisaljoudi** [comment]
@AlexVallat whatever you think is best!

On that note, can you please email me at `chris@chrismatic.io`? It'd help with some stuff we can discuss if that's okay.

Normally, I'd just ask for your address, but I figured you might feel uncomfortable posting it publicly on GitHub.

**Comment by AlexVallat** [comment]
@chrisaljoudi Sure. I've sent you an email, so if you don't receive it, check your spam traps or let me know and I'll try again.
