### ISSUE TITLE
Opera support?

### ISSUE THREAD

**Issue by nntoan** [uBlock-LLC/uBlock#1411]
Hello,

I'm wondering is there any release support Opera browser ?

**Comment by anewuser** [comment]
https://addons.opera.com/search/?query=ublock

**Comment by nntoan** [comment]
Yes, I knew that, but that is uBlock Origin

**Comment by lewisje** [comment]
The core code is very similar; in fact, chrisaljoudi regularly merges commits made by gorhill.

**Comment by nntoan** [comment]
@lewisje : Thanks for that information. I want chris uBlock because seem this addon seems very active and under highly maintained.

**Comment by lewisje** [comment]
I actually came under the impression that uO was better-maintained, but that was just my impression as of the middle of April, after switching from uO to uB and seeing how much further uO was progressing.

**Comment by mathiasbynens** [comment]
The [README](https://github.com/chrisaljoudi/uBlock#installation) says:

> Opera: Opera shares Chrome's underlying engine, so you can install uBlock simply by grabbing the latest release for Chrome.

Please consider uploading the extension to https://addons.opera.com/en/ so users can more easily install it. Thanks!

**Comment by shwetank** [comment]
It is possible to just submit the .crx file to the Opera addons store too (as long as all APIs requested in the extension are supported by Opera too). Since that seems to be the case here as well, It would be really great if you could just submit this extension to the Opera addons store. 

That way, Opera users would have a much easier time finding and using the extension.
