### ISSUE TITLE
Layout of https://advertiser.wildwallet.com/ is broken

### ISSUE THREAD

**Issue by trietbui85** [uBlock-LLC/uBlock#1413]
- Url: https://advertiser.wildwallet.com/
- uBlock version: 0.9.7.5
- Chrome 45.0.2414.0 dev-m
- Windows 7

**Comment by gjallarhorn** [comment]
This is because the URL matches the filter "/advertiser." and as uBlock got the feature "strict site blocking" removed, it just shows you a broken site with no other information.

I doubt there will be any change in the filter lists for this, so just [whitelist](https://github.com/chrisaljoudi/uBlock/wiki/How-to-whitelist-a-web-site) the page.

**Comment by ghost** [comment]
EasyList, `/advertiser.$domain=~advertiser.growmobile.com`.
Report here: https://forums.lanik.us/viewforum.php?f=64
