### ISSUE TITLE
"uBlock could not be installed because Firefox could not modify the needed file."

### ISSUE THREAD

**Issue by LifeWulf** [uBlock-LLC/uBlock#1416]
I was very confused when the button suddenly disappeared and ads started popping up again. Now I know why.

**Comment by AlexVallat** [comment]
This is a Firefox issue, rather than a uBlock one, so you might have better luck at http://support.mozilla.org . I can offer a few suggestions to try, though:
1. Restart your computer first.
2. Check if uBlock is listed in about:addons. If it is, remove it.
3. Try installing again. If it still won't, then
4. Try installing from the Releases page here rather than from addons.mozilla.org.

**Comment by LifeWulf** [comment]
You're right, it was a Firefox issue. My apologies. I tried other add-ons and the same issue occurred. Resetting Firefox helped, and now I have uBlock again.
