### ISSUE TITLE
Fanboy Lists break Capital One 360

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#142]
You can't submit your login on Capital One 360 if Fanboy+Easylist-Merged Ultimate List or Fanboy’s Enhanced Tracking List are enabled.

You get a JS error "urchinTracker is not defined" and it is the blocking of the urchin.js file.

Not sure if this is the appropriate place so please close if necessary.

**Comment by gorhill** [comment]
> Not sure if this is the appropriate place so please close if necessary.

Depends. If you can confirm the breakage still happen after unselecting _"Peter Lowe's Ad server"_ list, than the breakage should be reported to Fanboy: http://forums.lanik.us/viewforum.php?f=64

Otherwise, if the breakage occurs because of one of hosts-based filter, I will create an exception. But we the **exact reason** of the breakage so that we can create the most narrow filter to fix it. Since I don't have a Capital One account and don't plan to apply for one, I will have to rely on volunteers on figure this one out (if ever the problem is really not Fanboy).

Though ultimately, for bank sites I tend to favor whitelisting.

**Comment by ghost** [comment]
I'll test further later, but you don't need an account. Just observe
that the submit button becomes worthless when that tracker is blocked,
as in it doesn't submit to login or complain the ID isn't valid.

**Comment by ghost** [comment]
I can confirm that disabling everything but those 2 still causes the issue, and leaving either one enabled (as in 1 of them being the only enabled list) still breaks it.

So I'd say it is the Fanboy Lists.

PS: I've been whitelisting it as such:
@@||stats.capitalone360.com/urchin.js$domain=secure.capitalone360.com,script

Only enables that specific file on that specific domain.

**Comment by gorhill** [comment]
So I will let you report to Fanboy (can post as Guess, no need to create an account): http://forums.lanik.us/viewforum.php?f=64
