### ISSUE TITLE
Toolbar button gets disabled when using a single tab with TabMixPlus

### ISSUE THREAD

**Issue by M1dknyte** [uBlock-LLC/uBlock#1425]
When "Display - Hide the tab bar: When I have only one tab" is chosen in TabMixPlus (TMP) options and there is only one tab open, I click on the uBlock toolbar button and then open the dashboard.
After that, the ublock toolbar button stays grayed out. To get it "unstuck", I have to either restart Firefox or disable/re-enable uBlock from Addons.

It works fine if I choose "Display - Hide the tab bar: Never".  It also works if I have multiple tabs open first.

I'm using uBlock 0.9.5.0 and TMP0.4.1.7.1-signed. This problem has occurred with all previous versions of uBlock. I've also tried the latest Dev version of TMP.

This is the only addon I have with this problem. I'm hoping it's a simple fix. Thanks for your time.

**Comment by Gitoffthelawn** [comment]
I've noticed an issue that could possibly be related: sometimes on a new (empty) tab, uBlock will temporarily report that it is disabled (via the toolbar button).  It then re-enables itself after a few moments.  This seems to happen more often if the new (empty) tab is the only tab (other tabs get closed).  I haven't filed an issue because I haven't isolated it yet.

You can add the following style to make the issue easier to detect:
/\* uBlock Origin extension button: enhance visibility when disabled by applying background color _/
#ublock0-button[style=""]  { background-color: red !important; }
/_ uBlock extension button: enhance visibility when disabled by applying background color */
#ublock-button[style=""]  { background-color: red !important; }

Note that for the last line of CSS, I guessed the id, because I am testing uBlock Origin at the moment and don't have regular uBlock installed; you may need to adjust the id if I guessed wrong.

Tested on uBlock Origin 0.9.8.2 - Firefox 38.0.1 - Win7 SP1

**Comment by M1dknyte** [comment]
Do you mean in the userchrome.css? I tried it with ublock. I also installed ublock origin and disabled ublock. Unfortunately, that didn't seem to keep the button "unstuck". Thanks for the info. I'll keep tinkering.

BTW, I tried it with FF31.7.0ESR and 38.0.1ESR. I removed my userchrome.css too, just to see if any of my mods affected the button.

If you change  "Display - Hide the tab bar: When I have only one tab" to "Never", that instantly fixes the issue. But I'd prefer to hide the tab bar to maximize space.

**Comment by Gitoffthelawn** [comment]
@M1dknyte Correct, you can add it to userchrome.css or you can directly modify the uBlock xpi.

If you add it to userchrome.css, make sure to include the following line at the top of that file:
@namespace url(http://www.mozilla.org/keymaster/gatekeeper/there.is.only.xul);

Yes, there is a Ghostbusters joke in there, and yes, it's required!   :-)

**Comment by Gitoffthelawn** [comment]
@M1dknyte After re-reading your post, I think you might have been under the impressionism that the CSS code will prevent the issue.  It won't; it only makes it easier to notice when uBlock is disabled.

**Comment by M1dknyte** [comment]
Ahhh ok. Gotcha. It's pretty easy to see when the button gets "stuck". It stays gray like when you've clicked on it. When you try to click on it again, nothing happens. I can still go into "Tools-Options, uBlock-Options, Show Dashboard" after the button gets stuck, though.

Yup. I had the Ghostbusters line in there already. Love that movie. Thanks! :)

**Comment by AlexVallat** [comment]
I can reproduce this. It is, however, a TabMixPlus bug and not a uBlock bug - please report it to them.

Some repro steps that work with only TabMixPlus installed:
- Set TabMixPlus to "Display - Hide the tab bar: When I have only one tab"
- Use Customize to put the Firefox History button on the toolbar
- Close all but one tab so that the tab bar is hidden
- Click the History button, then Middle-Click (or Ctrl+Click) one of the history entries to open it in a new tab

Observe that the History button is now stuck.

**Comment by M1dknyte** [comment]
Oh! Thanks for taking the time to look into it. I'll see if I can post it to the TMP support forum. Thanks again!

**Comment by M1dknyte** [comment]
Well, I tried what you said and the History button does look "stuck" until I close the History sidebar (click on History button again). After that, the button returns to normal.

It's a little different from the ublock icon, where it becomes unclickable (like it is locked in the pressed state). Just thought I would let you know. Thanks.

**Comment by AlexVallat** [comment]
I think we're referring to different history buttons. I'm talking about the one that looks like a clock, that when you click on it shows a drop-down. The sidebar isn't used at all.

**Comment by M1dknyte** [comment]
Ok, I see it. There are two history buttons. I tried the one with the drop down menu just now.

One tab open, click on the History drop down menu, and open one of the links. The History button returns to normal.

The only other addon I have right now is Classic Theme Restorer. I removed everything else.

I'm also looking on the TMP forum to see if there is a similar issue.

It's just really strange that having two or more tabs open allows the ublock button to return to normal. Thanks.

**Comment by AlexVallat** [comment]
Open the link in a new tab (Ctrl+click or middle click)

**Comment by M1dknyte** [comment]
The history automatically opens in a new tab for me. Middle click will delete the history entry.

I managed to find a workaround. I set extensions.ublock.forceLegacyToolbarButton to true in about:config and it seems to work. I'm fine with that. Maybe you can add a checkbox to enable that option in the ublock dashboard?

Thanks for your help! Keep up the good work!
