### ISSUE TITLE
show and disable blocking of services

### ISSUE THREAD

**Issue by davidak** [uBlock-LLC/uBlock#1429]
coming from Ghostery i miss the feature to see what spying servies a site uses. also the ability to allow just one of them.

![bildschirmfoto 2015-06-03 um 16 54 06](https://cloud.githubusercontent.com/assets/91113/7963763/9d7fa010-0a14-11e5-8185-3e01a4c09713.png)

**Comment by Snapy** [comment]
Enable "Advanced user mode" and expand the view.

**Comment by davidak** [comment]
Okay, but i don't see that the Request comes from Piwik. I want to allow Piwik for all sites because it respects the users privacy.

![ds](https://cloud.githubusercontent.com/assets/91113/7964216/e435dfa4-0a16-11e5-9064-e25731f8a5ca.png)

the interface of ghostery is more user friendly.

**Comment by Snapy** [comment]
Click the first line with the "+" to have more details about the connected domains.
You don't see the requests from Piwik because it is hosted by the website itself so there is no domain directly linked to it (look in the logger).
Piwik is blocked by EasyPrivacy so you can either disable that list or search for its occurrences in it and create an exception for each one. You have one other option : use dynamic URL filtering in uBlock Origin.
