### ISSUE TITLE
Whitelisted element may not display as intended

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#143]
I've noticed that if I whitelist an element, it gets a display: initial !important.

This might not work out if that element is using a different display.

For example on 53.com there is a div#ad-rotator. If I whitelist this, it ceases to be a block element and messes up the layout.

**Comment by gorhill** [comment]
I see.. So the fix is really to have the whitelisted selectors removed from the set of blocked ones, rather than try to re-enable them, as I can't restore for sure their computed `display` values.

**Comment by ghost** [comment]
That makes sense. I figured trying to compute the original CSS value
would be no small feat, but removing any block rules on page load that
would conflict with the whitelist could work.

**Comment by gorhill** [comment]
Ok, I have a fix.

However, your specific filter would still not work, because I originally made the choice to not support generic exceptions for cosmetic filters: there is no such filters in _EasyList_ or _EasyPrivacy_. These are rather rare occurrences: for all the lists which ship with uBlock, there are only 8 occurrences of such filters.

Workaround for your specific case is to use: `53.com#@##ad-rotator`. Domain- or entity-scoped cosmetic filters are the preferred way for cosmetic filters: Their look-up is more performant, and they can be injected very early in the page.

If I were to enable support, this would add some overhead to the cosmetic filter look-up code, and I rather not introduce a systematic overhead in order to support such rare occurrences.

**Comment by ghost** [comment]
I am actually using that filter as is already, it just doesn't make it a
block element.

I used Stylish for Chrome to force it to be a display: block for now.
