### ISSUE TITLE
Temporarily disable for all sites

### ISSUE THREAD

**Issue by majax79** [uBlock-LLC/uBlock#1432]
I'm hoping for the ability to temporarily disable ublock origin everywhere by left or right clicking the icon. Currently, I have to go into chrome addon and manually disable ublock origin, but this way would make it a lot easier.
This feature is in adblock and adblock plus. It's called "Pause AdBlock" and "Disable Everywhere". I find it really useful.

**Comment by Gitoffthelawn** [comment]
+1

I asked for this over on the uBlock Origin repo and was denied.  Hopefully it will be implemented here.

**Comment by 5t3f4n** [comment]
This sounds like a terrible idea. One might disable it temporarily to unbreak a particularly annoying site that just won't work and then, without realizing, open something else in an a new tab and getting exposed to god knows what by accident.

The extension is "restartless" so you can just disable/enable it quickly if you desperately need to "pause" it.

**Comment by chrisaljoudi** [comment]
A similar control is slated to be included in the [upcoming new UI](https://github.com/chrisaljoudi/uBlock/milestones). 

@majax79 to avoid confusion, I just wanted to point out this isn't uBlock Origin — and @Gitoffthelawn  says this feature request was already denied there. 

[The main uBlock](https://www.ublock.org/) is indeed getting this next version, but I can't say about uBlock Origin.

**Comment by chrisaljoudi** [comment]
@5t3f4n all good points, and this is s consideration which the redesign pays a lot of attention to.

Will certainly continue to keep it in mind.

**Comment by 5t3f4n** [comment]
Glad to hear that @chrisaljoudi. If it can be implemented in such a way that it eliminates, or at least minimizes risk of, accidental exposure then I guess everybody wins.

**Comment by Snapy** [comment]
Gorhill denied the request because he considers that a temporary `* * * allow` is the same so it is already supported in some way.

**Comment by chrisaljoudi** [comment]
@Snapy except that's only available to advanced users (and is arguably a lot more obscure).

**Comment by Gitoffthelawn** [comment]
@snapy Not only is it more obscure, it no longer works as a 'disable' feature due to strict blocking.  Sites will still be blocked at the top level.

**Comment by ArtificialTruth** [comment]
This would make a tremendous difference.  It's very inconvenient to make custom filters on tons of websites if you just want to temporarily pause Ublock. It's also very inconvenient to have a extra tab open just for the purpose of pausing Ublock. Adblock has had this feature for years (day one probably) and it's the only thing holding me back from fully switching.  
Please make Ublock even better by reconsidering this idea! :)

**Comment by gartkb** [comment]
Sometimes one really does need a temporary disable, rather than a "unblock this site" feature.  This comes up, for example, when trying to use sites like ebates.com, or topcashback.  It can also come into effect when some redirects are happening. I'm really tired of the attitude that some users know better than other users how something should be used.
It's a huge pain in the rear to use the chrome disable or incognito mode which is what I use now.

If trying to force users to a particular behaviour pattern is the goal, then keep the big "unblock site" icon and add a tiny one that says "I am not a moron, I need this feature."

thanks for consideration.

By the way, I will never, ever use ublock origin because of gorhill's attitude in that linked issue.  This is not "replicating a browser feature".   Being dismissive and totalitarian is his right, I suppose, but I don't have to like it.

**Comment by ghost** [comment]
Man, I'd love to see this, I enter sweepstakes for a living and when I enter them i have to disable for SO many sites to see the gleam.io widgets!

**Comment by Gitoffthelawn** [comment]
@Zibokwe Do you really enter sweepstakes for a living?  I have to ask: How much do you make doing that?

**Comment by ghost** [comment]
@Gitoffthelawn Anywhere between $30k-$100k a year, using all available resources, keeping tabs on the best daily/weekly/multiple enter sweeps, entering anything of value in all available methods they offer... It's easy to live off of if you got the time, and since cost of living is low here just have to set aside about $100k for 7~ years of rent/food/etc.

**Comment by Gitoffthelawn** [comment]
@Zibokwe Thank you for the details.  I would have never imagined it was possible to generate that type of return.  Well done!

**Comment by tbrodbeck** [comment]
Since this has not yet been implemented, I think it is fair to add a comment to an old thread.

Why this is an important feature? Sometimes you have some websites where you are redirected many, many times. And you cannot access that website because a fraction of it is blocked. So the only way to be able to quickly access the website without researching which redirect was blocked this feature would be exceptional.

**Comment by ibushong** [comment]
I would also like this feature. My use case is that I am making a purchase that gives me a reward via some promo extension, like Honey. So the tracking/attribution pipeline that the site uses needs to operate correctly. Otherwise, I won't receive the award. This has already happened to me once, where I disabled uBlock for the site, but my purchase was not verified/confirmed by Honey, which I can only assume is due to certain tracking scripts being blocked.

In fact, the Honey extension sometimes notifies you of this. Their suggested fix is to install an extremely generic whitelist, which unblocks tons of common trackers. Obviously this is not a great solution.

It would be much more convenient to be able to just temporarily disable all blocking, do the transaction, and then re-enable. The feature could even include a timeout, like "Disable uBlock for X minutes".

My temporary workaround for now is just to disallow the extension in private browsing mode and then do my purchase there. But this opens the possibility that I forget to re-allow the extension.

**Comment by Gitoffthelawn** [comment]
@ibushong I agree with everything you wrote.  Please note you've posted your comments in the uBlock issue reporter.  If you happen to be using the more popular uBlock Origin, the correct repo is https://github.com/gorhill/uBlock

**Comment by ibushong** [comment]
Oops! My mistake. Sorry about that. I'll check out that repo

**Comment by Gitoffthelawn** [comment]
> Oops! My mistake. Sorry about that. I'll check out that repo

@ibushong  No problem.  I just had a hunch you might have posted in the wrong repo by accident. :)

BTW, I don't have any affiliation with this repo... I just happened to receive your note because I commented on this issue 4+ years ago!
