### ISSUE TITLE
What do YOU want out of uBlock?

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1433]
Since this issue tracker gets a fair amount of traffic, I figure this might be a good place to post this, at least temporarily.  Chris, if you disagree, I won't be offended at all if you close it ( okay, maybe a little bit :-)  ).

What do YOU (the reader) want out of uBlock?

I'll answer that question first:
I currently use uBlock Origin, not uBlock.  Why?  Because at the moment I made the decision, uBlock Origin had updates and functionality that uBlock did not.  That was a while ago, and things change quickly.

In order to switch to uBlock from uBlock Origin, what I want is to know is that uBlock has all the important functionality of uBlock Origin, and all the bugfixes.  If any uBlock Origin functionality is completely removed, I want it to be itemized with an explanation of why it was removed.  I would like such a document to be kept current as gorhill constantly improves uBlock Origin.  I don't feel entitled to any of this in any way, or that anyone has to do it.  It's just what I want.  I'm willing to help with this task, as time permits.

Differences in UI will not hold me back from using uBlock, since if I start using regular uBlock, I will likely expand the [uBlock-Deluxe enhanced UI overlay](https://github.com/Gitoffthelawn/uBlock-Deluxe) to include regular uBlock.  Chris also seems very interested in working on the uBlock UI, while gorhill is more limiting his focus on the engine (which I understand and respect).  As such, I expect the uBlock UI, with or without the uBlock-Deluxe overlay, eventually to be superior to uBlock Origin.

**Comment by CrisBRM** [comment]
I want Chris to stop fucking with the wiki (trying to erase gorhill from the history of uBlock), pretending he knows how to program by copying gorhill's code and stripping his name from the commits, taking credit for Deathamns Safari port and, most importantly, victimising himself (eg: claiming you have no money, when you offered gorhill a large sum of money to port uBlock to Safari, amongst MANY other things, and then acting like you meant no harm).

It's pathetic and quite obvious he wants to use uBlock to pad his resume in the future.

**Comment by bateller** [comment]
I don't know about the truth behind @CrisBRM's claims (not saying he's lying... just not taking a position one way or another)... however I think another way to approach the question is to ask what does uBlock hope to deliver to users? What was the reason behind forking uBlock Origin? The FAQ page tries to elude the reason was because uBlock Origin's development was stagnant. This obviously isn't the case if you look at @gorhill's commits and responses to issues (which seems to actually be MORE active than uBlock's).

If there is truth to @CrisBRM's claims and the real reason for the repository is to pad a resume then there isn't any need to further develop this project. If there is a true goal though, to build this beyond what is capable with uBlock Origin then I can understand (hell I'll even contribute). But you don't build a project for the sake of it, then hastily try to figure out the goal/mission after the fact.

**Comment by 0xBRM** [comment]
@bateller 
Of course Chris would delete my comment. Here's an example of what he did:

![1434123801554](https://cloud.githubusercontent.com/assets/9098352/8137385/f5246c24-113a-11e5-8653-4e2445d6fd1f.png)

Check gorhill's readme for more information: https://github.com/gorhill/uBlock/commit/daef0bd8c8b45d8c9c734d51a930367c511fa881

> +Somewhere toward the end of May, I decided I will not contribute code anymore to this [uBlock branch](https://github.com/chrisaljoudi/uBlock).<sup>[2]</sup>
> +
> +<sub>[1] [An example](https://www.ublock.org/faq/). [Another one](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/reviews/716364/).<br></sub><sub>[2] Reasons: [this](https://en.wikipedia.org/w/index.php?title=UBlock&type=revision&diff=662527440&oldid=662107368) vs. [this](https://github.com/chrisaljoudi/uBlock/commits/master?author=gorhill), and [this](https://www.reddit.com/r/ublock/comments/38lf1y/any_difference_between_ublock_and_ublock_origin/crwhmwt).</sub>

**Comment by Betsy25** [comment]
I think it's already perfectly clear for people, if you want to see more than a commit from Alex every couple of weeks, and nothing at all from the main "developer", uBlock Origin is definitely the way to go. Only wished gorhill work consider implementing some of Alex's pull requests.

**Comment by chrisaljoudi** [comment]
@CrisBRM your comment was deleted because it was a personal attack. 

This is not the place to discuss the Wikipedia edit, but it was perfectly valid since uBlock Origin != uBlock and the article is about uBlock. 

I don't feel the need to justify the frequency of commits (all of the work has been on a complete rework of the UI and it's local since pushing it partially would break the UI off the HEAD). 

I will no longer allow political discussions that include personal attacks or criticisms on GitHub.

Yes, comments including personal attacks will be deleted.

**Comment by Gitoffthelawn** [comment]
@chrisaljoudi It is unfortunate that certain people act like that.  CrisBRM has been in at least one other github repo spreading rumors about that project.  Quite a number of his posts are not nice or productive.

I think this issue tracker item is still useful.  Can you delete all the items except for the initial post, as they are all OT?

**Comment by PlasmaMiasma** [comment]
@Gitoffthelawn I second your preference of add-on and your reasoning. I'll put it this way: I would like to see the relationship of uBlock Origin to uBlock as Chromium is to Chrome, not in the testing sense but in the code-base sense.

And because my browser of choice is Pale Moon, I'm grateful that uBlock supports legacy Firefox (and disappointed that uBlock Origin [and uMatrix] does not), and am therefore more inclined, at least for now, to lend my support to uBlock.

So, until then, I will continue using uBlock in my primary browser, Pale Moon, and uBlock Origin (and uMatrix) in my secondary browsers, Firefox and Chromium, at least until uBlock starts committing the updates made to uBlock Origin.

Edit: Since uBlock Origin (and uMatrix) now support legacy Firefox, and thus Pale Moon, I now use those add-ons in all browsers, looking forward to what might become of uBlock.
