### ISSUE TITLE
The 'Parse and enforce cosmetic filters' option applies more globally than is intuitive

### ISSUE THREAD

**Issue by Gitoffthelawn** [uBlock-LLC/uBlock#1445]
The 'Parse and enforce cosmetic filters' option on the 'Third-party filters' tab also applies to 'My filters'.  It probably should be renamed and not apply to user-created filters, or even better, there should be separate options for each.

**Comment by lewisje** [comment]
I thought it was quite intuitive: If it's on, hiding filters work; if it's off, they don't.

**Comment by Gitoffthelawn** [comment]
Correct, except that clicking an option on one tab disables many items on another tab.  There is no indication (or option) on the 'My filters' tab indicating that many of the filters will be ignored (if the option in the other tab is unchecked).

**Comment by lewisje** [comment]
"My Filters" is exposed on the 3rd-party filters tab as a subscription called "My Filters" (actually the first subscription in the list); again, I fail to see how this is unintuitive.

**Comment by Gitoffthelawn** [comment]
"I fail to see how this is unintuitive."  What is your education and experience in the cognitive sciences or human factors engineering?

**Comment by lewisje** [comment]
None: I just saw the text label and immediately knew what it meant; the only potentially confusing part was "cosmetic filters" and that's only because it's the uBlock term for hiding rules.

Seriously, the _unintuitive_ thing would be for that checkbox to _only_ apply to subscriptions and not to custom filters.

**Comment by Gitoffthelawn** [comment]
Oh dear.  You have no education or experience.  People go to universities and get degrees and then work for years in the field to try to master the cognitive sciences and human factors engineering, but you hope your "off the cuff" analysis is spot-on.

Without trying to be offensive, I think you are very much overvaluing your opinion.  Nobody wants a random untrained person repairing airplanes or performing surgery; similarly, nobody wants a random untrained person designing interfaces.  It's a complex science.  When untrained people try making "off the cuff" analyses, they are wrong a majority of the time.  Unfortunately, by the time their mistakes are noticed, much has been built on top of all the errors.  Tearing away the layers of dysfunctional design and rebuilding a system that works for the end users winds up representing a substantial task.

**Comment by lewisje** [comment]
However, when it comes to what a typical untrained user would deduce from a UI, typical untrained users provide useful input.

BTW, to clarify, I _did_ go to college, just not for cognitive science or UX; I have, however, read many of the articles on Jakob Nielsen's site, and you were being offensive as soon as you brought rank credentialism into this issue.

Finally, requiring _two separate options_ to toggle cosmetic filters for subscriptions and custom filters sure sounds like "dysfunctional design" to me, unless there were also a master toggle that affects both in tandem, to ease the user experience. Actually, that sounds like a good idea: one master toggle in the first tab, one toggle in the subscriptions tab, and one toggle in custom filters.

**Comment by Gitoffthelawn** [comment]
Ugh.  It's not about "rank credentialism", it's about the futility of trying to explain methodology and details to someone who does not have the education to understand.  The reason you feel offended is perhaps because you don't want to acknowledge you don't know everything.  No one knows everything; some people are just more willing to acknowledge it.  I wouldn't expect an orthopaedic surgeon to spend her/his time explaining to me why I feel that their idea of using surgical steel pins is a bad idea, and why my idea of using wooden surgery pins is a great one.  I certainly wouldn't relentlessly reply to his posts telling him that surgical steel is a bad idea because I think wood is better (that's how your posts sound).

Your statement that "when it comes to what a typical untrained user would deduce from a UI, typical untrained users provide useful input" is often true, but what you fail to see is that your "study" has an n of 1, and thus is close to meaningless.  Furthermore, that is not close to how we actually determine what a user "deduces".  You haven't even tried to control for a number of biases or taken into account a multitude of other factors.

Studying unrelated fields in college or reading a few articles by Jakob hardly constitute an appropriate education.  By that standard, NASA should ask millions of us to design spacecraft, as we are certainly qualified.  Those who carefully read "The Physics of Star Trek" should definitely be placed on the top of their list, and NASA should listen closely to their recommendations.

**Comment by lewisje** [comment]
That post certainly [sounds extreme](http://rationalwiki.org/wiki/Straw_man): You're literally putting "one toggle instead of two" [in league with obviously stupid ideas](http://rationalwiki.org/wiki/Extended_analogy).

For a more down-to-earth analogy, your recommendation sounds like the opposite of something that Alex Limi (UX lead for Firefox) [recommended and got implemented](http://limi.net/checkboxes-that-kill) (albeit in this case, there's still a hidden pref that does what that "checkbox that kills" did).

I am also not sure why someone who has not gotten a degree and several years of experience in UX [must therefore have nothing of value to say about it](http://rationalwiki.org/wiki/Courtier%27s_Reply).

**Comment by Gitoffthelawn** [comment]
Okay, your ideas are very, very meaningful, Lewis.  Without any idea what you are talking about, any actual experience, or even the vocabulary necessary to effectively discuss it, you come to great conclusions and understandings.  We all agree, so time to move on.  Will you stop posting now, and let us foolish people continue with our pathetic and useless mutterings?

**Comment by lewisje** [comment]
I'm sure [_you're_ the one](http://rationalwiki.org/wiki/Psychological_projection) treating others as simpletons who know not what they say (specifically, because they did not specialize in your area and _dared_ to have an observation regarding it).

Stop insulting me, and wait for one of your fellow collaborators to weigh in; if I were you I would have locked the issue a couple flames ago, and that's even a great way to get the last pompous word in! :+1:

**Comment by Gitoffthelawn** [comment]
You just won't quit trolling, huh?  Go away.  I'm not going to close an issue because you won't stop trolling.

**Comment by lewisje** [comment]
I actually left GitHub issues for almost two weeks because of how heated this discussion got, but I should say that I wasn't trolling: Lack of deference to the unexplained conclusions of experts does not constitute trolling.

I _did_ end up flaming, though, which is a natural reaction to getting more insulted and mischaracterized with every post.

I was actually reminded of [an exchange on the AdBlock support forum](http://support.getadblock.com/discussions/problems/73821-cant-block-a-dataimagepngbase64-encoded-and-added-images) that led me to abandon that forum for a while too (three months and counting), and it wasn't until I looked the two of you up more thoroughly that I learned you _weren't_ the same blowhard as he is.

---

Anyway, I didn't say this clearly earlier, but I understand that one really unintuitive thing about placing a global toggle for cosmetic filters in the "3rd-party filters" tab is that that's not where you'd expect to find it (the "Settings" tab, where the other general settings live), even though when you _do_ find it, its wording still makes it look like a global toggle.

Instead, I said it less clearly at the end of my fourth post in this issue:

> Actually, that sounds like a good idea: one master toggle in the first tab, one toggle in the subscriptions tab, and one toggle in custom filters.

**Comment by Zoooook** [comment]
Wow, I had the misfortune to stumble across this thread. Has anybody called out the argument from authority yet? This is pulled straight from the "Where did you matriculate?" quote from Reefer Madness, it looks like a re-enactment.

"I fail to see how this is unintuitive." -- This is where an honest debater with an actual argument would explain why it is unintuitive, instead of resorting to insulting condescension. Typically people who respond with fallacies instead of arguments are the ones "very much overvaluing" their opinion. Just wow.
