### ISSUE TITLE
could not support certain ABP rules

### ISSUE THREAD

**Issue by ivysrono** [uBlock-LLC/uBlock#145]
e.g.
~dsjunshi.com##div[id^="ad_thread"]

**Comment by gorhill** [comment]
Need to support "negative" domains for element hiding rules, currently not supported.

No such rules in _EasyList_ _EasyPrivacy_, however many in Fanboy's lists.

If I understand correctly, `~dsjunshi.com##div[id^="ad_thread"]` is equivalent to `dsjunshi.com#@#div[id^="ad_thread"]`. If so, then fixing this is trivial. I wonder why exception filters were not used rather than having yet another syntax for the same result.

Correction: it is actually equivalent to two rules: `dsjunshi.com#@#div[id^="ad_thread"]` and `##div[id^="ad_thread"]`.

**Comment by ivysrono** [comment]
This rule come from EasylistChina.

**Comment by gorhill** [comment]
Will take the opportunity to do some re-factoring.
