### ISSUE TITLE
hide-tab-bar-with-one-tab add-on incompatibility problem

### ISSUE THREAD

**Issue by HybridDog** [uBlock-LLC/uBlock#1468]
https://addons.mozilla.org/en-US/firefox/addon/hide-tab-bar-with-one-tab/
l use this add-on to see more of the page when l use only one tab.
But when the tabs are hidden and l click on the ublock filter list button, the ublock button in the toolbar is pressed and doesn't become released again, it's stuck there.
There's a small (241 KB) video showing how my top right corner looks like: https://d.maxfile.ro/vfbfvcarhs.mkv
![2015-06-23-201244_1280x1024_scrot](https://cloud.githubusercontent.com/assets/3192173/8313641/6c09cddc-19e4-11e5-9d71-f5f84133178d.png)
l need to restart firefox that l can click on the ublock toolbar button again.

**Comment by AlexVallat** [comment]
Sounds like #1425 to me. Try the steps in https://github.com/chrisaljoudi/uBlock/issues/1425#issuecomment-107838095 and see if you can reproduce it using a standard firefox button

**Comment by M1dknyte** [comment]
Yup. Sounds like the same problem I had with TabMixPlus. Instead of restarting FF, you can also disable/enable the uBlock extension.

Try using the "Legacy" uBlock button instead:
1. Open Firefox
2. Type about:config in the address bar, press enter
3. In the Search bar, type forceLegacyToolbarButton
4. Double-click extensions.ublock.forceLegacyToolbarButton to set value true

You'll have to remove and add the button back to the navigation bar from Customize.

**Comment by HybridDog** [comment]
thanks, readding the button worked after restarting firefox
