### ISSUE TITLE
console spam

### ISSUE THREAD

**Issue by skylize** [uBlock-LLC/uBlock#1471]
Using this extension causes Chrome to spam the developer console with 

`GET https://some-really-long-url  net::ERR_BLOCKED_BY_CLIENT`. 

It would be nice if you could capture and suppress these errors. Thanks.

**Comment by lewisje** [comment]
I think that's what filtering console messages is for; anyway, I remember when gorhill tried to suppress those messages the best way he knew how, and that ended up conflicting with HTTPS Everywhere so he backed out that change: #18

**Comment by skylize** [comment]
I disagree. Console filtering should not be considered a fix for anything, it's for workflow convenience. Thanks for pointing that out, as I can use this ugly bit of regex as temporary workaround:
`^(?!.*?ERR_BLOCKED_BY_CLIENT)`

But that regex has to be manually entered every single time DevTools is opened in a new window. The errors still show up in the error count at the top of DevTools with a bright red X symbol. The top line of the console must report that errors are filtered out. And I only get one regex field. If I want to filter anything else, I now have to merge it into this already complicated string, or expose these errors again.

The basic concept with error handling is you want errors to bubble up to avoid hiding something broken underneath. In this case the error is simply confirmation that uBlock did it's job. The only thing broken is uBlock failed to capture the error and respond by suppressing it.

**Comment by augnustin** [comment]
:+1: 
Yes yes yes!
I agree with @skylize. I'm considering going back to ABP because of those errors: when I'm trying to debug my own errors, I don't want other error to interfere with mines.

**Comment by lewisje** [comment]
IIRC ABP does the same thing uBlock does with blocked requests (cancelling rather than redirection), so you'll get the same flood of errors; meanwhile, AdBlock redirects a few requests last time I checked (images to a transparent 1x1px PNG, documents to about:blank), so if you want to minimize spam in the console, that's the extension you should choose.

**Comment by skylize** [comment]
I was going to try to build up a proof of concept for this, but when I tried to make changes to the code, Chrome blocked the extension as corrupted.

Looking at this from Chrome, don't know how well it would carry to other browsers:

Blocking a request fires  `onErrorOccured` event. I'm speculating here, but I would think you could register a listener to verify it was the expected error, then `preventDefault()` and/or `stopPropagation()` on the event.

**Comment by augnustin** [comment]
I did try to switch (using [Extensify](https://chrome.google.com/webstore/detail/extensity/jjmflmamggggndanpgfnpelongoepncg)) and I haven't had any `ERR_BLOCKED_BY_CLIENT` error since.

**Comment by skylize** [comment]
@gorhill Has anyone looked at this [suggested fix](https://github.com/andre-hub/uBlock/commit/4650b8778ad2bb0ea946a6d65ea8611bdceeae8b) to reduce console spam?

**Comment by lewisje** [comment]
The fix was made by @gorhill himself; its current incarnation is here, refactored slightly from when he first made the fix: https://github.com/gorhill/uBlock/blob/9208f8d56e324ca1f1e0132a06926daca958f650/src/js/tab.js#L635

As you ought to be aware, this version of uBlock has not been developed for a long time, and it's practically dead; switch to uBlock Origin at https://github.com/gorhill/uBlock

(unless you use Safari, then hope someone takes the trouble to port uBO to Safari and _doesn't_ mismanage it the way Chris did)

**Comment by skylize** [comment]
Thanks
