### ISSUE TITLE
Domains Connected and Request blocked??

### ISSUE THREAD

**Issue by tsunami2311** [uBlock-LLC/uBlock#1472]
So both this + show the same exact thing or am i missing something?

I would think Request Blocked would show all the ads being blocked and Domains connected would show domains connected, but the both show the same thing.

**Comment by RoxKilly** [comment]
When the browser fetches a page, say <code>homepage.html</code>,  the page contains links to other resources that the browser needs to render the page. for example images, javascript files etc...  Each of these links will cause the  browser to make one request, unless a uBlock rules blocks the request or the browser uses a local cached copy of the file needed.

Several links could be on the same domain. so if a page at <code>example.com</code> needs two images at <code>example.com/img_1.jpg</code> and <code>example.com/img_2.jpg</code>, those requests are on the same domain.  The browser will connect to the domain to make those two requests.  Broadly stated, the domain corresponds to the host name in the URL. A domain is considered connected if the browser made one or more requests to that domain.

So "Domains connected" and "Requests blocked" are different. There are more requests than domains because each request has its domain, and many requests can have the same domain.  The higher the number of "domains connected" the more exposed is your privacy. On the other hand, the higher the number of "requests blocked" the less exposed is your privacy. The attached log (taken from uBlock origin 0.9.9.1), from a visit to <code>grc.com</code> shows many requests (one per line), but only a few domains (grc.com, grctech.com and github.com). 
![1](https://cloud.githubusercontent.com/assets/12346501/8351070/7ec7e304-1af8-11e5-92c5-2af66663f919.png)
