### ISSUE TITLE
Peter Lowe’s Ad server list‎ should be disabled by default

### ISSUE THREAD

**Issue by moray33** [uBlock-LLC/uBlock#1479]
When I installed uBlock I started to have issues in some websites. After testing a little, I found out it was because the Peter Lowe’s Ad server list‎.
Some websites doesn't show correctly, like statcounter.com , or playing videos from atresplayer.com

I think this list should be disabled by default because this could be a problem for some not 'advanced' users.

**Comment by lewisje** [comment]
uBlock Unbreak actually does counter the blocking of statcounter.com in Peter Lowe's list (and also adf.ly, which I had noticed earlier).

**Comment by Gitoffthelawn** [comment]
In regards to the OP, as @lewisje mentioned, the uBlock Unbreak list contains one kind of fix (with the consequence that the site you mentioned may be allowed when you don't want it to be allowed).  Did you have that list turned off?  Was it outdated due to uBlock not updating it frequently enough?  Did it just not work?

In general, I find the uBlock Unbreak list to be much too broad to be useful.  It unblocks more than I want unblocked.

The need for a list to fix another list is indicative of how difficult it must be for people to create these lists.

**Comment by lewisje** [comment]
What I actually did was uncheck the built-in subscription and add a custom subscription like this: `http://pgl.yoyo.org/as/serverlist.php?hostformat=adblockplus&showintro=0&mimetype=plaintext&skip[]=adf.ly‎`

You can add as many hosts to skip as you like, all with the same pattern: `&skip[]=<hostname>`

Peter Lowe's list is rare in allowing hosts to be skipped (its example uses the alternative pattern of separating query-string parameters with a semicolon): http://pgl.yoyo.org/as/formats.php#skip

**Comment by moray33** [comment]
Where is the uBlock Unbreak list? I can't find it.

**Comment by gjallarhorn** [comment]
In uBlock it's just called "uBlock filters".
"uBlock filters - Unbreak" is what it's called in uBlock Origin.

**Comment by lewisje** [comment]
There is a separate "uBlock filters" list in uBlock Origin, although it does seem to include some unbreakage.

**Comment by moray33** [comment]
Ok, I use uBlock, so I couldn't find it by that name.
The list is enabled. Last updated: 2015-01-27

**Comment by TerrakionSmash** [comment]
An interesting quirk here is Disconnect Malvertising is almost equal to Peter Lowe's + Disconnect Malware since Peter Lowe's almost equals Advertising Disconnect.
