### ISSUE TITLE
Unable to block fonts

### ISSUE THREAD

**Issue by birdie-github** [uBlock-LLC/uBlock#1492]
The rule

```
||fonts.gstatic.com/s/arimo/
```

doesn't seem to work at http://www.gsmarena.com/news.php3 Edit: it doesn't work in Adblock+ either.

Also $font is neglected: http://forums.mozillazine.org/viewtopic.php?p=12730559&#p12730559

**Comment by harshanvn** [comment]
##### Method 1:

You can use dynamic filtering rules, to block fonts, by blocking the <b>whole domain</b>  in <b>My Rules</b> tab -
<code>www.gsmarena.com fonts.gstatic.com \* block</code>
or to block this domain from any website, instead of just gsmarena, you can replace <code>_</code>
<code>_ fonts.gstatic.com \* block</code>

##### Method 2:

Alternatively, if you want to <b>block</b> only of <b>type <i>fonts</i></b> from this domain and not anything else, you can use below rule in <b>My Rules</b> tab. 
<code>gsmarena.com http://fonts.gstatic.com font noop</code>
or to block this domain from any website, instead of just gsmarena, you can replace <code>*</code>
<code> \* http://fonts.gstatic.com font noop</code>

<br>

##### Note:

I am not sure if <b>Method 2 </b> is supported in uBlock. But it is supported in <a href="https://github.com/gorhill/uBlock">uBlock Origin</a> version as part of Dynamic URL Filtering..

**Comment by birdie-github** [comment]
Tried both

```
www.gsmarena.com fonts.gstatic.com * block
fonts.gstatic.com * block
```

and none of them works.

**Comment by harshanvn** [comment]
Can you give me the screenshot of the rule?
And the url to test?
Did you check the logs? show us the screenshot of the logger, for the font requests...

Edit: I forgot. For this, you should click "I am an Advanced User". As these are the Dynamic Filtering rules...

**Comment by birdie-github** [comment]
Website: www.gsmarena.com

This screenshot in particular: http://www.gsmarena.com/samsung_galaxy_a8_is_now_official_in_china-news-13039.php
![gsmarena](https://cloud.githubusercontent.com/assets/4958603/8675284/74947f8c-2a5c-11e5-9c18-dad8ddfb2a59.png)
![gsmarena-log](https://cloud.githubusercontent.com/assets/4958603/8675353/d3ca5076-2a5c-11e5-8861-30ca36b0b2ac.png)

**Comment by harshanvn** [comment]
> by blocking the whole domain in My Rules tab -

You copied to wrong place. It should be in <b>My Rules</b> tab as advised. And remember to check "I am an Advanced User", to have an effect with these Rules.
And delete these rules in My Filters tab.

Note: These are not regular Adblock compatible filters. Rather they are Dynamic Filtering rules. Please read the wiki about it.

**Comment by birdie-github** [comment]
OK, I went to My rules, Hit "Edit" under temporary rules, added your both rules.

```
www.gsmarena.com fonts.gstatic.com * block
```

was added after "Commit" but

```
fonts.gstatic.com * block
```

was silently discarded.

And this first rule still doesn't seem to work.

**Comment by harshanvn** [comment]
Did you checked "I am an advanced user" option. Show me your network request logger screen shot

**Comment by birdie-github** [comment]
![info](https://cloud.githubusercontent.com/assets/4958603/8677998/9dc59e2c-2a6b-11e5-93af-0693ec986333.png)

**Comment by Snapy** [comment]
@birdie-github 
If you want to use static filtering, you have 2 options :
`||fonts.gstatic.com^` -> block all network requests to this domain (the `^` is important ; you can also add `$domain=www.gsmarena.com` to make it site specific)
`|fonts.gstatic.com/s/arimo/` -> block network requests beginning with the url (the single `|` is important)

If you prefer dynamic filtering rules :
`www.gsmarena.com fonts.gstatic.com * block` -> same effect as `||fonts.gstatic.com^$domain=www.gsmarena.com`
`* fonts.gstatic.com * block` -> block all network requests to `fonts.gstatic.com` on all websites
To add the rules :
1. Go to "My Rules" tab in the Dashboard.
2. Click "Edit" and paste the rules (1 rule per line).
3. Click "Save" : rules are temporary. Click "Commit" to make them permanent.

_Notes_
In uBlock Origin you can use :
the `$font` filter option
the no-remote-fonts switch but it will block more than Google fonts
dynamic URL filtering using the rule `gsmarena.com http://fonts.gstatic.com/s/arimo font block` as suggested by harshanvn
