### ISSUE TITLE
problem on FF39 on OSX 10.10.4

### ISSUE THREAD

**Issue by asheenlevrai** [uBlock-LLC/uBlock#1506]
Hi,

I am using uBlock 0.9.1.0.1 on 2 different macs (at home vs at work) both running OSX 10.10.4 and FF v39. Some sites won't load (or only incompletely) and just hang up (white screen most of the time). No issue when uBlock is disabled. No issue on Safari (uBlock not installed there).

Many site work properly though, even with uBlock enabled. Some sites have pages that can be displayed and others that cannot e.g xda-developers.com

Am I running the latest version of uBlock?

Best,
-a-

**Comment by lewisje** [comment]
TL;DR: No.

The latest version of uBlock for Firefox is 0.9.5.0; the latest version of uBlock Origin for Firefox is 1.0.0.0 and it has actually seen more development effort than uBlock.

The latest version of uBlock for Safari is 0.9.5.0 and unfortunately, uBlock Origin is not, and probably never will be, made available for Safari, because it costs serious money to get a Safari extension hosted for auto-update, and even a substantial amount for the right to _make_ Safari extensions, and @gorhill does not want to ask for, let alone rely on, donations or other means of monetization.

**Comment by LimboSlam** [comment]
@chrisaljoudi or @lewisje Is Ublock going to be maintain anymore? I'm a Pale Moon user that has recently switched over to Ublock Origin because of the active development @gorhill has shown to the Pale Moon browser. Though I'm not sure if this is temporarily? I would love to see @chrisaljoudi and @AlexVallat version of Ublock to continued support, because I really don't need all the extra functions that come with Ublock Origin, just the blocking and bug fixes here and there.       

A reply back would be greatly appreciated!  :)

**Comment by lewisje** [comment]
I haven't heard any news that uBlock _won't_ be maintained anymore, and I'm surprised that uBlock Origin has actually been developed more.

**Comment by AlexVallat** [comment]
From my point of view, I will continue to provide support for uBlock on Firefox, including Pale Moon, but only at a maintenance level. I do not intend to develop new functionality. I can't speak for @chrisaljoudi but I suspect he may be busy with his new OS-X blocker at present.

Whatever the original intentions or circumstances were, the status quo self-evidently is that uBlock Origin is under active development and receives new functionality and fixes at a rapid pace. That is simply not the case for uBlock.

**Comment by LimboSlam** [comment]
Thanks @lewisje, @AlexVallat for getting back to me. I guess we're really just at standby at this point.

**Comment by ghost** [comment]
@AlexVallat If you're not actively developing _uBlock_ anymore, why not simply hand over the project maintainership back to @gorhill ?
He can then stop using the _Origin_ name, and we're back to a simple, single, _uBlock_ branch.

**Comment by AlexVallat** [comment]
I agree that the situation is not ideal, and personally I would prefer it if there were just one uBlock branch, but unfortunately things are not so simple.

With regards to your specific suggestion:
1. uBlock isn't mine to hand over, it's @chrisaljoudi's. I just do some Firefox maintenance.
2. Chris has already offered to hand the project back
3. @gorhill does not (or at least did not) want it back

**Comment by ghost** [comment]
It's better if you guys, @gorhill, and another new set of people would simply develop _uBlock_ together.
It will be one, single brach, avoiding all the " _uBlock_ vs _Origin_ " confusion, or the " _uBlock Origin_ is the real version " one star reviews being posted on the _uBlock_ Chrome Webstore page.
