### ISSUE TITLE
Firefox forces disabling uBlock since they cannot verify it 

### ISSUE THREAD

**Issue by callain** [uBlock-LLC/uBlock#1511]
Since the last update of Firefox (WebDeveloperEdition), there is no way to enable uBlock.
![capture](https://cloud.githubusercontent.com/assets/7001103/9117921/8dbb236c-3c6d-11e5-85a9-db050cbf0c4f.PNG)

Firefox 41.0a2 (2015-08-06), Windows 8.1, uBlock 0.9.4.0

**Comment by AlexVallat** [comment]
In `about:config` set `xpinstall.signatures.required` to false.

The signed version is in AMO, but is very old, so unless you really need Firefox to block unsigned addons, I'd recommend simply toggling the preference.

**Comment by callain** [comment]
Great, thanks.

**Comment by sander85** [comment]
There is a problem with this option tho'..

https://wiki.mozilla.org/Addons/Extension_Signing#Timeline - they are going to disable this option soon..

**Comment by jomo** [comment]
>  The Developer Edition and Nightly versions of Firefox will have a setting to disable signature checks. There will also be special unbranded versions of Release and Beta that will have this setting, so that add-on developers can work on their add-ons without having to sign every build.

I see pros and cons of Mozilla's decision, but the fact is that people won't be able to install this, unless they are using dev versions of Firefox.

Is signing a big issue?
_(and can this be reopened?)_

**Comment by AlexVallat** [comment]
Signing is a big issue, unfortunately. Due to the way Mozilla have implemented it, only AMO can sign add-ons. You can choose whether you want them to only sign your add-on, or to sign it and list it, but not both. As we want uBlock to be available and listed in AMO, that means that it will only be signed as it become available there, which means after review (which means it will be very, very delayed).

The alternative is to have uBlock be unlisted and only host it on github, but I don't think we want to go that route. Or to have two different versions of uBlock (with different IDs, so Firefox would treat them separately) one listed and one unlisted. I don't like that much either.

I hope that by the time signing is forced on there will be a better solution, but for now there is not.

**Comment by Gitoffthelawn** [comment]
@AlexVallat My (limited) understanding is that once Mozilla completes their full review of an extension, that approval of updates are generally quite fast.

For other fully approved extensions, updates are sometimes released the same day the developers send them to Mozilla.

AFAIK, the initial full review is what takes what seems like forever.  I seem to remember reading that you or Chris submitted uBlock a while back, so it should be working its way through the queue.  Mozilla certainly needs more volunteers to help with their review queues (or needs to offer compensation!).

**Comment by AlexVallat** [comment]
@Gitoffthelawn At present, uBlock 0.9.3.5 has been in the queue for preliminary review since April, and is at position 52 of 344. I'm not sure how much the position means any more, as I think reviewers can pick and choose which addons they want to review. In any case, the intention was that once 0.9.3.5 passed preliminary review, the current version of uBlock would be submitted for full review.

**Comment by Gitoffthelawn** [comment]
@AlexVallat Sounds great.  (Well, except for sitting in the queue so long.)  Letting extensions sit in the review queue for so long is really not good for Mozilla or for them achieving their mission statement.  Perhaps you could ping them on their new [AMO support forum](https://discourse.mozilla-community.org/c/add-ons) or even mention the issue to a media outlet.  Mozilla is good at responding when you get in touch with the right people or the media gets involved.

**Comment by AlexVallat** [comment]
I have actually asked if there was any way that we could have signed self-hosted versions of an addon while we wait for review, but apparently not. It would have to be a separate addon with a different ID.

I'm hoping something changes before Firefox can no longer be configured to accept unsigned addons, otherwise there are no good answers. I'd be very tempted to just unlist the thing from AMO and give up on them, but I might be in a minority view there.

**Comment by Gitoffthelawn** [comment]
@AlexVallat  According to https://wiki.mozilla.org/Addons/Extension_Signing there is quite a bit of time until it becomes a major issue.  Firefox release is currently 39.0.3, and the first version to be concerned about is version 41, which won't hit general release for over 6 more weeks.  Version 41 will have a workaround switch that can be toggled which will be present until version 42 -- more than 12 weeks away.

I'm pretty sure the AMO version of uBlock is currently signed.  Mozilla signed all AMO extensions recently.  The big trouble is, AFAIK, you can't update it without losing your spot in the queue.  Hopefully, it will be fully reviewed soon so that you can publish updates.

In the meantime, I recommend posting something on the AMO support forum so everyone knows how long you have been patiently waiting.
