### ISSUE TITLE
Ublock blocking comment-sections.

### ISSUE THREAD

**Issue by GoodTimesAhead** [uBlock-LLC/uBlock#1535]
I'm having problems with ublock blocking the comments on some pages. Some are discuss some are facebook. I'm using EasyList, EasyPrivacy, Malware domains, Fanboy's Annoyance and social blocking list. Here are two examples of ublock blocking comments.

http://robhasawebsite.com/big-brother-2015-august-28-bb17-live-feed-highlights/
http://www.huffingtonpost.gr/2015/08/29/politiki-symfonia-diapragmatefsi-_n_8057976.html?utm_hp_ref=greece#comments

**Comment by RoxKilly** [comment]
Doesn't sound like a bug, but rather the result of blocklists working.  Do comments work if you uncheck all blocklists?  If so, you could enable the lists one at a time until you find the one that blocks what you want to use, and either:
1. Disable uBlock filtering on the pages in question,
2. Use [Dynamic Filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering) to allow the scripts that load those comments
3. Post an issue to the support forum for the blocklist in question
4. Stop using the blocklist

**Comment by publicarray** [comment]
Disqus should be blocked because of the Static filters `||referrer.disqus.com^` found in: EasyPrivacy and `||disqus.com/listpromoted?` found in: EasyList

For Facebook you can use the `||connect.facebook.net$script` filter. Alternatively you can subscribe to ~~`Fanboy’s Social Blocking List‎`~~ `Anti-ThirdpartySocial`. The list also removes like and share buttons.

**EDIT**
Do you want them to be blocked or unblocked?

You can whitelist a domain described [here](https://github.com/chrisaljoudi/uBlock/wiki/How-to-whitelist-a-web-site). if you want to unblock Disqus add `no-cosmetic-filtering: robhasawebsite.com true` to My Rules

@gorhill Do custom cosmetic whitelists work? I ask because I could not get Disqus to show with the following filter:

```
! 8/31/2015, 10:31:05 PM http://robhasawebsite.com/big-brother-2015-august-28-bb17-live-feed-highlights/
! To counter ##ad_container found in: EasyList
robhasawebsite.com#@##ad_container
```

**Comment by gorhill** [comment]
> I could not get Disqus to show with the following filter:

Try `robhasawebsite.com#@#.ad_container`.

**Comment by publicarray** [comment]
Cheers mate!
