### ISSUE TITLE
HTTPSSB and uBlock

### ISSUE THREAD

**Issue by toooonyy** [uBlock-LLC/uBlock#154]
Can these two extensions just work together?
Beacause I see httpsb's settings page looks pretty much the same as ublock's, so the question is can httpsb work as adlblockers, or an independent adblocker must be used. If httpsb can, will it save more memory?
PS I want to save my RAM, as I'm using a old PC now
PSS English is my second language, so if this's any stupid mistakes just LOL and tell me about it.

**Comment by mikhaelkh** [comment]
See [The road ahead](https://github.com/gorhill/httpswitchboard/issues/378)
 TL;DR: Stop using ABP-filtering aka pattern-based filtering in HTTP Switchboard, and install µBlock to take care of pattern-based filtering. µBlock's pattern-based filtering engine benefits from a lots of enhancement/fixes since the code was taken out of HTTPSB, and these enhancements/fixes won't make it to HTTPSB.

**Comment by toooonyy** [comment]
ok,thx a lot
