### ISSUE TITLE
Omniture in Journal of request but not in icon

### ISSUE THREAD

**Issue by TraderStf** [uBlock-LLC/uBlock#1543]
http://www.scmagazine.com/anti-spam/products/85/4/

You see that omniture is in red (like e.g. googleanalytics)
But when you click the icon, it is not listed.

Ghostery shows "Adobe Analytics (omniture)"

**Comment by publicarray** [comment]
when you say

> You see that omniture is in red

I assume you mean in the logger

> But when you click the icon

I assume that you have advance mode on and that you mean in the dynamic filter pane

That is by design, the dynamic filter pane shows the hostnames that the page has requested. A version of omniture.js is hosted by scmagazine.com as you can see in the log:
![screen shot 2015-09-17 at 12 57 16 am](https://cloud.githubusercontent.com/assets/5497998/9908557/904a6720-5cd7-11e5-8a1d-49875dbc649f.png)

Dynamic filtering is explained [here](https://github.com/chrisaljoudi/uBlock/wiki/Dynamic-filtering:-quick-guide#important)

> In bold, domain names. Domain names are hostnames, but hostnames are not necessarily domain names from uBlock's point of view: domain names are extracted as per Mozilla Public Suffix list.

Does this address your issue?

**Comment by TraderStf** [comment]
Sorry for not being clearer.
I got it, ublock report smag.com and ghostery 'omniture'.
No problem for me.
Thanks a lot.
Keep up the good work!
