### ISSUE TITLE
Rebrand as Purify

### ISSUE THREAD

**Issue by gblazex** [uBlock-LLC/uBlock#1544]
You have an iOS app now, the _uBlock_ name should go back to @gorhill  and there'll be less confusion.

You should use _Purify_ as your brand name consistently across platforms.

**Comment by zummuz** [comment]
I agree with @galambalazs, there will be less confusion. Plus chris would be able to sell this extension for 4$ with free conscience.

**Comment by gorhill** [comment]
> sell this extension for 4$ with free conscience

What makes uBlock "uBlock" is its core filtering engine which required a whole lot more work than coming up with the name.

**Comment by zummuz** [comment]
@gorhill my first post is sarcastic. I know uBlock has been written from scratch by you and it differs from ABP alot. I was saying chris dropped uBlock maintenance because he couldn't monetize it (he tried) and now selling Purify which (I'm pretty sure but we can't find out because it's not open source) is based on uBlock.
If I'm not right I'd like to know.

**Comment by gorhill** [comment]
> based on uBlock

Unlikely, the filtering engine of all these new iOS blockers is Apple's own code -- they all use the same filtering engine. A blocker' job is merely to feed rules to the new API. What I wonder is if and which of these new blockers make use of community-maintained filter lists such as EasyList (using EasyList requires proper attribution as per license.)

**Comment by 5t3f4n** [comment]
@gorhill 

> What I wonder is if and which of these new blockers make use of community-maintained filter lists

Could you monitor your network traffic and see if any connections are made to any servers of such lists?
Also, if am I allowed to go slightly off topic here, do you have any plans whatsoever to develop for iOS?

**Comment by gblazex** [comment]
So what do you think @chrisaljoudi ?

(used cc cause the last public activity seems to be one month old)

**Comment by xHN35RQ** [comment]
Has it really been a month since @chrisaljoudi last activity? And he's still taking donations via `ublock.org`? What an asshole move to abandon the uBlock userbase... while still making money from them. Not cool. :angry: :-1:

**Comment by xHN35RQ** [comment]
Hrm, someone deleted my comment about `ublock.org` continuing to make money for @chrisaljoudi while he is AWOL ... I wonder who deleted it?

**Comment by gblazex** [comment]
Yes it's weird. But...

Guys please don't turn this thread into a fight.

I raised a legitimate point let's get Chris to answer.

**Comment by xHN35RQ** [comment]
> I raised a legitimate point let's get Chris to answer. Guys please don't turn this thread into a fight.

Yes, you did raise a good point, and I'm too am interested in his reply. I apologize for being antagonistic. If Chris has a good reason for being absent then it's no problem for me.

**Comment by harshanvn** [comment]
> I raised a legitimate point let's get Chris to answer.

Sorry, you were expecting an answer from Chris.

But if i may.. 

I think the name still should be continued to use uBlock, unless the underlying <b>core</b> code has been changed <b><i>completely</i></b>. Remember, it is not just the name,' the <b>code</b>', 'the effort' put into it, is what makes the uBlock today!

I am afraid, changing it to some thing else, am sure people would forget that it is who "gorhill a.k.a Raymond" created it.

Hope you understand! :)
Just my 2 cents..

**Comment by xHN35RQ** [comment]
Chris has a number of ways he can relieve himself of the burden of supporting uBlock:

1. close this repository
2. convert this repository to a safari-only ublock repo
3. transfer this repo to a uBlock Organization
4. transfer this repo to gorhill

Any of these options gives Chris more time to work on his own projects. 

And, I don't think people will forget it was gorhill who created it. Just looking at the codebase, it's clear who is the creator.

**Comment by gblazex** [comment]
@harshanvn You miss the point. For example you can fork the Firefox project but you cannot call it Firefox! The codebase can be the same but the name cannot, so as to avoid confusion.

Now, it is different in the case of uBlock because as far as I know there's no restriction for the use of the name, what's more @gorhill transferred the project to @chrisaljoudi.

So it'd be perfectly _legal_ for @chrisaljoudi to keep the name _and_ the codebase. 

But my point is that it only leads to confusion. For _ethical_ reasons (aka "to do the right thing") this project should use a different name. 

I think there should be **one uBlock**. Anybody can fork the codebase and publish their own extension, this is the nature of open source. 

But now that that @chrisaljoudi has his own brand (**_Purify**_) he could give the uBlock name back to its _creator_ and current _maintainer_.

**Comment by harshanvn** [comment]
@galambalazs You are right! Yes, one can change the name, after forking it. 

However as you said, it is little different in this case, as its transferred maintainership!!!

One thing to sort here is , if it is merged to uBlock Origin, what would happen to vanilla uBlock in Firefox AMO. i.e.,
-  It has little different UI (which is being used by 200,000 users, and i am worried how they react to the new UI)
- And a lesser feature set (which i am not much worried about, as those users would gain more fine-tuned code base and updated feature set)

**Comment by gorhill** [comment]
> a lesser feature set

What?

**Comment by Betsy25** [comment]
I understand @chrisaljoudi now spends 100% of his time on the iOS part of things, therefor i find it a little shame he accepted the original uBlock from @gorhill without much consideration.
I know raymond has his hands more than full with further perfecting and refining a wonderful product, most "issue" posts are back at Gorhill's repository.

It might be better to put uBlock at rest, uBlock Origin is here for all of us, and Purify is there for iOS.
I just hoped Raymond could at least catch a few bucks for his excellent contribution.

**Comment by ghost** [comment]
"I just hoped Raymond could at least catch a few bucks for his excellent contribution."

I doubt that he did, which is good, because this was explicitly never his goal and he said so himself. As I understand his agenda this would defeat the purpose and integrity of uBlock (Origin). Just take a look at the whole Adblock Plus mess.

**Comment by PatTheMav** [comment]
@chrisaljoudi confirmed to me on Twitter that a Purify version for OSX is planned, which makes total sense in my book. Safari in El Capitan uses the same content blocker API as in iOS9, so Purify (and similar OSX blockers) would be faster and more efficient than any extension-based blocker.

If I followed the tweets correctly, Purify on OSX will be free for anyone who purchased the iOS version and still uses the "optimized" rules that made it one of the top 5 content blockers in terms of speed (others use the "vanilla" EasyLists but seem to be less quick than the optimized competitors).

As such it doesn't make much sense to rebrand uBlock to Purify (especially considering that for Purify the bulk of the work is in optimizing and maintaining the optimized block list). It still might be a good idea to have some "official" word on how uBlock will be maintained in the future (as some might want to keep the extension's more customizable nature or not upgrade to El Capitan).

My current impression is that as a Firefox or Chrome user, you might want to use the more rapidly updated uBlock Origin, as a Safari user you are "stuck" with uBlock and might be better off switching to El Capitan and use Purify, Refine, et. al. once they're available.

**Comment by Freida-Moo-Goo-Gai-Pan** [comment]
Content blockers on OS X are not good. They all have issues with youtube,  they don't hide spacers for what they block, etc......  Traditional ad blocking is still better. 

The current owner of this fork is more interested in monetizing his Purify app. This includes from what I've seen on Twitter, him threatening other developers with content blocking apps and trying to get them removed from the app store for iOS.  Sounds an awful lot like what the ABP people have been doing to their competitors with free solutions. 

The best thing that could happen is that somebody will work to do an official port of uBlock Origin for Safari and then we can all leave this unmaintained uBlock behind us.   It's obvious money is his goal and  that is fine, however, seems rather silly that he is the owner of this project and has left it in this situation.  

Between his scaring other devs on the iOS app store and this, it kind of says what type of person he is.

**Comment by chrisaljoudi** [comment]
@Freida-Moo-Goo-Gai-Pan

I've been silent about this because an actual official announcement regarding the direction of this project is coming. But

> scaring other devs on the iOS app stor

That's ridiculous. The only two apps I reported to the App Store were more-than-obvious clones/imitations of Purify — one of them even used the name Purify and lazily mutated the logo:

![clone logo](http://i.imgur.com/RxJRIXE.jpg)

Second, uBlock is no longer under development for Safari because the extension APIs that made it possible are now deprecated and have been replaced by the new Content Blocking APIs, which is what Purify uses.

**Comment by chrisaljoudi** [comment]
Also:

> Content blockers on OS X are not good. They all have issues with youtube, they don't hide spacers for what they block, etc...... Traditional ad blocking is still better.

The part about hiding spacers is utter BS FYI.

The YouTube problem is a Safari bug that has been fixed in nightlies.

**Comment by harshanvn** [comment]
> uBlock is no longer under development for Safari because the extension APIs that made it possible are now deprecated and have been replaced by the new Content Blocking APIs

@chrisaljoudi Can you provide a link, where they say it is deprecated?

> uBlock is no longer under development for Safari

@chrisaljoudi If its no longer being developed, why this site @ublock.org is being asked for dontations. Though its been stagnant (for the better part) from its inception in April :(. Excluding few commits from @AlexVallat

**Comment by gblazex** [comment]
> I've been silent about this because an actual official announcement regarding the direction of this project is coming.

Whatever this direction is I'll be happy, as long as the name goes back to @gorhill 

You rode the uBlock wave, now you have a totally separate money making app. Serious money.

It's time to end the confusion that's been surrounding uBlock.

Do the right thing.

Cheers

**Comment by publicarray** [comment]
@chrisaljoudi why not state that this repo is deprecated and that a new safari extension is on it's way in the Readme.md?

**Comment by harshanvn** [comment]
@chrisaljoudi Can you tell when did you come to know about Safari Extension deprecation? I guess maybe for couple of months. (if so) And you still continued to seek donations for uBlock @ublock.org. :(

**Comment by publicarray** [comment]
@harshanvn

>  ~~advise to opt for alternate free blockers for iOS like Adblockfast atleast~~

~~I think you miss read the conversation here. The extension APIs depreciation is for desktop Safari and has nothing to do with iOS.~~

> Can you provide a link, where they say it is deprecated?

I am not sure if these are the ones @chrisaljoudi  was referring to but..
https://developer.apple.com/library/safari/releasenotes/General/WhatsNewInSafari/Articles/Safari_9.html#//apple_ref/doc/uid/TP40014305-CH9-SW10
after the image it says

> Note: The onbeforeload event and canLoad message for content blocking have been deprecated

**Comment by harshanvn** [comment]
@publicarray I have removed about that advice immediately after posting it..

**Comment by Betsy25** [comment]
> Whatever this direction is I'll be happy, as long as the name goes back to @gorhill
> 
> You rode the uBlock wave, now you have a totally separate money making app. Serious money.
> 
> It's time to end the confusion that's been surrounding uBlock.
> 
> Do the right thing.
> 
> Cheers

+1

Except for 1 thing, he didn't ride the uBlock wave at all, except for some .txt file changes, consisting of changing all links to his homepage, and a lot of styling & colorizing of his homepage.
Raymond sensed this from the very beginning, and he made the perfect decision.
It ain't the add-on, it is the $$$

I really feel sorry for all the work Raymond has done into forking & re-naming,   for what ? for nothing at all.

I would like to conclude, regarding the 0.99$ "choices" for iOS, be aware that Purify is closed source, and the man will take every opportunity to make money out of it. At least the ABP author made it public that he was getting paid by the biggest advertisers, let's see if this guy is so honest. From the look of his couple of YT video's, imho I have serious doubts....

**Comment by xHN35RQ** [comment]
@chrisaljoudi remarks in this thread do nothing to explain the situation with uBlock. I guess I was hoping for too much.

**Comment by PatTheMav** [comment]
@chrisaljoudi 

> I've been silent about this because an actual official announcement regarding the direction of this project is coming. [...] uBlock is no longer under development for Safari because the extension APIs that made it possible are now deprecated and have been replaced by the new Content Blocking APIs

I fully expect that the technical requirements to make ad blockers work will be removed entirely within the next 1-2 OS X updates, so that move is entirely reasonable, but it should've been communicated earlier to manage the expectations leveled at you and the project. 

Too late now, but I guess with all the drama surrounding this project ever since you stepped forward to actually _do_ the Safari releases (and not just talking about doing it sometime), it's better to end it on this note and leave the project to whoever wants to keep it running for people that wish to stay on Yosemite (or below).

**Comment by publicarray** [comment]
@Betsy25 

> he didn't ride the uBlock wave at all, except for some .txt file changes and a lot of styling & colorizing of his homepage.

Chris and Deathamns ported uBlock to Safari. see: [vapi-common.js](https://github.com/chrisaljoudi/uBlock/commits/master/platform/safari/vapi-common.js), [vapi-background.js](https://github.com/chrisaljoudi/uBlock/commits/master/platform/safari/vapi-background.js) and [vapi-client.js](https://github.com/chrisaljoudi/uBlock/commits/master/platform/safari/vapi-client.js)

 @PatTheMav 

> I fully expect that the technical requirements to make ad blockers work will be removed entirely within the next 1-2 OS X updates

True, but I think these extensions will be replaced by ad block extensions that use the new [Content-Blocking rules](https://developer.apple.com/library/safari/documentation/Extensions/Conceptual/ContentBlockingRules/Introduction/Introduction.html) instead.

**Comment by heubergen** [comment]
@chrisaljoudi Have you any plan to port Purify to the desktop safari version?

**Comment by chrisaljoudi** [comment]
@heubergen it's in the works.

**Comment by heubergen** [comment]
Great, thanks :)

**Comment by Gitoffthelawn** [comment]
This gang-mentality attack of another person is getting old.  It's also very mean-spirited.  Do any of you stop to think of the negative impact you are having on Mr. Aljoudi?  What you are doing is cruel and nasty.

Instead of attacking a fellow human being, perhaps people could choose to be more kind.

A productive use of people's time might be to take a moment and learn accurate facts.

Here are the facts, all of which you can easily verify for yourself:
1. Raymond Hill (aka Gorhill) gave up mainternership of this repo because he didn't like dealing with the people in this repo who were posting issues.
2. Raymond Hill chose to assign mainternership of this repo to Chris Aljoudi.
3. Chris Aljoudi offered to give mainternership of this repo back to Raymond Hill.
4. Raymond Hill refused to take back maintainership of this repo.

From what I've seen, Chris had good intentions when he accepted maintainership.  He was even active making improvements to the code.  After being attacked left and right by certain people here, I'm not surprised he chose to focus on other projects.  That said, because he isn't actively working on this repo, it's probably best if one or more other people step up to actively maintain this repo.

Given that Raymond has indicated that he does not like openly interacting with others, and has an established history of blocking people from his uBlock Origin repo, it's hard to say what is best for uBlock.  Ideally, _this_ repo will be updated with recent enhancements made by Raymond, and will find one or more new maintainers dedicated to keeping this repo strong.  That way, uBlock can continue as an open community-based project and other developers can add functionality and enhancements that Raymond is unwilling to add, like an obvious on/off toggle, which is the most frequently-requested feature.

We owe our thanks to Raymond Hill for taking his valuable time to develop such a fine piece of code.  We also owe our thanks to Chris Aljoudi for his willingness to take on maintainership when Raymond grew tired of the human side of project development.  Finally, we owe our thanks to Allex Vallat and all the other developers for their code contributions.  **Thank you to everyone for your fine work and the time you have chosen to spend.**

**Comment by xHN35RQ** [comment]
> This gang-mentality attacking another person is getting old.

How is it attacking someone to ask for information about a project that seems to be abandoned. And then to express disappointment when no information is forthcoming?

> because he isn't actively working on this repo, it's probably best if one or more other people step up to actively maintain this repo.

Welp, that's what this thread is about. :wink: For this to happen, Chris needs to "pass the keys" to those who would step up. As it stands, we don't know if he's willing to do that or not. @chrisaljoudi if you're willing to hand off uBlock Safari development to other developers it would be good to know.

@Gitoffthelawn It's not a matter of who did what, and when. Please don't go back and rehash the drama. This thread is about the future of this repository, and whether or not uBlock Safari users can rely on future updates and fixes.

**Comment by harshanvn** [comment]
> What you are doing is cruel and nasty.

Don't say each and every one who added their views are cruel or nasty.
Atleast as far as i am concerned, i am unhappy because -

**Comment by harshanvn** [comment]
> What you are doing is cruel and nasty.

Don't say each and every one who added their views are cruel or nasty. Most of them can be taken in positive manner..

Atleast as far as i am concerned, i am unhappy with uBlock.org because -

1) uBlock.org website tells that uBlock is the main version. Which in reality are both two different versions..

 Proof, see below - https://www.ublock.org/faq/

> You're welcome and should feel free to use either per your own judgment. If you're currently using uBlock Origin, you're welcome to move over to the main uBlock project.

<u>And more..</u>

> If you're using uBlock Origin, you're welcome to move over to the main uBlock project. uBlock is actively supported by the uBlock development team.
>       Alternatively, if you wish to use gorhill's personal fork, please feel free to do so. gorhill has stated he will focus on maintenance.
> <b>In contrast, the uBlock project will be moving forward with awesome new features, refinements, and enhancements. We at the uBlock team are very excited and looking forward to improving your web experience even further.</b>

Note: The above statements has been removed once Raymond has clarified the things.. But, if you see, how Chris has advertised, and lured users to shift the users from uBlock Origin. Which is not at all a good thing..

2) uBlock.org (maintained by chris) <b>still</b> asks for donations, to keep the project alive with awesome feature/refinements/enhancements. 

As, chris is not doing anything to uBlock. So, why these donations links are still kept alive and promoted? What could be the possible reason behind it? 

> 1. Raymond Hill (aka Gorhill) gave up mainternership of this repo because he didn't like dealing with the people in this repo who were posting issues.
> 2. Raymond Hill chose to assign mainternership of this repo to Chris Aljoudi.
> 3. Chris Aljoudi offered to give mainternership of this repo back to Raymond Hill.
> 4. Raymond Hill refused to take back maintainership of this repo.

I agree with you, above are true, but you have conveniently ignored all the other things, few of which i pointed above...
Also, remember taking a repo back is not a simple thing, both are diverged significantly like -
uBlock removed per-site switches, uses font-based icons. Which are complete opposite in uBlock Origin.
And uBlock Origin has now tons of features/improvements added to it..

**Comment by Gitoffthelawn** [comment]
> Don't say each and every one who added their views are cruel or nasty. Most of them can be taken in positive manner..

I did not write what you claim.  Read it again.  I wrote collectively about the gang-mentality attack on Chris.  If you feel it applies to you or to each and every person who added their views, that's on you.  It's clearly not what I wrote.

> uBlock.org website tells that uBlock is the main version. Which in reality are both two different versions..

When uBlock Origin was created, uBlock was the main repo.  Raymond Hill transferred away the uBlock repo and then created the uBlock Origin fork so that he could continue to program without  having to deal with the uBlock community.

Since then, Raymond has put quite a bit of work into uBlock Origin, and most of that work has not been added to uBlock.  At the same time, the uBlock repo is the only repo where all community members are free to post issues.  The situation is a confusing mess to the average user.

I agree, at this point the products are two different versions.  The upside to uBlock is that it designed to be a community project where everyone's contribution and feedback are valued.  The downside is that development has stalled.  The upside to uBlock Origin is that it is receiving active development by Raymond.  The downsides to uBlock Origin are that only features that Raymond wants to add will be added, he does not like dealing with the community, and he has a history of blocking people from his repo.

> ... Note: The above statements has been removed once Raymond has clarified the things..

You seem to value holding a grudge against Chris.  You're quoting text that Chris deleted some time ago.  The fact that Chris deleted the text indicates that he was willing to work to fix misconceptions.  By quoting his deleted text, you are indicating that you want to continue the propagation of misconceptions.

> uBlock.org (maintained by chris) still asks for donations, to keep the project alive with awesome feature/refinements/enhancements. 

I think it would be good if Chris explained to the community if he still plans on contributing to uBlock.  But given how a number of people have treated him, I'm not surprised that he has not made it a priority in his life.

> As, chris is not doing anything to uBlock. So, why these donations links are still kept alive and promoted? What could be the possible reason behind it? 

That's a good question.  I think it would be fair to know if he has any plans to continue work on uBlock.  If so, great.  If not, I think it's best for other people to step up and maintain the repo.

As far as the money goes, I doubt he even receives enough to pay for the uBlock.org website.  I doubt most people even know about uBlock.org; it's not even mentioned on the Mozilla Add-Ons website (GitHub is the only site listed, and the Mozilla donations system is not enabled for uBlock).  Given how some people have treated him, if he's made a couple quid, that's not sufficient to compensate for all the grief.  But I'm guessing his expenses exceed any donations.

Did you donate?  Has anyone?

> I agree with you, above are true, but you have conveniently ignored all the other things, few of which i pointed above...

When others show good faith by working to fix misconceptions, I don't drag up their deleted text to try to villanize them.  Chris has even posted a nice video on YouTube explaining his good faith efforts.

**Comment by Gitoffthelawn** [comment]
@chrisaljoudi What's your plan for uBlock at this point in time?

@community Are there people who want to step up and volunteer to help maintain uBlock?

**Comment by zummuz** [comment]
> ... the gang-mentality attack on Chris. 
> Since then, Raymond has put quite a bit of work into uBlock Origin ...
> The upside to uBlock is that it designed to be a community project where everyone's contribution and feedback are valued.
> The downsides to uBlock Origin are that only features that Raymond wants to add will be added, he does not like dealing with the community ...
> The fact that Chris deleted the text indicates that he was willing to work to fix misconceptions.
>  But given how a number of people have treated him, I'm not surprised that he has not made it a priority in his life.
> ... if he (chris) has any plans to continue work on uBlock. If so, great.
> As far as the money goes, I doubt he even receives enough to pay for the uBlock.org website.
> But I'm guessing his expenses exceed any donations.
> Chris has even posted a nice video on YouTube explaining his good-faith efforts.

Looks like script for sick stand-up show. Are you chris'es relative?

**Comment by Gitoffthelawn** [comment]
> Looks like script for sick stand-up show. Are you chris'es relative?

That type of comment is likely why there are no contributions lately.  What do you gain by acting that way?

**Comment by harshanvn** [comment]
> If you feel it applies to you or to each and every person who added their views, that's on you. It's clearly not what I wrote.

OK Thanks. Looks like i clearly misunderstood your statement.

> The upside to uBlock is that it designed to be a community project where everyone's contribution and feedback are valued. 

Same with uBlock Origin. However, any features to be added should strictly adhere to uBlock Origin's goals..

However, i am yet to see a single implementation of any kind of community request <b>being implemented</b> for uBlock;)

Care to point me the commits, on what are the community requests that are valued??

> The downsides to uBlock Origin are that only features that Raymond wants to add will be added, he does not like dealing with the community, and he has a history of blocking people from his repo.

And those features are beneficial to the entire community. I just don't understand this claim - "only what Raymond needs, are added". At this point, this is the single most <b>feature rich</b> addon which does more than any other in its category.

Any features (if) to be added, have to be well explained and should be beneficial to the larger audience. Not just duplicating the browser functionality requests..This is what Raymond follows...

> and he has a history of blocking people from his repo.

Since, there are no mods as in like forums, Raymond has to do him self unfortunately.

> You seem to value holding a grudge against Chris. You're quoting text that Chris deleted some time ago.

And there was note, which you have quoted already (so, i don't think u would need an explanation), but let me explain the reason i brought it.. is because of the things like below (just mentioned 1) -

And no i do not have grudge against him. But i do definitely have bad faith in him. Sorry

> uBlock.org (maintained by chris) still asks for donations, to keep the project alive with awesome feature/refinements/enhancements. 
> 
> As far as the money goes, I doubt he even receives enough to pay for the uBlock.org website.

I don't think so, how ever it is only chris, who can give the correct answer on how much he earned..Good luck getting an answer from him..

> I doubt most people even know about uBlock.org;

Actually more people (an average joe) and sites, are landing on uBlock...rather than Gorhill's Repo. You can see many people (from reddit)/articles mentioning about it..

> I think it would be good if Chris explained to the community if he still plans on contributing to uBlock. But given how a number of people have treated him, <b>I'm not surprised that he has not made it a priority in his life.</b>

<b>He should have taken this as a priority, at least this way the community backlash would have been reduced or gone :). </b>

> I don't drag up their deleted text to try to villanize them.

i Kept a note (saying it was rectified), So, did not villanize him. Just pointing out his past/current actions, and the reason as i explained above, and more (one other example <a href="http://thenextweb.com/insider/2015/10/14/the-surprising-amount-of-money-an-adblocker-was-offered-to-show-acceptable-ads/">here</a>).

> Did you donate?

I wanted to, but Raymond did not have a policy for donations. Just wanted to show him the appreciation!

And coming to uBlock.org, NO. I am following this project (back from 2014 from httpswitchboard days), and all the happenings. I was skeptical initially, And good that i did not.

**Comment by zummuz** [comment]
> That type of comment is likely why there are no contributions lately.

You are confusing cause and consequence.

> What do you gain by acting that way?

What do you plan to achieve by misleading and confusing people with your hypocritical comments? 

> Since then, Raymond has put quite a bit of work into uBlock Origin ...

Quite a bit? Did you mean quite a few? You are on github already, you can check it with two clicks.

> The upside to uBlock is that it designed to be a community project where everyone's contribution and feedback are valued.

There hasn't been any feedback from the maintainer for a long time and any valuable contribution at all.

> The downsides to uBlock Origin are that only features that Raymond wants to add will be added, he does not like dealing with the community, and he has a history of blocking people from his repo.

gorhill knows better what features should be added. He answer to every adequate post. Yep, banned a spammer [and explained why](https://github.com/gorhill/uBlock/issues/839#issuecomment-148925778) - what a cruel person. 

> As far as the money goes, I doubt he even receives enough to pay for the uBlock.org website.

There is progress bar on that site which shows he receives enough. Btw how much does it cost to maintain a plain site with donate button for a month?

> But I'm guessing his expenses exceed any donations. 

What expenses? Do you take sentences from a fairy tale book and just post it here?

**Comment by harshanvn** [comment]
> That type of comment is likely why there are no contributions lately.

I haven't seen any single awesome feature/enhancement from April..
Again remember, at least if he tries to fulfill what he said on his website, there will not be any backlash..

**Comment by zummuz** [comment]
> @community Are there people who want to step up and volunteer to help maintain uBlock?

There is no need to maintain it, users should just switch to uBlock Origin. chris claims that 

> uBlock is no longer under development for Safari because the extension APIs that made it possible are now deprecated and have been replaced by the new Content Blocking APIs

so no one is "stuck" with it on Safari anymore.

**Comment by Betsy25** [comment]
Let's just stop it people, most people already abandoned this abandoned begware, they chose the tool that is maintained by someone who's willing to offer a brilliant product without even requesting anything in return.

If you look at the bunch of "most-popular" & "Alternative to" sites, you see most people dropped uBlock already & went to the real thing, except a few ignorant individuals.

Let's be honest, nothing at all has been done to uBlock since the change of "author", except linking every possible string in every possible .txt or document file to his begware page.

The "upcoming awesome new features, refinements, and enhancements" where merely a bunch of lies to draw the masses to the donation button. It's only after months of nothingness that people, rightfully so, finally started to complain about this bunch of false fairytales.

He gave uBlock a bad name. End of Story.

**Comment by Gitoffthelawn** [comment]
If this is abandoned and uBlock has a bad name, why are you all still here?

There are over a quarter of a million people using this software.  Referring to all those users as "a few ignorant individuals" is, well, you know what it is.

**Comment by zummuz** [comment]
> If this is abandoned and uBlock has a bad name, why are you all still here?

It is not user's fault that they are not aware of the project's state and keep posting issues to this repo (some issues could affect uBO also). So people help them, gorhill checks this repo now and then, even these people who don't code can be helpful (can answer simple questions, try to reproduce issues, etc.).

**Comment by xHN35RQ** [comment]
Who keeps deleting my posts in this thread? I left a nice reply to @Gitoffthelawn which I went out of my way to word politely and thoughtfully. And now it's gone. What? Why?

**Comment by Gitoffthelawn** [comment]
Some of us are completely blocked from the uBlock Origin repo and therefore cannot post issues or help others there.  It's not developed in an open way like most other open-source software.  That repo is one person's personal project and is run as such.  Nothing wrong with that, but it makes that repo quite different from this one.

The coding by that developer is outstanding, but he does not run it like a real open-source community where everyone's input is valued and appreciated.  Remember, he left this repo and gave it away to the first taker because he did not want to be involved with the uBlock community.

**Comment by Betsy25** [comment]
@Gitoffthelawn that most probably is because these people were requesting features that don't belong in the scope of uBo, It's developed in a perfectly open way, the only difference with this one here, is that feature requests are at least being read and considered, here they are wasted keystrokes.

If Raymond spends a huge chunk of his days actually busy with the code, he obviously can't respond to 400 issue requests per day.

You say Raymond doesn't want to be involved with the uBlock community ?

Here you go, and see who does get involved and who doesn't...
https://github.com/chrisaljoudi?tab=activity
https://github.com/gorhill?tab=activity

**Comment by xHN35RQ** [comment]
> It's not developed in an open way like most other open-source software. That repo is one person's personal project and is run as such. Nothing wrong with that, but it makes that repo quite different from this one.

And this 

> The coding by that developer is outstanding, but he does not run it like a real open-source community where everyone's input is valued and appreciated.

A "real open-source community" is an appeal to a non-existent standard. There is no such standard.

Take a look at the development of the Linux Kernel. Linus Torvalds is famous for not valuing and appreciating everyone's input. And consistently the Linux Kernel is one of the golden standards of open-source programming.

Good code and Good Results are the most important things in open-source programming. Not whether everyone is valued and appreciated.

You have to earn the right to be valued and appreciated. And you do that by writing good code, to generate good results for the end user.

If anyone is under-valued or under-appreciated it's because either they were not writing Good Code, or they were doing things that would not generate Good Results for the scope of the project.

**Comment by Gitoffthelawn** [comment]
@Betsy25 I personally did my best to help out the uBlock and uBlock Origin communities by improving the uBlock and the uBlock Origin wikis, which were in desperate need of improvement.  I took my time to do this because I felt it could help many people, including the developers.  I spent many hours donating my time.  By improving the wikis, many common questions could be answered, which would help many people.

In response to my help, Raymond Hill blocked me from the uBlock Origin repo without a single word of communication.  That's not how a good open-source project is run.  Raymond has blocked others as well.  In contrast, Chris Aljoudi publicly thanked me for helping with the wiki in the uBlock repo.

**Comment by meat-ball** [comment]
I liked ublock and was sorry to hear (through the user comments) that it was no longer being developed. To each his own. But then I remembered this- https://www.reddit.com/r/apple/comments/398fgq/apples_new_safari_extension_policy_100year_to/
There could be (and probably is) more to the story, but you can understand why this may look a little dubious.

**Comment by publicarray** [comment]
you can switch to [uBock Origin](https://github.com/gorhill/uBlock) which is actively developed. For safari I am still using [uBlock](https://extensions.apple.com/details/?id=net.gorhill.uBlock-96G4BAKDQ9). If all your need is an adblocker many alternatives exists: e.g. [Adblock Plus](https://safari-extensions.apple.com/details/?id=org.adblockplus.adblockplussafari-GRYYZR985A), [ghostery](https://extensions.apple.com/details/?id=com.betteradvertising.ghostery-HPY23A294X) etc.

If you have OS X El Capitan you can try out Content blockers: [Adamant](https://safari-extensions.apple.com/details/?id=com.corybohon.Adamant-Safari-683GF3WH33), [Ka-Block!](https://safari-extensions.apple.com/details/?id=com.kablock.osx-UYW4V22L7E), [NoThirdParty](https://safari-extensions.apple.com/details/?id=net.NoThirdParty-AK3JVSZ85V), [Roadblock](https://safari-extensions.apple.com/details/?id=com.obiedcorner.roadblock-WE58FS6Q6B), [Wipr](https://safari-extensions.apple.com/details/?id=com.giorgiocalderolla.wipr-desktop-4449XA862Y) or [JS Blocker 5](https://safari-extensions.apple.com/details/?id=com.toggleable.JavaScriptBlocker5-6S8J5HV3H4)
