### ISSUE TITLE
RFE: please add possibility do enable/disable uBlock through its menu/shortcut

### ISSUE THREAD

**Issue by yarda** [uBlock-LLC/uBlock#1551]
It would be nice to have button/shortcut to disable/re-enable blocking for all sites/tabs without storing any exception. Currently it seems the only way is to disable the extension which is clumsy. This could be useful for development or e.g. for some shops affiliate programs where I don't have time to investigate the whitelist, just temporally disable the blocker, buy the item and re-enable it. Sometimes whitelisting the domain is not enough due to various 3rd party providers involved in the affiliation program (e.g. site A opening tab with site B, both needs to be without blocker, but if not in transaction I want B to be fully covered by the blocker). I am sure there will be various other use cases.

**Comment by zummuz** [comment]
Hi, you can try to disable filtering by setting dynamically global rule (Dynamic filtering overrides static filtering):
![global](https://cloud.githubusercontent.com/assets/13698274/10276374/bc4bb868-6b57-11e5-9bfd-7a1c55eaccc1.png)
Loaded pages after restart will not be filtered and new ones either, when you need to turn filtering back just press the eraser button.
I use uBlock Origin and assume forked uBlock could look different.

**Comment by helarqjsc** [comment]
Why isn't there an option to turn off temporarily though? It's such a vital functionality for an ad blocker. I had to switch back to ABP because uBlock makes it a nightmare to work with any kind of marketing site.

**Comment by zummuz** [comment]
@helarqjsc In the way described above there are 2 clicks to turn off uBlock temporarily:
1) on icon to show user interface
2) into the cell (+ all)
And there are 2 clicks to turn it on back:
1) on icon to show user interface
2) eraser icon
It is the option, instead of creating another button the developer used convenient feature of the interface. Can you do it with one (or less) clik in ABP? If you want to turn uBlock off for a particular site only, then click into the cell from the right column (the same number of clicks).
