### ISSUE TITLE
uBlock is blocking Marketo forms from MAC users

### ISSUE THREAD

**Issue by julieannasb** [uBlock-LLC/uBlock#1566]
If a person comes to one of our website/landing pages because they want to download an ebook or start a free trial the gateway form (Marketo hosted) is blocked by uBlock. This seems to only be an issue for people with MACs. uBlock is also blocking our Optimizely testing which allows us to test for better user experience on our website. 

Please help, thanks!

![errors](https://cloud.githubusercontent.com/assets/15388063/10834332/b9c28f34-7e55-11e5-876b-1106e414f6b4.png)

**Comment by lewisje** [comment]
It's probably an issue with EasyList or EasyPrivacy; go to https://forums.lanik.us/ to complain.

**Comment by julieannasb** [comment]
Thank you lewisje, I just reached out to them so we will cross our fingers. Does that listing service get used by ublock too or just adblock plus (the site only mentions adblock plus)?

**Comment by lewisje** [comment]
It's used by almost every ad-blocker that uses ABP syntax, because it is the only actively maintained general filter-list remaining; this means that both uBlock and uBlock Origin (only the latter being actively maintained) use it, and so does AdBlock from Betafish Inc.

The site probably mentions Adblock Plus because it was the first extension to use filter lists like that, and Eyeo GmbH (the company behind Adblock Plus) also hosts EasyList on its servers, even though volunteers from the ad-blocking community actually maintain it.

**Comment by julieannasb** [comment]
Ok thank you so much!
