### ISSUE TITLE
TopCashBack whitelist not working

### ISSUE THREAD

**Issue by spongbros** [uBlock-LLC/uBlock#1570]
The whitelist provided by the website TopCashBack (https://www.topcashback.co.uk/Misc/AdBlockWhiteList.aspx) does not appear to work. When adding the url as a Custom filter list, the title is parsed but the filter items are displayed as “0 used out of 0”. Opening the filter list by clicking on its title in uBlock shows that the list downloaded correctly.

I am using uBlock 0.9.5.2. This issue also exists in uBlock Origin 1.3.3 (attn. @gorhill).

**Comment by lewisje** [comment]
uBlock and uBlock Origin do not support the `$document` option in whitelist rules, and [this is by design](https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#not-supported); I realize I'm linking to the uBlock Origin docs, but I'm not sure chrisaljoudi could even figure out how to make uBlock support `$document` for whitelist rules, under the assumption he'd want to.

Every single filter in that list is a whitelist rule with the `$document` option, so it is dropped completely; maybe it would be better to just ignore the `document` part in the list of options, but that would greatly change the semantics of most `$document` based whitelist rules.
