### ISSUE TITLE
Fixed the Youtube ads problem

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#1575]
**Obs.: I didn't make a pull request because the existence of these values must have some purpose, so I'll just report how I fixed it.**

I was having problems with Youtube unskippable ads. Deleting this from the whitelist of uBlock fixed the issue:

```
behind-the-scene
chrome-extension-scheme
chrome-scheme
loopconversation.about-scheme
opera-scheme
```

Info to reproduce the error:
- Firefox 42.0
- uBlock (default lists)
- Disconnect
- HTTP-Everywhere
- Cryptocat
- OneTab
- I only had problems with videos longer than 1 hour

**Comment by lewisje** [comment]
All of those whitelisted schemes are there for a reason.

**Comment by Gitoffthelawn** [comment]
The big question is why would deleting those whitelist items have any effect?

**Comment by ghost** [comment]
I have no idea, but I can assure that doing this fixed the problem. I forgot to include in my post that I had previously cleaned and updated the caches, and restarted firefox, but none of these actions helped in any way.

What I didn't try to do is disabling and reenabling uBlock. Maybe there's something related to that with changing the whitelist?

**Comment by lcalabrese** [comment]
I'm pretty sure you're on to something here. Digging in the logger, it looks like a lot of Youtube's requests are originating from "blank.about-scheme"(!?) and were thus being allowed through.

Adding a dynamic block filter for doubleclick.net was also oddly doing nothing. I see a nice red rectangle, but then a curious "++" and not a single "-". Probably because the whitelist takes precedence over even dynamic filters.
