### ISSUE TITLE
Purify for OS X

### ISSUE THREAD

**Issue by asoksevil** [uBlock-LLC/uBlock#1581]
Considering that uBlock has been dropped around August, how´s Purify so far on OS X? @chrisaljoudi mentioned that once Purify is released, uBlock will no longer be supported but we are yet to see any developments of the OS X version.

uBlock Origin does not intent to have a Safari version so we are stuck to the current release of August or switch to another browser like Chrome or Firefox which do support uBlock Origin,

**Comment by ghost** [comment]
Some infos would be very interesting!

**Comment by MikhailTNY** [comment]
Lack of communication on this is what causing me not to even buy Purify for either iOS or OS X. What's the point of buying an app when the dev does not communicate to his current users. I'm going to look for a different solution.

**Comment by asoksevil** [comment]
Any news whatsoever?

**Comment by xdtnguyenx** [comment]
If you mean Purify for iOS, then I do have it for the Safari browser. The last update for Purify for iOS was in December 17, 2015 which included a background Site insight mechanism and a real-time chat option. I haven't used the real-chat option so I can't speak for that, however, the background site insight mechanism is used to prevent blank pages. From experience, it doesn't work too well and presumably "check for updates". 

If you are using Chrome or Firefox - based browser, uBlock Origin can't be beat. Frankly, I would like someone to take over this project or provide a good fork for the Safari version. In the future, I'll probably look into updating it for Safari, since there isn't a good ad-block option besides Adblock Plus.

**Comment by Temptin** [comment]
@xdtnguyenx Safari has deprecated the APIs that allow developers to hook into page loading to intercept the page contents and AJAX requests etc, and they can therefore shut them off at any time. When they shut them off, all old ad blocking extensions for Safari will quit working. That is why uBlock for Safari and AdBlock and Ghostery and everything else are living on borrowed time right now. Apple did this because they do not want 3rd parties to have access to snoop on all web traffic.

The solution is to write a certificate-signed extension which publishes a Content Blocker blocklist in Apple's format. The browser itself then takes care of blocking all matching elements/scripts/images. It is much faster than any extension ever was, but it's also a lot less powerful, so we'll see if content blockers step up.

Anyway, Chris can go fuck himself with the way he handled uBlock like a sleazebag and leeched donations without fixing any bugs or doing any maintenance. I will not be supporting him by buying any Purify for OS X. I also know that his blocklist isn't feasible in the long run since he edits it manually.

I will wait for Ghostery to use the Content Blocker format. I trust their skilled blocklist prowess and their corporate funding.

**Comment by publicarray** [comment]
See: http://forums.macrumors.com/threads/the-el-capitan-safari-9-content-blocker-thread.1924936/ and http://www.imore.com/here-are-ad-blocker-extensions-os-x-el-capitan .
Personally I use [Wipr](https://safari-extensions.apple.com/details/?id=com.giorgiocalderolla.wipr-desktop-4449XA862Y) in addition to uBlock.

**Comment by asoksevil** [comment]
Interesting read: https://www.reddit.com/r/ublock/comments/32mos6/ublock_vs_ublock_origin/cte0a3n

@chrisaljoudi certainly does not care bout this repo anymore.

**Comment by Hrxn** [comment]
Maybe still cares enough to remove your comment soon ;-)
And this one as well, probably.

**Comment by MacFlurry** [comment]
Any news?

**Comment by asoksevil** [comment]
You won't expect them unfortunately. This project is dead.
