### ISSUE TITLE
braking angular sites

### ISSUE THREAD

**Issue by shimondoodkin** [uBlock-LLC/uBlock#1585]
for example http://www.windward.eu/

uBlock v0.9.5.0

**Comment by joshvickerson** [comment]
This would be the result of a false positive with one of the filter lists enabled. It's not breaking all Angular sites - my website works: [joshvickerson.com](http://www.joshvickerson.com)

**Comment by shimondoodkin** [comment]
another one http://bootcamp.mit.edu/

**Comment by ghost** [comment]
https://forums.lanik.us/viewtopic.php?f=64&t=27798
Also: https://www.reddit.com/r/apple/comments/3q1vh5/purify_app_developer_attempts_to_remove_rival_app/cwbed6m

> I will be letting go of uBlock

**Comment by SW1FT** [comment]
IDK why the hell are people still using uBlock instead of uBlock Origin, LOL.

**Comment by lewisje** [comment]
It's like the wise sage Ron Popeil said, people like to "set it...and forget it."

**Comment by FredMatt** [comment]
I had the same issue on my site using google analytics.
The Problem is you are injecting a module that is not available due to uBlocks blocking. That leads to a module error which prevents your app from starting. 
I solved it, but for that i had to change the code of my app. 
I can show you my solution if you want, but it would be better if the team will fix the bug in uBlock :)
I don't know why uBlock does it that way, the sites doesn't crash if you use Ghostery (which still blocks google analytics..)

**Comment by ghost** [comment]
It's not a bug in uBlock. And nothing will get fixed in uBlock.

> I will be letting go of uBlock

It's due to a broad filter in EasyPrivacy. You need to report it for every site that's broken on the thread I linked. https://forums.lanik.us/viewtopic.php?f=64&t=27798
Or you change the code of your app which would be even better.

**Comment by harshanvn** [comment]
> but it would be better if the team will fix the bug in uBlock :)
> 
> I don't know why uBlock does it that way, the sites doesn't crash if you use Ghostery (which still blocks google analytics..)

This is an abandon ware. If you think if there is something to be fixed in the addon (`make sure it is not a filter list issue`). Then please switch to uBlock Origin instead (which is devloped and maintained by the original author of uBlock), unless you are on Safari. And see if its still an issue. Then try to report it here - https://github.com/gorhill/uBlock/issues

**Comment by ghost** [comment]
@harshanvn I already confirmed that it's not an issue with the add-on but with the filter lists.
