### ISSUE TITLE
Block Ads Inside Extensions

### ISSUE THREAD

**Issue by vortex250** [uBlock-LLC/uBlock#1592]
Trying to block ads inside a extension called "Chrono Download Manager"
Tried following this guide: https://github.com/chrisaljoudi/uBlock/issues/1137
But nothing seems to work.

Examples of ads and their networks are the following:
http://cdn1.eclkspbn.com/ext/onn/ctd/in_dow_160x600_en.gif
http://tags1.revdepo.com/adServe/
http://eclkmpbn.com/

**Comment by lewisje** [comment]
I'm not sure which platform you're on, but it might not be possible to block ad-requests made by extensions; try adding those domains to an ad-blocking HOSTS file, with lines like below:

```
0.0.0.0 eclkmpbn.com eclkspbn.com cdn1.eclkspbn.com revdepo.com tags1.revdepo.com
:: eclkmpbn.com eclkspbn.com cdn1.eclkspbn.com revdepo.com tags1.revdepo.com
```

The two lines are there because the upper line won't block requests made over IPv6 (:: is the equivalent of the zero-address 0.0.0.0, and ::1 is the localhost address), they have multiple hostnames per line because it's doable (up to nine per line works on Windows, which ignores any hostnames after the first nine, and more than nine per line makes OS X lag), and there are no explicit or implicit wildcards, which is why I blocked both the base domains and the specific subdomains.

Anyway, add both of those lines to the bottom of your HOSTS file; this link shows how to find and edit that file: http://www.howtogeek.com/howto/27350/beginner-geek-how-to-edit-your-hosts-file/
