### ISSUE TITLE
$domain=variety.com blocks requests to valid domains too

### ISSUE THREAD

**Issue by mariusa** [uBlock-LLC/uBlock#1599]
On this site
https://www.shoevariety.com/collections/shoes
2 scrips are blocked from loading, and they shouldn't be.

Here's the relevant log entry (the last 2)
-   @@||cdn.shopify.com^    script  https://cdn.shopify.com/s/files/1/1099/0742/t/4/assets/jquery.products.min.js?13462275826218498564
  -  |https://$domain=variety.com    script  https://ajax.aspnetcdn.com/ajax/jquery.templates/beta1/jquery.tmpl.min.js
  -  |https://$domain=variety.com    script  https://collection-filter-www.herokuapp.com/collection-filter-v1.js?shop=bulmen-footwear.myshopify.com

**Comment by lewisje** [comment]
It looks like the problem is that the parsing of the `$domain` option matches domains that contain the targeted domain, (like `variety.com` matching `shoevariety.com`); I wonder whether uBlock Origin also has this problem, and I think I'll look into the code to see whether they have this same issue.
