### ISSUE TITLE
Make uBlock undetectable, hide it from adblock detectors

### ISSUE THREAD

**Issue by slrslr** [uBlock-LLC/uBlock#1612]
Hello,

uBlock block various ads and such, but thanks to it there is a problem that sites instead shows an anoying messages warning me that im using adblocker.

How to hide these messages / make ublock undetectable?

**Comment by joshvickerson** [comment]
You can try going into the options and enabling the anti-adblock killer filter, though I've had mixed results with this. Sites that try to detect adblocking are getting smarter about it.

**Comment by lewisje** [comment]
There is no general solution, but I can say that ad-blockers don't announce their presence, and instead their presence is inferred by checking whether something that shouldn't be blocked or hidden actually is blocked or hidden.

Often, sites use pre-made "adblock-detection" scripts, and then it's possible to just block the scripts themselves, or individually whitelist certain scripts or elements that are used to test the presence of the ad-blocker.

**Comment by slrslr** [comment]
There seems to be usefull anti-adblock killer. It stops anti adblock scripts:
https://reek.github.io/anti-adblock-killer/#filterlist
Would probably get rid of many anti adblock notices and such.

**Comment by lewisje** [comment]
That UserScript is highly recommended, and it's chock-full of site- and plugin-specific workarounds.

**Comment by juanpide** [comment]
Yo can also try the extension ublock protect

**Comment by lewisje** [comment]
and for those who use either a blocker other than uBlock Origin, or a non-Chromium-based browser, there's the AAK-Cont UserScript: https://xuhaiyang1234.gitlab.io/AAK-Cont/

**Comment by CalicoCatalyst** [comment]
And you guys wonder why everyone charges for everything on the internet nowadays.

**Comment by nmaxcom** [comment]
@Insxnity I'd very much like the *option* to pay youtube and other providers a *reasonable fee* to get rid of "dumber than dumb" ads that only waste my time.

**Comment by lewisje** [comment]
For YouTube at least, I thought that's what YouTube Red is.

**Comment by nmaxcom** [comment]
According to CNET, it's only available in US, Australia, New Zealand, Korea and Mexico. Obviously, I don't live in any of those countries.

And that's only Youtube, so I'll keep using uBlock, thanks.

**Comment by juanpide** [comment]
There is a new extension called Nano Defender

**Comment by lewisje** [comment]
> Obviously

I had to click over to view your profile to learn that you didn't live in the US, and neither your English proficiency nor anything I remember you saying in these Issues hinted at that, so I presumed that you did, both because I do and because GitHub is based in the US.

Also, you did hint at a good point about ad-free subscription services generally: They tend to be per-provider and greatly add up.

**Comment by nmaxcom** [comment]
@lewisje I know you didn't know, we can't go checking where people are from. But the internet is a very big place, way bigger than the US, and US citizens are not the only ones paying and using ISPs to access the internet, having online businesses and whatnot. I never assume any country so I never have this issues.

You should [check out this article.](https://medium.com/@hoffa/github-top-countries-201608-13f642493773) which shows interesting facts, like the US not being (per capita) the ones using GitHub the most, or making more pushes etc. I'm surprised how Hungary and Estonia are dominating everyone else by far...

But I digress. I'll check out these anti-anti solutions 😄

**Comment by plato1123** [comment]
The infuriating thing is that pages appear to detect ublock origin EVEN WHEN I AM NOT BLOCKING ANYTHING.  I have nothing blocked by default and ublock shows 0 requests blocked and indeed pages show ads, but pages STILL DETECT I AM USING AN ADLBOCKER.  I try to have nothing blocked by default and only block ads if they are really annoying, but even this nice guy policy isn't allowed because somehow ublock still allows itself to be detected.  If truly nothing is being blocked why do so many sites detect an adblocker?  This seems like a pretty major flaw in ublock origin.  Very frustrating.

edit: Actually I see even though it says 0 requests blocked it is indeed still blocking ads.  I had put in a support requests asking how I could have adblocking off by default but apparently the solution they provided was false.  Why can't ublock allow ads to show by default, a sort of blacklist mode where everything is allowed unless I blacklist them?  Seems like a pretty obvious and logical use of this application but apparently the authors of this module are determined to destroy the internet by blocking everything by default.  Very lame.

**Comment by ghost** [comment]
This is not uBlock Origin repository.

**Comment by ghost** [comment]
https://old.reddit.com/r/uBlockOrigin/comments/7p7vws/even_when_i_green_a_site_to_not_block_ads_and/e037s86/

**Comment by plato1123** [comment]
Thank you so much for taking the time to clarify that!  I'll check it out.  Thanks again and best!

**Comment by ToxicMushroom** [comment]
@nmaxcom you can now pay for youtube xd
