### ISSUE TITLE
Can uBlock block this (random domain + base64 path)?

### ISSUE THREAD

**Issue by klesiczka** [uBlock-LLC/uBlock#1616]
I found interesting type of commercial not blocked by uBlock (0.9.5.0.1, default config) on Firefox.
It looks like: http//{random_subdomain}.domain.com/{base64_encoded_path}
Example:
//iwtjxgfu.wp.pl/Uk0vQm94LzIwMTYtMDUvbWlyZWsvMTAvbGl2aW5nXzAzLzk3MHgyMDAuanBn
after decoding:
//iwtjxgfu.wp.pl/RM/Box/2016-05/mirek/10/living_03/970x200.jpg
More examples you can check on http://www.wp.pl/

**Comment by lewisje** [comment]
This is a job for a regex filter:

```
/^http(?:s)\:\/\/\w{8}\.wp\.pl\/[\w\d]{32,}$/
```

It looks for a URL that starts in `http` (with optional `s`), followed by `://`, then 8 letters in a row (presuming the "random subdomain" consists of 8 letters specifically), then `.wp.pl/`, and finally a string of at least 32 letters or digits (picked to be longer than any normal word, to minimize false positives); this follows the same syntax as [regexes in Javascript](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions).

---

This works in all Adblock Plus style extensions, but I still recommend switching to uBlock Origin, because unlike this extension, it's actually still being maintained.
