### ISSUE TITLE
Settings in Hebrew language are displayed from ltr instead of rtl

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#165]
This one really messes the display of a translation if English is involved in the middle of the sentance and the dots are displayed at the beginning and more..

P.S: I am the Hebrew crowdin translator :)

**Comment by gorhill** [comment]
Best is for a developer who is familiar with both Hebrew and English could help me fix all this, as I am rather clueless as to what needs to be done. For instance I just tried to fix (well I am guessing it does not appear properly) the "{{used}} out of {{total}}", and I couldn't fix it despite forcing left-to-right style on the span object. So a contributing developer with experience in that area would be great.

**Comment by Mikey1993** [comment]
I have already a fix for  "{{used}} out of {{total}}" part.
Will be checking some more to be sure that I am not breaking anything in the way.

**Comment by Mikey1993** [comment]
Committed some changes to styles and css files.
Hope that my commit fixes not only Hebrew, after the merge :)

**Comment by gorhill** [comment]
**Thank you very much.** I just looked, and I can tell I would not have been able to fix this on my own.

I suppose the fix would have been a bit easier for you if I had created css files for each corresponding html ones instead of embedding the styles in the html code. I will do this eventually to make maintenance easier.

**Comment by Mikey1993** [comment]
Yeah, for example, I have needed to add an id for an element on the page just to make it work.
Also, it's wrong to embed the styles in the html file iteself (can't use for example the "__MSG_@@bidi..." in there, so I had also needed to delete some rules manually from the html file because it would break the css).

Better create a css file and import it for each html page as you have mentioned :)

**Comment by gorhill** [comment]
I created a css file for `3p-filters.html`. From there I took a screenshot of how it is supposed to look and I made some changes to get rid of `float`/`position`, as with these some of the formatting subtilities were lost. Also, after reading a bit I found a solution for when there is a trailing parenthesis in the list name. As far as I can tell, result complies with the screenshot I took.

**Comment by Mikey1993** [comment]
Hmm.. 
What do you mean by "formatting subtitles"? I didn't notice any breakage with my local tests..
Anyhow, I can see you have managed to solve this by not using floats. I have also learned something new in the process.

<b>kudos</b>!

**Comment by gorhill** [comment]
No breakage, I was just trying to bring back the slightly larger spacing between the header and the previous section as seen in this [screenshot](https://github.com/gorhill/uBlock/blob/master/doc/img/ss-chromium-1.png). It just wouldn't work, even entering ridiculously large margin values, and finally I realized it was the `float` causing the top margin value to be ignored.

**Comment by gorhill** [comment]
Just for the record, since moving the CSS block into it's own file kind of hide the changes, here they are as far as I can remember:
- got rid of `float` and `position`
- added `unicode-bidi: bidi-override` on the `.listDetails` selector
- added `unicode-bidi: embed` for  the `.listDetails > *` selector
- I modified the js code to ensure no grand-children for the the `.listDetails` selector (to ensure the rule above takes effect for the link to the remote domain)

**Comment by gorhill** [comment]
Just found out the `unicode-bidi: bidi-override` is not needed, no change if I remove it. So that's the `unicode-bidi: embed` doing the work.

**Comment by Mikey1993** [comment]
Nice finds!
Keep up with the good work :-)
