### ISSUE TITLE
Google Analytics filter too strict

### ISSUE THREAD

**Issue by Ahrengot** [uBlock-LLC/uBlock#1653]
I'm developing a WordPress plugin that has the word google-analytics in the plugin slug (I can't change this slug on WordPress.org) which means all the JS needed by the plugin is getting blocked by Ublock.

I guess the blocker is doing a regex match on `/google-analytics/` or something to that effect. Is there any way to change this so it specifically blocks the js files from GA instead? i.e. to explicitly block the js files, not just any file that has `google-analytics` as part of the filename.

I would love to patch this myself if you want some help. Just point me to the file(s) that are responsible for GA and I'll take a look :)

**Comment by meat-ball** [comment]
unfortunately this extension is no longer maintained/hasn't been updated since spring of 2015.

**Comment by anewuser** [comment]
This project is dead. Use uBlock Origin instead (it's developed by the original creator of uBlock): https://github.com/gorhill/uBlock , and report any filter problems to list maintainers instead of posting on the extension repository. You can use the logger to find the problematic list/filter: https://github.com/gorhill/uBlock/wiki/The-logger .

Please close this issue.

**Comment by Gitoffthelawn** [comment]
What it the plugin, and what does it do?
