### ISSUE TITLE
Block filter too strict

### ISSUE THREAD

**Issue by wumingdan** [uBlock-LLC/uBlock#1655]
It seems the blocker is doing a regex on pattern `/analytics\/js\//` to block all the javascript files fllow the path `analytics`.

I think this is too strict, my site (**none ads**) is using a path like `domain.com/analytics/js/*.js`, and these files are all blocked by uBlock.

Could you please make the block rule not so strict ?

**Comment by ghost** [comment]
> Latest commit a70a500  on 24 Aug 2015
- https://github.com/chrisaljoudi/uBlock
> Users should be aware that this add-on represents an older fork. The original developer of uBlock is continuing to actively develop the newer fork uBlock Origin.
- https://addons.mozilla.org/firefox/addon/ublock/

**Comment by nomaed** [comment]
I have a similar issue with our internal network application.

There's a bunch of JS content loading, and some of the modules have the word "analytics" in them because they are showing internal analytics related stuff.

However, with uBlock the application is completely broken because part of the AngularJS content that is required is being blocked.
