### ISSUE TITLE
Link in READ.md to Firefox add is out-dated

### ISSUE THREAD

**Issue by melroy89** [uBlock-LLC/uBlock#1686]
The link to the addons.mozilla.com webpage is oudated. You should point to the uBlock **Origin** version instead of only uBlock.

https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/

**Comment by anewuser** [comment]
The person you're trying to reach has abandoned this project in a shady way. See https://github.com/gorhill/uBlock/#beware-ublock-origin-is-completely-unrelated-to-the-web-site-ublockorg

I've even contacted Github to request them to at least hide/close this issues tab because people keep getting here by accident every week, but it was pointless.

**Comment by danger89** [comment]
Sorry to hear about that.

**Comment by melroy89** [comment]
Sorry to hear about that.
