### ISSUE TITLE
Add amplitude.com to whitelist for direct access

### ISSUE THREAD

**Issue by ryanashcraft** [uBlock-LLC/uBlock#1751]
Same issue as https://github.com/uBlockAdmin/uBlock/issues/463, except for amplitude.com. Peter Lowe's list outright blocks amplitude.com, so directly accessing that site fails to load the CSS and related media.

Proposed solution: add a whitelist rule to allow direct first-party access to amplitude.com, just like was done for mixpanel.com.

Site affected: https://amplitude.com and https://analytics.amplitude.com (for the logged in experience).
Environment: Chrome with uBlock v0.9.5.3 on Mac OS

Screenshot of site today with ublock's default settings:
![screen shot 2018-03-28 at 11 26 44 am](https://user-images.githubusercontent.com/523675/38048703-efaf6fbe-327a-11e8-99d2-532cac7e312a.png)

**Comment by amywtlin** [comment]
the same issue also happens to fullstory.com - not sure if this should be a separate issue yet so I think I'll leave it here first

**Comment by krystian3w** [comment]
Peter Lowe ask why block fullstory.com / amplitude.com

**Comment by iam-py-test** [comment]
Why would anyone need to visit that website?

**Comment by spirillen** [comment]
> Why would anyone need to visit that website?

hmm

1. they are from within the US
2. they simply don't care about other...

**Comment by iam-py-test** [comment]
> 
> 
> > Why would anyone need to visit that website?
> 
> hmm
> 
>     1. they are from within the US
> 
>     2. they simply don't care about other...

If people need to visit this spyware website, they can simply use uBlock Origin and disable the privacy list
@ryanashcraft there is another simple solution; don't use that website.

**Comment by paladin8** [comment]
Hi @iam-py-test, I understand the sentiment here and agree that uBlock should block client-side tracking to api*.amplitude.com. That said, we do have a paying customer base who regularly visit amplitude.com and analytics.amplitude.com and, more recently, public investors trying to reach investors.amplitude.com who are getting surprised by this rule. If there's anything we can do to whitelist these domains in order to allow people who are directly trying to get to Amplitude information to do so, that would be appreciated.

**Comment by iam-py-test** [comment]
> 
> 
> Hi @iam-py-test, I understand the sentiment here and agree that uBlock should block client-side tracking to api*.amplitude.com. That said, we do have a paying customer base who regularly visit amplitude.com and analytics.amplitude.com and, more recently, public investors trying to reach investors.amplitude.com who are getting surprised by this rule. If there's anything we can do to whitelist these domains in order to allow people who are directly trying to get to Amplitude information to do so, that would be appreciated.

1. This is not uBlock Origin

I probably already mentioned that, but I figured I would mention it again. The uBlock Origin is at https://github.com/gorhill/ublock. This is an unmaintained scam. It doesn't matter if your problem is legit or not, @uBlockAdmin would not fix it anyway. Please see my comment on #1840 

2. It doesn't matter why I want or think.

I could not allowlist your domains even if I wanted to. You will have to report it to https://github.com/ublockorigin/uassets, however, I doubt it would be allowlisted, as per the new polity from https://github.com/uBlockOrigin/uAssets/pull/10149#issuecomment-951814995.

3. It is _very easy_ to bypass strict-blocking and continue, and only slightly harder to disable uBlock Origin on that website. 

> we do have a paying customer base who regularly visit amplitude.com and analytics.amplitude.com

What I don't understand is why people want their privacy protected, but do not want to protect the privacy of others 🤷 

Again, it doesn't matter what I think, as I do not have commit-access to the uBlock Origin or Easylist rules. 

Edit: it was already rejected in https://github.com/uBlockOrigin/uAssets/issues/10388
