### ISSUE TITLE
uBlock Origin

### ISSUE THREAD

**Issue by yukulele** [uBlock-LLC/uBlock#1762]
hi,
What is the difference with uBlock Origin?

**Comment by krystian3w** [comment]
This is continuation "`uBlockAdmin/uBlock`" / "`chrisaljoudi/uBlock`" without 2 years gap.

Any new function find in relases: [https://github.com/gorhill/uBlock/releases?after=**0.9.6.0**](https://github.com/gorhill/uBlock/releases?after=0.9.6.0)

**Comment by krystian3w** [comment]
This is continuation "`uBlockAdmin/uBlock`" / "`chrisaljoudi/uBlock`" without 2 years gap.

Any new function find in releases: 

[https://github.com/gorhill/uBlock/releases?after=**0.9.6.0**](https://github.com/gorhill/uBlock/releases?after=0.9.6.0) <sup> (click <sup><kbd>Previous</kbd></sup> button to see newest versions (9.6.0+))</sup>



---

<div align="right">

_(`gorhill/uBlock` :arrows_counterclockwise:  `uBlock Origin`)_

</div>

**Comment by ibakirov** [comment]
@yukulele 
Take look at https://en.wikipedia.org/wiki/UBlock_Origin to get difference and compare development cycle (commits) of both project

**Comment by Terrabits** [comment]
@krystian3w According to the Chrome Web Store, the lastest release of `gorhill/uBlock` (uBlock Origin) is 1.16.4 available as of May 5, 2018. This is very recent.

[https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm)

**Comment by krystian3w** [comment]
Wtf...

¿Everybody reproach typo? <sup>(added cutted "`0.`")</sup>

---

**FIND CHANGES IN RELASES ≠ LATEST VERSION**

**Comment by yukulele** [comment]
so which one should I use?

**Comment by Terrabits** [comment]
@yukulele It's up to you.

I ended up choosing uBlock Origin based on Github activity. Contributions to -Origin and -Admin are primarily from the owners (`gorhill` and `uBlockAdmin`, respectively). Both projects have been around since at least 2016. Here is a comparison of commit activity from 2017 until today:

![gorhill 2017 commits](https://user-images.githubusercontent.com/1532047/39951035-01c29018-553b-11e8-8d9d-7651638de76e.png)

![ublockadmin 2017 commits](https://user-images.githubusercontent.com/1532047/39951038-0a811198-553b-11e8-8a84-9e9f8dfe98f4.png)

It looks like -Origin is more consistent in contributions from the author over time, presumably with bug fixes at the very least. -Admin has made large changes recently, but not consistently.

That said, I didn't compare features. I am interested in simple ad blocking, so I'm assuming either one will do.
