### ISSUE TITLE
Not block ads yandex direct 

### ISSUE THREAD

**Issue by alexsanfr** [uBlock-LLC/uBlock#1763]
Not block ads yandex direct 
Screen: https://ibb.co/noazBx

**Comment by hugoncosta** [comment]
Try going to the settings and activating the country specific filters, there are 2 russian ones that block Yandex's ads for me. https://i.imgur.com/eG2EBGw.png

**Comment by alexsanfr** [comment]
Yes ,two russian filter activate

**Comment by hugoncosta** [comment]
That's odd, it works here perfectly. You can try to choose the elements by hand (I don't know if this work on mobile though): https://i.imgur.com/0WC0Afl.png. Also, try clearing the cache on the Russian filters, fresh the files, since Yandex is most certainly changing their design to circunvent these filters.

**Comment by alexsanfr** [comment]
Yandex.ru setting ads off ads
https://ibb.co/h6vt8c
No ads 
Clear cash yes ads

**Comment by hugoncosta** [comment]
That's odd, idk then, wait for the list to be updated, this isn't a problem related to uBlock

**Comment by alexsanfr** [comment]
Specific problem yandex browser ads

**Comment by Menelion** [comment]
Chrome 72.0.3626.121, Windows 10 latest non-insider build. The ads from yandex.direct are not blocked, at least on some sites (see ideer.ru, for example). Any thoughts or suggestions are highly appreciated.  
And as I'm a screen reader user, could you please give instructions in plain text, not images, if possible? 
 
Thanks!
