### ISSUE TITLE
Remove "No sneaky tracking" from ublock.org

### ISSUE THREAD

**Issue by CamilleScholtz** [uBlock-LLC/uBlock#1768]
Hi Chris Aljoudi,

Please remove the "No sneaky tracking" bullet point from ublock.org, because ublock now does sneaky tracking: https://github.com/uBlockAdmin/uBlock/commit/76b89c0a22d20f3a66d7feab14e024f56ca65539

**Comment by pastly** [comment]
Before getting all up in arms about that commit, consider

- the usefulness of knowing what environments your code is running in so you can prioritize features and bug fixes based on number of affected users
- how you know the collected information isn't properly anonymized
- how you know it's being used for more than simple useful analytics
- how you would obtain this information in a safer way
- how well an opt-in (AKA: disabled by default) option to allow analytics actually manages to represent a user base

There's easy and obvious reasons for every piece of information collected. Even the user ID can be explained as (most likely) a way for the backend to correlate pings from a single installation  in order to determine blocking performance over time.

Not all software you use is out to get you. Not all analytics are bad.

\- Someone who doesn't even use uBlock, but just hates seeing waves of rage

**Comment by okiehsch** [comment]
@pastly I think the  "sneaky" part is what gets some people "all up in arms".

Consider the release page https://github.com/uBlockAdmin/uBlock/releases, he documented the last changes in uBlock 0.9.5.3 marked as a `Pre-release`.
He then added the tracking code and **released** uBlock 0.9.5.5 to the chrome webstore without any release notes, there is not even a mention of  0.9.5.5 at https://github.com/uBlockAdmin/uBlock/releases

I would certainly call that "sneaky".

**Comment by CamilleScholtz** [comment]
@pastly There hasn't been a relevant commit for a few years now, the only commits being either cosmetic, adding more begging/donation pages, and now a tracking feature, why would this "knowing" of the environment be needed? Firefox and chrome both release this kind of information even.

**Comment by Tharn** [comment]
Exactly. Telemetry for troubleshooting requires first of all active development and an *interest* in bugfixing, maintenance or feature expansion. Considering the history of the µBlock takeover and the activity in the years since then, what would you think this data gathering is used for? Let's connect the dots, shall we?
