### ISSUE TITLE
Albertsons.com video content blocked by uBlock

### ISSUE THREAD

**Issue by SyedSan1** [uBlock-LLC/uBlock#1843]
We provide a video technology platform for partners to embed instagra/ tiktok like videos on their website.
Albertsons  recently shared that their video is getting blocked by uBlock.

Note, we don't put outside advertisements. We provide technology that the customers can use to put their product videos which is what happens in 90%+ cases. Occasionally, a customer may decide to insert ads.

We recently worked with the AdGuard team to get this issue resolved here by allowing filters to pass our content CDNs.
https://github.com/AdguardTeam/AdguardFilters/issues/111021

Similarly, we worked with uBlockOrigin team to get the issue resolved here
https://github.com/uBlockOrigin/uAssets/issues/12153

We'd appreciate a similar resolution on this. Thank you.

**Comment by SyedSan1** [comment]
@uBlockAdmin  - could you please help?
Basically, need help with getting our video content unblocked.
Our domains are: fireworkapi.com, fireworkapi1.com, fireworktv.com, fwcdn2, fwcdn3, fwpub1
You can block fireworkads because that's where ads will come from whenever a publisher wants.

**Comment by iam-py-test** [comment]
@SyedSan1 this repo is unmaintained; don't expect a response. See https://github.com/uBlock-LLC/uBlock/issues/1838
The @uBlockAdmin account [hasn't been active](https://github.com/uBlockAdmin) [since 2019](https://github.com/uBlockAdmin?tab=overview&from=2019-12-01&to=2019-12-31)
If any of your customers have 'uBlock' installed, tell them it's malware and should be remove.
