### ISSUE TITLE
Use standard style for settings page

### ISSUE THREAD

**Issue by LeoColomb** [uBlock-LLC/uBlock#197]
Hi, great ad blocker! :smile:

I think use a bootstraped style for setting page should help to make it a bit more readable. 
Of course the best is [roykolak/chrome-bootstrap](https://github.com/roykolak/chrome-bootstrap):
- it's really easy to implement (your current HTML template may be already compatible, just some class changes) 
- it's pretty good for coherence

**Comment by kurtextrem** [comment]
:+1: 
I could do this if you don't have time @gorhill

**Comment by ialexsilva** [comment]
:cool: 
see demo https://github.com/roykolak/chrome-bootstrap

**Comment by kurtextrem** [comment]
https://chromium.googlesource.com/chromium/src/+/09a7e00df7e8316a01cda0288577a293d7d126a3 new keys for options @gorhill

**Comment by Baegus** [comment]
The only thing I don't like about the settings page is probably the fact that the "Apply changes" button isn't very noticable at first.

**Comment by gorhill** [comment]
@kurtextrem Thanks for the link.

@Baegus It used to be worst, as the button was always pinned at the top, default appearance -- did not stand out much. If a user scrolled down to select a filter list, he/she wouldn't know _"Apply changes"_ needed to be clicked. So the solution was to make it float on the page. The float behavior led to have the button moved to the right (or left of RTL text) so that it's not rendered over the filter lists. Then I added color to make it stand out more, and I increased the size. I don't know what else I can do.

**Comment by kurtextrem** [comment]
@gorhill https://chromium.googlesource.com/chromium/src/+/939816fbde192746649ae233b98db6a81a603613

**Comment by roykolak** [comment]
Hey everyone, I'm still trying to understand the usage and look of `options_ui` I've seen it as a separate page and as a modal in the google doc write up

I would love this idea tho, I think it would automate much work. I see the addition in the manifest in the link that @kurtextrem posted, but am confused as to how to specify the options in the `options_ui`. Assuming it runs off of a json config?

**Comment by kurtextrem** [comment]
I understand the `options_ui` as it's like the normal option page, with some "additional features", such:
- Embedded in the extensions overview page
- Chrome settings "style"

`options_page` will continue to act like now. `options_ui` will be the new (inline) options page.
I can imagine the options_ui page is just a normal options page without (custom) styling. Someone could test it as well.

(See https://chromium.googlesource.com/chromium/src/+/09a7e00df7e8316a01cda0288577a293d7d126a3 again)

**Comment by roykolak** [comment]
ah cool, understand now

**Comment by kurtextrem** [comment]
https://chromium.googlesource.com/chromium/src.git/+/8b1744726bc40f866df4c96293e472551c918600

**Comment by LeoColomb** [comment]
https://developer.chrome.com/extensions/optionsV2

**Comment by my-password-is-password** [comment]
I enabled "Enable embedded extension options" in `chrome://flags/#enable-embedded-extension-options` and on the dev build this is what it looks like.

![ubnewoptionui](https://cloud.githubusercontent.com/assets/6408935/4871638/13c9a578-61c2-11e4-886c-7472c6bef716.png)

Is it really going to be that narrow popup window?  Or is it like that because the options page isn't made for the new options_ui? Either way I think it sucks.

**Comment by kurtextrem** [comment]
It is definitely not made for the new options_ui. But yes, it will be that narrow. One of the links I've posted contains a designer doc which shows examples.

**Comment by gorhill** [comment]
I don't see how uBlock or uMatrix (or a lot of other extensions for that matter) can fit their UI in such a small box. My understanding was that this was optional though recommended way of doing it, but reading the doc again, it will become mandatory.

I guess the solution would be to simply show a link to the dashboard in that small UI popup.

**Comment by LeoColomb** [comment]
@gorhill 
See https://developer.chrome.com/extensions/optionsV2#sizing

**Comment by gorhill** [comment]
@LeoColomb 
Of course I read that part. It's HTML, the browser rendering engine knows the optimal size required to avoid scrollbars etc., there is no way one can know the size in advance with a UI which go further than a couple of buttons/radios/checkboxes.

In any case, the screenshot above shows that contrary to the doc, the "embedded dialogue" does **not** "automatically determine its own size based on the options page content".

**Comment by LeoColomb** [comment]
You're right :smiley:

**Comment by kurtextrem** [comment]
Can't exactly say why, but rightclick -> options on the uBlock toolbar icon now opens chrome://extensions and looks like this: http://prntscr.com/63ital. Clicking on "Einstellungen" opens the right page, but still wanted to report. Could be either because of the latest dev version or since the 0.8.7.0 update... or both together (new version, extension update = displays options in page)

**Comment by gorhill** [comment]
I don't plan more work on this, I consider what we have to be all fine.

**Comment by LeoColomb** [comment]
Hmm, well, just to be sure: my initial issue was to the style (which still the same), not specific to the Chrome's new options popup, right?

**Comment by gorhill** [comment]
I don't see an issue with the current style. It's the same for all browser versions which I prefer this way than have a different style on each browser.
