### ISSUE TITLE
Opera extension is not updated

### ISSUE THREAD

**Issue by SW1FT** [uBlock-LLC/uBlock#199]
Opera extension version is at 0.5.1.0 whereas other browsers like Google Chrome are at 0.5.3.0.

**Comment by gorhill** [comment]
I have to be more careful when I update for Opera store, as it may take a few days to be updated. That would be terrible if I introduce a serious bug, as there would be no way to provide an emergency fix. 

For Chrome store, it takes one hour to have a new version, so I can fix faster if such a bug occurred. Sometimes, depending on the changes, I prefer to wait to see what happen with the version in Chrome store, and when I am confident the version in Chrome store is a good one, I submit to Opera store.

I was planning to release one for the Opera store today. In anycase, we will have to accept that the version in the Opera store lags the one in Chrome store, due to how the stores differ in how long it take for upgrade approval.

**Comment by SW1FT** [comment]
So, should we download the Chrome extension for faster updates or would it bring any incompatibility?

**Comment by gorhill** [comment]
> or would it bring any incompatibility

No clue. My advice would be if you really want the latest version, download from Github. You lose auto-update of the extension code though (not the auto-update of the lists), but to some users this is even a good feature because you can roll back if ever you don't like the most recent version.

**Comment by iandol** [comment]
There is currently a bug in Opera (or more accurately between Opera's update request and the Chrome store) so chrome extensions (which I install using the excellent githubbed [crxviewer](https://github.com/Rob--W/crxviewer)) don't currently auto-update. Until this is fixed I also recommend using the manual install route; if yo do a git clone then you can use terminal/shell to automate git pulls (every hour / day etc)...
