### ISSUE TITLE
Add Clear Button

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#216]
See screenshot
![capturar](https://cloud.githubusercontent.com/assets/6363160/4175170/98d9016c-35c3-11e4-9d80-85ace351673c.PNG)
on whitelist too...

**Comment by gorhill** [comment]
To remove all custom data is quite a drastic operation. I rather have the user explicitly select and delete that data (which can be undone immediately) rather than have an easy to click button. It's more difficult to select all/delete through absentmindedness than clicking that clear button by mistake.

**Comment by ialexsilva** [comment]
Your idea seems to be better...
About "clicking on clear button by mistake" This can be bypassed by adding a confirmation box :D

**Comment by gorhill** [comment]
Select all, then <kbd>Delete</kbd> or <kbd>Backspace</kbd>, then _"Salvar e aplicar"_.
