### ISSUE TITLE
Add 'purge all caches' option for filter lists

### ISSUE THREAD

**Issue by Landpaddle** [uBlock-LLC/uBlock#219]
Currently, I have to click all 'purge cache' buttons individually to accomplish this. For those who like to manually update their lists often, an option to purge all caches (perhaps next to Update now) would be appreciated.

Thank you for all the hard work and attention to performance gorhill!

**Comment by ialexsilva** [comment]
:+1: +1

**Comment by Zylinder** [comment]
Hi,
uBlock 0.8.6.0 on Firefox 35.0.1
I'm commenting on this post because my question is related to Purge all caches in uBlock -> Dashboard -> 3rd-party filters.

I opted for manual filter lists' update, that is Auto-update is unchecked.
I'd wish to now the pertinence of purging all caches before updating filter lists. I noticed that sometimes I have to (_Update now_, greyished, requires it) and other times I have the choice (_Update now_ not greyished).

I assume the logic is that if I update the filter lists without purging first, the updated lists are added to existing ones and any removed filters from the sources are not removed from my database. Is this correct? If so, I'd have to purge systematically before updating to assure a mirror setting  of all my filters...

Thanks
