### ISSUE TITLE
µBlock 0.7.0.0-rc.0 and HTTPSB (not an issue)

### ISSUE THREAD

**Issue by puff-m-d** [uBlock-LLC/uBlock#277]
Hello,

I have a question about the µBlock 0.7.0.0-rc.0 and the added "dynamic filtering". If I use both µBlock and HTTPSB, will I gain anything from using the "dynamic filtering" in µBlock? I am assuming that I will not but want to ask the question just to verify that I understand it correctly. I am assuming that I would just leave the "dynamic filtering" set to default (not use it) since I also use HTTPSB. Am I correct in this assumption? Or are there benefits to also using the "dynamic filtering" along with using HTTPSB?

**Comment by gorhill** [comment]
The only benefit of uBlock over HTTPSB is that when uBlock blocks an `<iframe>` it can remove it from the page as well when _"Hide placeholders of blocked elements"_ is checked.

Other than that, I introduced this feature because some users just want to be able to minimally control these two type of requests on a 1st/3rd-party basis without the full blown level of details of HTTPSB.

If using uBlock to block inline script tags, this could prevent HTTPSB from blocking inline script tags. So for inline script tags, this has to be one or the other.

**Comment by puff-m-d** [comment]
Thanks for your excellent explanation. I consider both uBlock and HTTPSB must haves, so I definitely like to know the best way to use them together. Since I am one of those that likes the "full blown level of details of HTTPSB", it seems best in my case not to use the uBlock dynamic filtering.

Thanks again for your reply and for your excellent extensions (I also look forward for when you are able to get back to developing uMatrix)...

Best regards...

**Comment by ghost** [comment]
"Select all iframes and scripts" button would be great inside of uBlock toolbar button.

**Comment by gorhill** [comment]
There is a logic error in the handling of exceptions (dark gray), need to fix.

**Comment by gorhill** [comment]
@6black6ninja6: What do you call "uBlock toolbar button"? You mean in the popup?

**Comment by ghost** [comment]
Yup.
