### ISSUE TITLE
Incorrect number of blocked ads on gospelherald.com

### ISSUE THREAD

**Issue by trietbui85** [uBlock-LLC/uBlock#318]
I try to open an article on gospelherald.com/ (http://www.gospelherald.com/articles/52872/20141013/october-google-event-expected-to-announce-release-of-nexus-x-6-and-nexus-9-tablet.htm) and realize number of blocked ads continue increasing, from 1 to 5, to 10,..., then 562.

Is it any wrong there? I don't believe there are so many ads on this page.

**Comment by gorhill** [comment]
It stops at 35 on my side, using default filter lists.
- What version of Chromium (or derivative)?
- What filter lists you have enabled?

As an aside and to reiterate, uBlock blocks more than just ads, and actually more than often it will end up blocking less ads on a single page than other stuff like trackers/data miners et al. For example, at [this page](http://ici.radio-canada.ca/), the counter keep going up and up, not because of ads, but because of the obnoxious attempt at tracking/data-mining.

**Comment by ghost** [comment]
35 here also.

**Comment by trietbui85** [comment]
I'm using Chrome Version 37.0.2062.124 m on Windows 7.

This morning I try to load that page again and see there are 33 ads blocked. Try again, then there are 25. Try reload again, is 39.

Currently my Ads setting has EasyList‎ (adblockplus.org), Peter Lowe’s Ad server list‎ (yoyo.org) and VIE: Fanboy's Vietnamese‎ (www.fanboy.co.nz/fanboy-vietnam.txt) enable.

**Comment by gorhill** [comment]
The only places where the network request count is incremented is when [chrome webRequest API's onBeforeRequest() is called](https://github.com/gorhill/uBlock/blob/master/js/traffic.js#L118), and when inline scripts are blocked through dynamic filtering. There is no other place in the code.

So essentially this means that there were really net requests matching the block count -- there is no other way for the count to go up. If it happens again, I suggest you open the dev console of the web page where it happens (Ctrl-Shift-i) and take note of the blocked connection error messages to find out what URL is blocked.

**Comment by gorhill** [comment]
I have been trying to repro without success. I was thinking... What other extensions do you have installed?

**Comment by trietbui85** [comment]
Well, this morning I force update uBlocker update all its 3rd-party filter, then try to reload gospelherald.com again, and see there are 32 ads blocked. Till now I cannot reproduce to have 562 ad blocked as before. I think this issue might be already fixed.

**Comment by ghost** [comment]
I see count increasing by 1 on this page: https://github.com/gorhill/uBlock/issues by clicking on an issue, then back button, the clicking on an issue again.
With firefox 35.0.1 and uBlock 062afe4ad86c0614abf53ae84590aea67964a0a3
But I guess that makes sense because it's treating the page as one contiguous page with 3rd party requests happening with each click, due to its scripts. 
For example it doesn't happen when clicking multiple times on `Explore` at top of this page https://github.com/explore  but it does happen when doing it on `All` (or `Showcases`). 

What I was trying to find out is why, the counter is always `0 or 0%` when holding uBlock's popup open and clicking its refresh button, after having changed something in that matrix (`I am an advanced user` option must be active to see matrix). Reopening it shows the correct number though.

after having clicked the big refresh button(in uBlock's popup):
![afterrefresh](https://cloud.githubusercontent.com/assets/5661825/6311616/ad732dde-b965-11e4-9670-a322e5d5b152.png)

after closing and reopening the popup:
![cloreopened](https://cloud.githubusercontent.com/assets/5661825/6311617/b3add2d0-b965-11e4-8891-d64af4023f21.png)

The icon counter (of 1) is updated successfully though.
