### ISSUE TITLE
Problem with allowed filters in Filtros Nauscopicos

### ISSUE THREAD

**Issue by eduardoeae** [uBlock-LLC/uBlock#320]
This filters have some allow rules that shouldn't be there. They conflict with EasyPrivacy and others.
Examples:
 @@.bbci.co.uk/*/analytics.js
 @@||ssl.google-analytics.com^
 @@bbc.co.uk (this one allows (statistics|sa).bbc.co.uk that are blocked by other lists)

This are some I find often, there could be more conflicting filters.

**Comment by gorhill** [comment]
I can't set myself as a secondary maintainer of lists -- just do not have the time, which I rather spend coding.

One thing is to try and ask the author to modify the list so that it doesn't interfere with other lists.

If that doesn't work, then I think the best approach is for someone to fork the list, and have some kind of script to automatically import changes to the lists while removing undesirable entries, while renaming the list something like "Filtros Nauscopicos (enhanced)" or something. I will happily replace the original list with the enhanced one.

**Comment by gorhill** [comment]
Lists maintainers will have to take care of the problem in their own lists. I just don't have the time to override everybody else's bad entries in remote filter lists. Because I am nice, I do it once in a while for the ones which are selected out of the box in uBlock, but for others this will need to be taken care of by their own maintainers.
