### ISSUE TITLE
Adguard blocks more ads than uBlock (Myth)

### ISSUE THREAD

**Issue by ghost** [uBlock-LLC/uBlock#330]
As this post indicates, though there's no evidence about that.

http://www.nsaneforums.com/topic/231981-recommended-adblocker/#entry853397

I think this myth is busted.

**Comment by gorhill** [comment]
The only such statements which can be taken seriously are those which are supported by detailed benchmarks (detailed as in reproducible by others). So far I am aware of only two sources of benchmarks about blocking power, [Ghostery](http://www.areweprivateyet.com/), and [here of course](https://github.com/gorhill/uBlock/wiki/%C2%B5Block-and-others:-Blocking-ads,-trackers,-malwares) (because I don't like to develop in blind mode, which is what happens without benchmarks).

Once rigorous benchmarks are available, then debate can occur on whether the methodology is sound enough, etc.

Also saying that uBlock is "in dev stage" doesn't make much sense: all such extensions are in dev stage. The issue is more whether an extension is mature and stable enough, and this has been the case for uBlock since a while now.

I won't bother answering the post in nsaneforums.com , but let this answer serves as reference for all such unsupported statements.

**Comment by ghost** [comment]
I agree 100%, like I said in post 1, this is totally busted.
