### ISSUE TITLE
Element picker overlay on yahoo.com

### ISSUE THREAD

**Issue by pwstokes225** [uBlock-LLC/uBlock#344]
The overlay does not appear to cover the top of the page where the logo and search box are located.

This seems to occur specifically on https://au.yahoo.com/, https://hk.yahoo.com/ and https://nz.yahoo.com/.

**Comment by gorhill** [comment]
I will note my observation here before I forget:
- The `body` has a top margin of 89px. Since the element picker installs itself as a child of the `body`, it is being pushed down by that margin. Solution: set the `svg` element `position` to `fixed`.
- The `offsetTop` of the `body` is 0, meaning the mouse pointer mapping is offset. Solution: query the client bounding rect for the `body` element and offset according the `top` value (this may also solve other mapping issues reported somewhere else).

**Comment by Deathamns** [comment]
@gorhill Just for the record, I've made some changes to the element picker in my ports branch, and unintentionally fixed these issues. If you don't want to bother...

**Comment by gorhill** [comment]
@Deathamns Are you referring to the use of `Element.getBoundingClientRect()` rather than `offset[Something]`?

**Comment by Deathamns** [comment]
That probably solved the offset issue, the top margin for the body is fixed by adding the pickerRoot to the documentElement instead of the body element.

**Comment by gorhill** [comment]
@Deathamns Your fix works very well.
