### ISSUE TITLE
Feature: Add auto reload page feature

### ISSUE THREAD

**Issue by ialexsilva** [uBlock-LLC/uBlock#354]
Would like an option to "uBlock" auto reload the site when enable/disable the power button etc...

**Comment by Mikey1993** [comment]
Maybe a small reload icon below the power button will do the trick,
but ultimately, I think this feature won't be used a lot.

Anyway, +1 from me, as it is a "nice to have" thing.

**Comment by gorhill** [comment]
I made the decision a long time ago to not force reload, because the worst-case scenario is with a force-reload: a user loses whatever changes he made in a form or something like that.

As a counter-argument, it will probably be suggested to create yet-another setting to let the user chose whether to auto-force-reload or not, but this is stretching it. A user will undoubtedly faces at some point a scenario where a force-reload is **not** what he wants, and then this will suck big-time when it ends up force-reloading.

Just letting the user refresh whenever is best option. Inconvenient at most to some --- it's just F5, come on... -- but less worst than having a user lose all is input on a page. Whitelisting/de-whitelisting is not something which is done all the time, so a non-issue imo.

**Comment by kurtextrem** [comment]
I have to say I was annoyed by the auto refresh. I'd say a "Reload the page to reflect the changes"-tooltip would be sufficient.

**Comment by PatTheMav** [comment]
I'd go out on a limp here and assume that the request stems more from a point of "the other adblockers are doing it" than a usability need.

I'm with @gorhill that the current implementation breaks nothing about the current page context and doesn't assume any specific use case, while the automatic reload would assume that the user wants that reload (and that's always a chance for an error of judgement on the developer's part).
