### ISSUE TITLE
Massive blocked iframe on some facebook sites

### ISSUE THREAD

**Issue by semenko** [uBlock-LLC/uBlock#36]
Perhaps this is what's meant by the disclaimer for the anti-facebook list, but a number of sites that use <iframe> to embed facebook content end up with huge blocked icons (the iframe height & width are 1000px ea):

e.g. http://www.monoprice.com/Product?c_id=104&cp_id=10401&cs_id=1040115&p_id=9436&seq=1&format=2

I figured "Hide placeholders of blocked elements" would hide that enormous iframe, but it doesn't.

![blocked](https://cloud.githubusercontent.com/assets/167135/3448367/36d13c5e-0158-11e4-898f-72f12b7c1e9f.png)

**Comment by gorhill** [comment]
To me it looks like Fanboy is missing a filter to go with the other Facebook filters. Can you try: `||connect.facebook.net/*/all.js^$third-party`?

Looks like I will need a project list to fix Fanboy's annoyance and Fanboy Anti-Facebook until (and if) they add the missing filter.

Other way to address this would be to also listen to attribute changes in the mutation observer, but this is something I am trying to avoid (overhead etc.) So I see the above filter as logically missing in the relevant filter list.

Edit: updated to use a `*` in lieu of `en_US`.

**Comment by semenko** [comment]
Ah nice, that does the trick.

**Comment by gorhill** [comment]
Just for the record, I don't think ABP would have suffered the same problem, because it listens to _all_ load events, while uBlock listens only to the ones from elements which have not have their `src` property set (that could be a problem in certain cases, but I want to try the lower overhead angle first). Either ways, using above filter is the right thing to do, as otherwise users are still hitting 3rd-party Facebook server.

**Comment by gorhill** [comment]
Submitted suggested fix to [Fanboy's forum](http://forums.lanik.us/viewtopic.php?f=62&t=17309).

**Comment by semenko** [comment]
Awesome -- thanks again.

I love the focus on keeping uBlock's overhead incredibly low. I get the sense a lot of people avoid ABP & similar extensions due to CPU overhead on thin-ish clients like Chromeboxes (It's an ongoing problem we face with HTTPS Everywhere).

**Comment by gorhill** [comment]
Answer from fanboy:

> Would break facebook comments; add the Anti-Facebook sub from https://www.fanboy.co.nz if you don't mind blocking facebook comments.

Enabling Fanboy Anti-Facebook didn't work. Yet I see this filter in the list: `||connect.facebook.net^$third-party,domain=~facebook.com`, which means it should be blocked. Investigating.

**Comment by gorhill** [comment]
Interesting, this issue allowed to uncover a nasty bug which affected filters using the `~example.com` filter option. Once this bug is fixed, the suggestion from Fanboy will work, or else the other workaround of using the custom filter `||connect.facebook.net/*/all.js^$third-party`. I will open issue for the uncovered filter bug though, it deserves its own issue.

**Comment by gorhill** [comment]
Fixed in [0.2.3.2](https://github.com/gorhill/uBlock/releases/tag/0.2.3.2).
