### ISSUE TITLE
[Feature Request] Per Filter Whitelisting/Blacklisting

### ISSUE THREAD

**Issue by Skibicki** [uBlock-LLC/uBlock#361]
Usually, I keep Easylist disabled but use privacy and malware lists. I would like to use privacy/malware lists globally and enable/disable Easylist for specific sites or pages.

**Comment by gorhill** [comment]
Ads are privacy invading by design, so caring about privacy while allowing ads which typically pull resources from 3rd-party servers is sort of contradictory.

**Comment by Snapy** [comment]
@gorhill  I agree with you but @Skibicki did not use a good example. Sometimes when browsing you want/need to unblock a specific page/site because a filter you're using prevents you from interacting with the page as you would like. e.g. if you have Anti-ThirdpartySocial and you wish to like/share the page on Facebook your only solution (at the moment) is to completely disable µBlock which causes privacy concerns but given that you've shared on Facebook it dosesn't really matter anymore.
So if you could consider implementing this feature it would be nice.

**Comment by gorhill** [comment]
> So if you could consider implementing this feature it would be nice

I have some ideas to make it easy for users to un-break sites. Currently thought the blocking issue is #236, which I haven't found the time yet to address.

**Comment by logos88** [comment]
I agree with @Snapy I use ublock with Easylist, EasyPrivacy, ... but with Social filters disabled. Instead of using ublock for this, I have installed Disconnect too, because it leaves you to only allow facebook or twitter enabled in a specific page if you want to use their social buttons.

On the other hand, there are pages that I can't see well or use in a full way with ublock  enabled. In this sites I have to disable ublock, but at least I keep Disconnect so I can watch the web with adverts, but without tracking at least.

It would be great a simple way to enable/disable only advertising or social filtering lists (in separate) in particular webs. This way I could only use ublock for everything.

**Comment by gorhill** [comment]
> It would be great a simple way to enable/disable

Yes, I have my own solution for this, which I have been simmering for a very long time. I currently have infrastructure code written locally to fix the issue of easily un-breaking (or further tightening) web pages -- it definitely can be very tedious currently.

Just like dynamic filtering, I want to make the feature stashed away by default but readily available for users who are ready to override static filters.

Basically I split the concept of net filters into two categories, **Static filtering** -- the ones found in _"3rd-party filters"_/_"Your filters"_ tabs, -- and **Dynamic filtering** -- a broader concept of what is already used to block scripts/frames on the fly. This would allow to address a number of issues already filed aside the one here. Static filtering causes a lot of memory churning, so fixing sites through this is not ideal. Dynamic filtering though is virtually nil memory footprint-wise, so excellent to override existing static filters in order to un-break a site without having to change the selection of filter lists.

Anyway, I have my own ideas on giving users tools to fix stuff themselves on a per-site basis, and code already for this. It will happen sooner than later. The priority is to keep the extension minimalist, but to make available extra tools for those who care.

**Comment by logos88** [comment]
I am not sure about what you say because I don't have enough knowledge I fear. What I had thought it was something like when you open the hidden dynamic filtering options, but showing too a little grip with one square for Adverts, other for Privacy, other for Social, ... (and everyone of the categories of the 3rd-party filters"/"Your filters). And if you click on one of the squares, the filters on that category would be unabled inmediatly, but only the ones in that category (like social). And if you click again, that ones would be enabled again.

It would be something like the square button that disconnect has for twitter, facebook and google on the top. But whatever you do it will be better for sure :)

Another think I dind't know where to ask. In one post you showed your personal options for filters once, and I saw that you had Fanboy's Annoyance List and FanBoy’s Social Blocking checked. Since Fanboy's Social Blocking List is already included in Fanboy's Annoyance wouldn't that be redundant? (I only ask because it made me doubt).

**Comment by gorhill** [comment]
> something like the square button that disconnect has for twitter, facebook and google

Nah, I never try to mimic others, I prefer to come up with my own approach. There is more to the web than these 3 ones, especially elsewhere in the world. Whatever I do I will make it as user friendly as possible.

I prefer to be told of specific problems/issues/bugs, I will figure out the solution on my own when I agree to address an issue.

Re. Fanboy Annoyance I wasn't aware it contained Fanboy Social when I added the lists. I looked into it, and yes, Fanboy Social appears to be almost all in Fanboy Annoyance, except for 30 or so filters (I don't know which ones).

**Comment by logos88** [comment]
OKs! Great!

This is from fanboy website about Fanboy Annoyances List: "In page Pop-Ups and other annoyances; thereby substantially decreasing web page loading times and uncluttering them (includes Fanboy-Social List.)"

**Comment by ghost** [comment]
I didn't know too that Fanboy's Social Blocking List is already included in Fanboy's Annoyance List.

Shouldn't Fanboy's Social Blocking List get removed so it doesn't confuse?

By the way is `Fanboy’s Enhanced Tracking List‎` good to use? I see it's not checked by default.
