### ISSUE TITLE
[EasyPrivacy] Hyperlinks blocked

### ISSUE THREAD

**Issue by dhprototype** [uBlock-LLC/uBlock#373]
uBlock seems to block some links and buttons from bring clicked. For me, I'm having issue with links and button on Amazon. Items in red is not clickable until I disable uBlock.

First screen is accessible via this link - http://www.amazon.com/gp/help/customer/display.html/ref=gw_m_b_he_c?ie=UTF8&nodeId=508510

![image](https://cloud.githubusercontent.com/assets/9678346/5115825/a0646ad2-7012-11e4-9373-1345b4247278.png)

You'll need an Amazon account to access the next screen. This is the contact screen and you can access it by clicking on "Contact Us" link from above. You'll need to disable uBlock temporarily, refresh the screen to make the link clickable then once you are on the screen below, enable uBlock then refresh the screen again.
![image](https://cloud.githubusercontent.com/assets/9678346/5115828/a92e64ba-7012-11e4-8383-92f592464ad8.png)

**Comment by gorhill** [comment]
For the first case, I fixed it with the following custom filter:

```
@@||omtrdc.net^$domain=www.amazon.com
```

It's because there is `||omtrdc.net^$third-party` in EasyPrivacy. This needs to be reported to the maintainer of EasyPrivacy: [Report incorrectly removed content](http://forums.lanik.us/viewforum.php?f=64)

I can't check the second case, but maybe it is for the same reason, if you can confirm.

**Comment by dhprototype** [comment]
Thanks! I will check it out and give you an update.

**Comment by dhprototype** [comment]
It looks like both the links and the buttons are working now. Thanks!
