### ISSUE TITLE
Video not playing on news site

### ISSUE THREAD

**Issue by dhprototype** [uBlock-LLC/uBlock#374]
The video on this news article fails to play unless uBlock is disabled.
http://www.wsmv.com/story/27408881/man-questions-3000-comcast-bill#ixzz3JX38aBpo

I've experienced this for several news sites with similar video players but didn't think it would be due to uBlock until today. Haha.

**Comment by gorhill** [comment]
Fixed with f7c61647d86cef663a70856bd8d4789531ab1244. Had to add an exception to `s0.2mdn.net` because `2mdn.net` is blocked by Peter Lowe's list (and some other hosts files).

Purge cache for "uBlock filters", then click "Apply changes" while having auto-update enabled. This should force a fetch of the new version on github.
