### ISSUE TITLE
Not blocking Google search results ads

### ISSUE THREAD

**Issue by CharAznableLoNZ** [uBlock-LLC/uBlock#381]
When a tab is first opened and used to search something via the omnibar, ads are not blocked.  When refreshed the ads are blocked.

**Comment by gorhill** [comment]
Give me an exact test case so I can reproduce. I don't any such problem from here. uBlock doesn't make a difference how the page is loaded, via omnibar or otherwise. I tried "buy watch" and no ads showed up.

Need:
- Search terms
- Screenshot of resulting page would be nice (you can drag n drop image in a comment here)
- Browser version
- Filter lists selected

Also, other extensions installed. One of them could be actually injecting ads, which is something uBlock can't protect against.

**Comment by CharAznableLoNZ** [comment]
It doesn't do it every time, just once every five or so searches.

Search terms used:
MPC-HC

Screenshot
![snapshot 652](https://cloud.githubusercontent.com/assets/2172796/5210140/6032df9c-757c-11e4-9cce-b168cb31d27d.png)

Browser Version:
Version 40.0.2214.10 beta (64-bit)
Also does it on latest stable.

Filter lists selected:
Default lists plus anti-adblock.

Extention list:
APNG 2.1.3
appchan x 2.9.38
Auto HD For YouTube 6.5.1
Collusion for Chrome 2.3.0
Ghostery 5.4.1
Google Docs 0.7
Google Quick Scroll 2.2.2
Hover Zoom 5.5
HTTPS Everywhere 2014.11.25
Image Search Options 0.0.7.3
MEGA 1.0.213
NC Downloader 0.6
Referer Control 0.55
Stylish 1.2.2
Tab Cookies 1.0.5
User-Agent Switcher 1.8.6
Vimeo Download Videos 3.0.0
WOT 2.5.16
µBlock 0.7.0.10

If there's anything else I can provide, please let me know.

**Comment by gorhill** [comment]
I can't reproduce this.

I believe the culprit could be one of your extension, or something else on your system.

The "Ads by Google" is atypical, normally it is rendered orange. Even turning off uBlock, I can't get the result you get. With uBlock turned off I do get ads once in a while with other search terms ("buy iphone"), but with the orange "Ad" tag. With "MPC-HC" and uBlock turned off, I could never get ads.

There is a lot of crappy extensions in the Chrome store, I would first try to narrow it to one of these. For example [Hover Zoom](http://www.ghacks.net/2013/12/26/hoverzooms-malware-controversy-imagus-alternative/), which I see in your list.

See if you get the same results with all extensions/apps disabled except uBlock.

**Comment by gorhill** [comment]
I am trying to go through every single extension in your list to see if I can reproduce, and I arrived at "NC Downloader", however I can't find this extension in the store. Where is this from?

Also: "Tab Cookies" and "Vimeo Download Videos 3.0.0" I can't find in the store either.

So I tried all the extensions in there, repeatedly search for "mpc-hc" in URL address bar, alternatively I pasted the URL as seen in your screenshot, and however many often I tried, I just can't reproduce. I also downloaded and tried with Google Chrome 40 beta, still can't reproduce.

**Comment by gorhill** [comment]
Do you have any custom filters?

**Comment by my-password-is-password** [comment]
I think its this link for NC downloader, https://chrome.google.com/webstore/detail/nc-downloader/fhoofdceoggleefoalmfbfdmboaalhpo

the version is the same, 0.6

**Comment by gorhill** [comment]
Yes, found it not long afterward. Looks harmless.

Anyways, even without uBlock I **can't** get that sort of ads, so I am completely clueless at this point. Now I just need this to occur to somebody else with dev powers who can investigate why this is happening.

Would be nice to verify whether this happens with ABP too, as uBlock enforces the same cosmetic filters as ABP, so I expect this should happen as well with ABP.

**Comment by CharAznableLoNZ** [comment]
No custom filters, when I noticed it started happening I reset ublock to stock via the "Start from Scratch" button to make sure I hadn't added a filter that was allowing "acceptable" ads through.

**Comment by gorhill** [comment]
Can you check if these ads are inside an `iframe`, and if so, the URL of the `iframe`?

As said, ads on google search results look more like this:
![a](https://cloud.githubusercontent.com/assets/585534/5215653/bfba6112-7610-11e4-8923-ca55db2a4f01.png)

This is not what you get on your side. As if **something on your computer** is generating these ads.

Also, see if you get the same problem with ABP.

**Comment by CharAznableLoNZ** [comment]
Not really sure what I'm looking for but this is what inspect element shows.
![untitled](https://cloud.githubusercontent.com/assets/2172796/5221382/190bef6c-762d-11e4-928b-8595951a846a.png)

http://pastebin.com/xYkMrnsV
Perhaps WOT is doing this.

**Comment by gorhill** [comment]
Thanks for this. Ok, for the sake of comparison, using same search term, here is my DOM of the same portion:

![a](https://cloud.githubusercontent.com/assets/585534/5221978/df5d7414-766f-11e4-81f4-c014b1a06c14.png)

And here is yours:

![a](https://cloud.githubusercontent.com/assets/585534/5222025/1ecca4ca-7671-11e4-8c88-8fe93ced8fd4.png)

Major difference is that I do not have the `div[id="sqh"]` seen in your picture. When it comes to cosmetic filters, uBlock hides ads (with net filters they are blocked), it doesn't remove them from the DOM.

So this means you have an extra DOM branch in your page, of unknown provenance, while everything else is exactly the same.

I verified, and there is no `###sqh` cosmetic filter in EasyList, which means you would have the same problem with ABP.

Now is to figure where this extra DOM branch comes from. Since you are using an encrypted connection, aside Google itself possibly creating that DOM branch, only an extension or app could do this.

So further investigation needed.

**Comment by CharAznableLoNZ** [comment]
If there is anything I can do to help, let me know.
BTW thanks for making a proper, efficient, ad blocking method on Chrome.

**Comment by my-password-is-password** [comment]
Could it be one of your user styles that you use with the Stylish extension?

**Comment by gorhill** [comment]
Coincidently I had just installed Stylish and wondered... I never used this, but something designed to  inject something in a page, that's a good candidate.

**Comment by CharAznableLoNZ** [comment]
I'll disable it for a couple days and see if it still happens.  Since they are user created scripts, I could also see someone injecting ads.

**Comment by gorhill** [comment]
I don't know, from what I can gather Stylish only inject CSS styles, while there is a whole extra DOM branch in your case.

I would like to see the DOM property of the `<a>` tags of a URL in the ad box.

**Comment by CharAznableLoNZ** [comment]
I'm not sure where to find that information.
![snapshot 656](https://cloud.githubusercontent.com/assets/2172796/5233622/f617859c-7745-11e4-80aa-2542a95289d5.png)
http://pastebin.com/zVD8MH7w

**Comment by gorhill** [comment]
Really, it does look these ads are served by Google, I see nothing weird in there. If so, the questions are
- How come this is not in taken care by _EasyList_?
- Why can't I reproduce?

In any case, for now I will add the missing cosmetic filter in uBlock filters.

**Comment by CharAznableLoNZ** [comment]
Thanks, if there is any other information I can provide, let me know.
