### ISSUE TITLE
"Block Element" does nothing

### ISSUE THREAD

**Issue by kodemage** [uBlock-LLC/uBlock#404]
On wikipedia I'm trying to block the giant ad at the top of the page and when I right click the element and select "block element" uBlock finds it, highlights it in pink and then my cursor turns to the "busy" animation and just stays there. 

So, blocking elements is completely broken as far as I can tell. It just does nothing but make the cursor busy.

**Comment by gorhill** [comment]
When the busy cursor shows up, there is a dialog box in the bottom-right corner where you can further fine-tune the filter to create. Move the mouse over the bottom-right corner, the dialog box will become more visible. It is set to be semi-transparent when the mouse is not over in order to see the effect of the filter on the page.

**Comment by gorhill** [comment]
By the way... There is no ad on Wikipedia. Do you have a specific URL where I can see what you are talking about?

**Comment by kodemage** [comment]
they occasionally put up this giant ad which asks for a donation, it's
rather obnoxious and takes up about half the screen

it's the wikipedia equivalent of the NPR pledge drive where they interrupt
the normal programming and ask for money

it's still an ad and it can be blocked.

**Comment by gorhill** [comment]
So, did you find the dialog?
