### ISSUE TITLE
Q: how to identify/selectively disable what filter is blocking a particular element?

### ISSUE THREAD

**Issue by mblais** [uBlock-LLC/uBlock#415]
(My apologies if this is the wrong place for this question, but I couldn't find a better place to ask it :-\ )

The default filter set is blocking some images that I want to see - icons for "liking" pages on social media sites. Some of these images come from the social media sites and others are defined in css.

How can I find out which filters are blocking these images, and disable them (selectively by site would be ideal)?

TIA for the help, and for this wonderful extension ;-)

**Comment by gorhill** [comment]
You may want to un-select _"Fanboy's Social Blocking List"_. Otherwise there is no easy way, other than opening the _"Statistics"_ tab in the dashboard and looking at what was blocked (net filters), or opening the DOM and looking at what cosmetic filters have been injected. Long term I wish to make all this easier, but that would be in some not so near future.

**Comment by mblais** [comment]
That's what I was looking for, Thanks!

Please consider adding this Question and Answer to the Wiki... under Tips and Tricks, if not as a top-level entry.

Too bad the Whitelist can't be used to disable specific filters.

**Comment by gorhill** [comment]
> Too bad the Whitelist can't be used to disable specific filters

Yes, I have been thinking since a long time about this kind of feature (disabling specific filtering), to allow users to help themselves without requiring knowledge of the plumbing. I will come up with something eventually.
