### ISSUE TITLE
Marking of Dynamic Filtering is wrong?

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#434]
<h2>Steps:</h2>

1) Enter a site you have no Dynamic Filtering rules on.
2) Enable any HOST specific Dynamic Rule, lets say 3rd-party frames - HOST rule is now painted in **red**.
3) Enable the same Dynamic Rule of the same party, but this time, the Global rule - Note that the HOST rule _didn't_ change to a **light red** color (and won't change even after a reload of the page).
**Is this an actual issue (performance wise, or just visual wise) or am I not understanding something?**
4) Click on the HOST specific Dynamic Rule - Gray painting is the excepted result.
5) Click on the Global Dynamic Rule - the HOST specific rule is still gray (unless it's overriding static filters by design right now? if so, it's not an issue.)

**Comment by gorhill** [comment]
By design.

Picture you have many other hosts where you have explicitly blocked 3rd-party frames. It would not be a good idea to remove all these explicit rules whenever a global block 3rd-party frame rule is set, because if the global rule is removed, suddenly all these rules that were explicitly set by the users would disappear.

When a rule is set which override whatever global rule that may exist, it is considered an **explicit** rule (darker shade), which only the user can revoke, the filtering engine won't mess with it, because it can't read a user's mind. Only the user knows whether his explicit rule must be removed or not.

**Comment by Mikey1993** [comment]
Got it.
Good explanation.
