### ISSUE TITLE
Visually indicate that ublock is disabled for a page.

### ISSUE THREAD

**Issue by dashed** [uBlock-LLC/uBlock#441]
When I ctrl-click the on/off icon from the ublock pop-out window, I think it'll be useful to visually indicate that ublock is disabled for a page.

**Comment by gorhill** [comment]
uBlock shows that it is disable: it's grayed out. If you want a different visual just because it's disabled on one single page, I don't see the point. uBlock can be disabled for one page, one section of a web site, a whole web site, or according to a URL with one or more wildcards. I really don't see the point to have a special visual for one specific case.

**Comment by dashed** [comment]
Ah I see. I wasn't aware of this kind of blocking capability.
