### ISSUE TITLE
[EasyPrivacy] Blocks important parts of American Express site

### ISSUE THREAD

**Issue by engelke** [uBlock-LLC/uBlock#462]
Many links on the online.americanexpress.com site display an overlay on top of a page with the requested information. (I don't know why they did it that way, it seems dumb to me.) For example, the message center and the contact us pages do this. This blocker prevents the overlays from displaying, with no obvious indication that important information is missing from the page.

**Comment by gorhill** [comment]
> This blocker prevents the overlays from displaying

The problem is _EasyPrivacy_, you will have the same problem with ABP + _EasyPrivacy_. The filter `||ensighten.com^$third-party` blocks scripts from `nexus.ensighten.com`, and this breaks the page:

```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://nexus.ensighten.com/amex/prod/code/e10610aa745b003aa5fb6f33da6c1190.js?conditionId0=181208
```

Please [contact the list maintainers and report the problem](http://forums.lanik.us/viewforum.php?f=64). Workaround filter is `@@||nexus.ensighten.com/amex/$domain=americanexpress.com`, you may suggest this to them.
