### ISSUE TITLE
[Firefox] Tearing a tab to form new window, causes popUI to loose blocked item list..

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#526]
Tearing a tab, to form a new window in firefox, will cause uBlock popupUI to loose its blocked list..

![ublock tearing tab](https://cloud.githubusercontent.com/assets/779630/5789905/0a5ce57a-9ea5-11e4-8445-0f66eda1bc8c.png)

**Comment by Deathamns** [comment]
My guess is that the id of the tab changes when it's dropped to another window, which could be the cause.
You have to refresh the page for now.

**Comment by harshanvn** [comment]
Ok. Thanks. And i believe this is just a cosmetic thing and not something people will usually do.
However, i believe this needs to be fixed at some point in future :)

**Comment by pwr22** [comment]
> Ok. Thanks. And i believe this is just a cosmetic thing and not something people will usually do.
> However, i believe this needs to be fixed at some point in future :)

I wouldn't care about the bug but this is something I do frequently

**Comment by Deathamns** [comment]
Notes on the issue:
When moving tab to another window, no `TabMove` event is fired. Instead, a `TabOpen` event fires on the target window, and a `TabClose` on the source window. So, a totally new tab is created, but there is no reliable way to associate the old and a new one.
Detecting `drag` and `drop` events are not viable either, because that is not the only way to move a tab to another window, also there are extension that are able to move more than one tab at once, but the one I tried prevents detecting these events.

**Comment by gorhill** [comment]
So it does look like a Firefox limitation. Workaround is to refresh the tab being observed.
