### ISSUE TITLE
mail.yandex.ru loads with too much errors

### ISSUE THREAD

**Issue by farag2** [uBlock-LLC/uBlock#540]
Couldnt load account on mail.yandex.ru any more with 0.8.5.6 on Firefox 36.0 b1
Here are my filters: http://rghost.ru/60429951

**Comment by gorhill** [comment]
Disable "Experimental features" as a workaround, until I provide a fix in the next version.

I see the problem is that there is a `content-security-policy-report-only` header, which means I need to detect this and disable local mirroring for the site. Currently uBlock detects only `content-security-policy`. It also needs to detect `content-security-policy-report-only`.

**Comment by farag2** [comment]
Thanks. Temporarely it works.

**Comment by gorhill** [comment]
I am disabling the "experimental features" setting for the time being. There are more problems with the current bug which cannot be resolved trivially (related to fix to #516), aside the other issues elsewhere caused by CORS.

**Comment by farag2** [comment]
Much better, but still load with errors even on the main page yandex.ru. Downgrade to 0.8.5.4, waiting for fixes to upgrade to...

**Comment by gorhill** [comment]
Using your backup, the errors I see on `yandex.ru` are normal errors as far as I can tell:

![a](https://cloud.githubusercontent.com/assets/585534/5801024/417cf86e-9fb4-11e4-94cf-e129a51b2659.png)

Whenever something is blocked, which is the purpose of uBlock, this will cause normal error messages at the console. This actually confirms uBlock is blocking properly.

**Comment by farag2** [comment]
I was talking not about console errors. All site was ruined, but with 0.8.5.7 version, it's OK.

**Comment by farag2** [comment]
I think thread could be closed. waiting for another release and new bugs))
