### ISSUE TITLE
Can't Install on Firefox 35

### ISSUE THREAD

**Issue by moonstruck** [uBlock-LLC/uBlock#543]
I'm getting the following error message.
uBlock could not be installed because firefox cannot modify the needed file.
Firefox 35.0
OS: Ubuntu 14.10 32 bit (Linux moonstruck 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:28:14 UTC 2014 i686 i686 i686 GNU/Linux)

**Comment by ghost** [comment]
I had the same problem. Quite obviously, my Firefox profile was
corrupted. With a new profile I had no problem at all to install µBlock.

Another possible reason (although I didn't check it);
http://www.ghacks.net/2015/01/16/fix-add-ons-not-working-in-firefox-35/

**Comment by gorhill** [comment]
@tlu1024 but it works all fine in my FF35, so the explanation does not fit.

It seems the problem goes away when people install on a fresh profile. Why would profiles go wrong I have no idea.

@moonstruck Was this you first attempt to install uBlock?

**Comment by krisu5** [comment]
I got the same problems too, I get error that says that extension cannot be downloaded because error connecting to github server (not literal translation because I'm using finnish version of Firefox).

Workaround is right clicking to download link and save to download folder, drag and drop file to firefox and then install. But you have to do this every time there's release, because automatic updates don't work (least in my case)

OS: Windows 7

**Comment by gorhill** [comment]
**Correction:** I checked, and somehow my `dom.indexedDB.enabled` is set to true. I don't ever remember changing this.

So it's likely why I didn't experience the issue, and so it seems that `dom.indexedDB.enabled` set to `false` would be the problem when the error message is:

> uBlock could not be installed because firefox cannot modify the needed file

**Comment by moonstruck** [comment]
@tlu1024 Brilliant! I've performed Refresh Firefox from about:support. Everything is working as expected and got solved two other FF issues as well. Thanks.

@gorhill Yes this was my first attempt.

**Comment by krisu5** [comment]
I tried using new profile to install uBlock, still didn't work, same error then previous attempts. I feel like it's Firefox based problem, but if others can get it installed, then I dunno.

**Comment by gorhill** [comment]
@krisu5 Really I don't understand the problem you report. "error connecting to github server" means something is blocking your connection to Github, you have to find out what. Aside that, yes, you have to drag the XPI file to the add-on page. Until uBlock is in the AMO, this will have to be done manually.

**Comment by krisu5** [comment]
Sorry for my comments, I noticed it was Avast 2015 blocking installing the addon. I now know how to fix this. Thanks for support anyway.

**Comment by gorhill** [comment]
>  I noticed it was Avast 2015 blocking installing the addon

Ah I see. There has been many people reporting that Avast wrongly flags uBlock as malware. It must be some entries in the malware domain lists that ship with uBlock which Avast doesn't like.

**Comment by krisu5** [comment]
Actually no it wasn't that, it was Avast 2015's new HTTPS scanning that makes SSL error in Firefox and screws up the installation. You cannot install any XPIs from any HTTPS-powered site (except AMO) with HTTPS scanning on in Avast.

I had already that "browser cleanup" unenabled that you refer to, because it's so bad.

**Comment by xdmx** [comment]
I have this error on firefox 35 mobile (on my tablet). On my laptop (firefox 35 as well) it works great

**Comment by gorhill** [comment]
@xdmx Your issue is probably related to #524?

**Comment by xdmx** [comment]
It is, I didn't see it

**Comment by grektum** [comment]
Installation failed on firefox 35 on linux with the same error message.

The issue was caused by a change of default parameter in firefox 35 and once I reverted `dom.indexedDB.enabled` to true, the installation worked.  

thanks @tlu1024 for pointing this url: http://www.ghacks.net/2015/01/16/fix-add-ons-not-working-in-firefox-35/
