### ISSUE TITLE
[Firefox] Manually editing cosmetic filter list breaks all filters

### ISSUE THREAD

**Issue by leaumar** [uBlock-LLC/uBlock#546]
1) use element picker to pick some elements to be hidden on various websites (9gag, memebase and 4chan, everything like sidebars, legal footers and other wastes of screen space - I'm familiar with ABP syntax so I simplify each rule to its core selectors)
2) revisit pages several times to make sure it works
3) open ublock config, go to filters tab
4) remove any filter
-> all filters stop working until I completely clear the list and start over fresh

I don't know why it happens, the list looks fine. Undoing my change (ctrl-z) doesn't restore functionality.

Example: 9gag and facebook

9gag.com###sidebar
www.facebook.com###rightCol

Refreshed each page a few times, it works. Deleted the facebook filter line (including the preceding newline), refreshed fb and 9gag. Fb of course had its sidebar back, but so did 9gag despite 9gag's filter still being there. Ctrl-z to undo my change and restore the list exactly as it was, both filters stop working. Nothing I do makes it work again, except for clearing the entire list and starting over.

Firefox 35.0, 8.1 x64

**Comment by gorhill** [comment]
Symptom you describe correspond to a cosmetic filter syntax error. They have to be valid CSS rules, or expect problems. If you can show me all your filters, I will spot where is the problem.

**Comment by leaumar** [comment]
## The example i wrote with fb and 9gag wasnt hypothetical, i literally carried that out with just those 2 filters and it happened as described.

**Comment by gorhill** [comment]
Can't reproduce.
- After you click _"Apply changes"_, are you waiting long enough for the filters to be fully reloaded
  - All the filters are reloaded, necessary because of potential duplicates
  - For cosmetic filters specifically, they become active **only** once all parsed
  - Fixing issue #520 should help greatly reduce the time it takes to reload all fitlers
- Do you have _"Auto update"_ selected?
  - If at least one remote server doesn't respond, the update may take long to complete (timeout is 15s), and in such case, the filters won't be working until filter lists have been all parsed
  - Fixing issue #376 should also help a lot here.

Creating then editing a cosmetic filter from the element picker is optimal, as this won't cause a reload of all filters. (And you get to see the effects on the page).

**Comment by leaumar** [comment]
After I apply changes, I wait long enough for everything to reload (it takes only about 1s from what I can see). I've deselected auto-update and waited 15s anyway. It still happens.

Would it help if I made a video of this so you can see everything in a clear picture?

**Comment by gorhill** [comment]
> Would it help if I made a video

If it's not too much trouble.

**Comment by leaumar** [comment]
https://dl.dropboxusercontent.com/u/3357590/Videobox/firefox_20150120_004054W.mp4
Here you go :) Hope I covered everything clearly enough (just open it in a tab, it's streamable)

**Comment by gorhill** [comment]
Ok thanks. Let me look into this carefully, will see what I can find.

**Comment by gorhill** [comment]
Actually, never mind, I just spotted the problem. The _"My filters"_ entry is not selected in the filter lists.

As said, when using the element picker, this bypasses reloading all filters, and it works right away without any overhead. However when editing from the textarea, a normal full reload occurs (because someone could paste MB of filters in there), but since your filter lists is not selected, they end up not being applied.

**Comment by leaumar** [comment]
...

Well, don't I feel stupid now xD Sorry about that, and thanks for spotting that :P
