### ISSUE TITLE
no icon in firefox

### ISSUE THREAD

**Issue by arschkrampe** [uBlock-LLC/uBlock#557]
after install there is no icon
where is it?
can't work without the icon

**Comment by Deathamns** [comment]
The extension has proper support from Firefox 29. And since you didn't mention your version, I assume it is less than 29?

**Comment by arschkrampe** [comment]
oh, sorry
its ffox 35

**Comment by Deathamns** [comment]
Everything else works (does it block ads for example), except the button?
Do you use other extensions that modify the look of the browser?

**Comment by arschkrampe** [comment]
seems like nothing happens at all, no messages, nothing
yeah, i use 'the fox, only better' and 'classic theme restore'

**Comment by arschkrampe** [comment]
tested it on a 'naked' ffox - seems to work
sad that it does not work on a 'modified' fox.
will stop using it til these issues are terminated

**Comment by Deathamns** [comment]
First we should identify the problem...

I tried those two extension, but they didn't interfere, so...
What happens when you disable/enable the extension? Does it work after that? Any chance that you're using the StartupMaster add-on?

If no, then in the Add-ons Manager disable the addon, open the Browser Console (Ctrl+Shift+J), clear it, make sure that everything is checked in the JS dropdown, then enable the extension, and see if the console says something.

**Comment by nhantrn** [comment]
I'm using FF24.1ESR at work, please add support for it.
