### ISSUE TITLE
[Firefox] Add Bluhell Firewall to Benchmarks

### ISSUE THREAD

**Issue by pwr22** [uBlock-LLC/uBlock#560]
I would be very interested in seeing some benchmarks that include this plug-in and maybe some real world examples of where one blocks more effectively than the other. I would except uBlock to do better since BHF has very naive blocking rules in comparison

**Comment by gorhill** [comment]
I would like to find out too because I've always been skeptical of performance gain of using gigantic regular expressions over well laid out dictionary. However I have been benchmarking using Chromium mostly, using home-made tools, so I do not have insights at this time on how to run automated benchmark on Firefox.

**Comment by my-password-is-password** [comment]
Is this any good?

http://www.areweprivateyet.com/

its on github 

https://github.com/ghostery/areweprivateyet

**Comment by gorhill** [comment]
Err I understood OP was interested in memory/CPU benchmark. Re-reading again I see it's about how much stuff BluHell blocks? If so that is easy to answer:

> just seven hard-coded blocking rules covering about 8400 .com and .net domains, these were auto-generated from Easylist [[source](https://addons.mozilla.org/en-US/firefox/addon/bluhell-firewall/)]

So BluHell hard-code part of EasyList, so it can't block more. uBlock you choose whatever you want, from zero filter to above 100,000. Not worth running a benchmark for that, BluHell's description says all.

**Comment by pwr22** [comment]
Sorry if I wasn't clear, I meant both

Peter

**Comment by pwr22** [comment]
I agree uBlock will block a lot more, I was more interested if BHF is
capable of blocking the worst stuff etc

Peter

**Comment by gorhill** [comment]
You will have to try it and decide for yourself, I can't decide for you. And thinking of it, I can't possibly take all request to benchmark everything under the sun, or I might just as well stop coding. However I undertook this project because I like coding. So I am just going to close this. Maybe BluHell author will accept to benchmark for you if you ask him.

**Comment by pwr22** [comment]
I'll do some informal testing again (I did it before when the FF port first appeared), I was just hoping you had some automated method. I'll chime back in if I manage to find a way of automating FF tests for you
