### ISSUE TITLE
Ads on pandora

### ISSUE THREAD

**Issue by darakian** [uBlock-LLC/uBlock#565]
Adblock plus blocks commercial ads in pandora (I think via the easylist filter) while microblock does not. Not sure how to dig deeper on this.

Edit:
Firefox 35, uBlock v. 0.8.5.7

**Comment by gorhill** [comment]
What is "pandora"? Give me a specific URL where you see a problem.

**Comment by gorhill** [comment]
I suppose it's this site: http://www.pandora.com?

If so, you will need to tell me exactly where I am supposed to see ads. I looked in the filter lists, and all filters in there related to http://www.pandora.com are supported just fine in uBlock. Also, tell me what your settings -- filter lists selected, dynamic filtering rules, etc.

uBlock can block just fine what ABP blocks with the same lists, so we have to find out what is specific to your case.

**Comment by darakian** [comment]
Yes http://www.pandora.com/
The ads come up in stream. I can make a video for you if you like.

**Comment by gorhill** [comment]
Which stream did you play and how long to wait before you see an ad?

**Comment by darakian** [comment]
custom station (I think it will happen for all of them). Not 100% sure on duration. 20 min maybe?

**Comment by gorhill** [comment]
So if I understand correctly it's a sound-based ad? I'm confused here because earlier you offered to make a video..

So I need to spend time efficiently, I need to know exactly what I should look for. 20 minutes is a bit long just to find out I did not follow the steps properly. Thing is if I spot the ad, I will also try with ABP to confirm this is a filter list issue (uBlock just block same as ABP no reason why there should be a difference) and that means spending a lot of time trying to spot that ad.

**Comment by darakian** [comment]
So, I spent some time trying to recreate the issue and I can't (this is across two machines). The one thing I noticed was that the uBlock icon which shows the number of requests blocked was showing zero and is now showing 36. I'm not sure what changed, but it is working now.

Edit: Also yes the ads on pandora are sound based ads. Think commercials on a regular radio station.
