### ISSUE TITLE
uBlock breaks a site - now what?

### ISSUE THREAD

**Issue by generallevy** [uBlock-LLC/uBlock#570]
So uBlock breaks a site I frequent because of one JavaScript that gets blocked. How do I allow this one JavaScript on this one site? 

I can use the whitelist but then I get a multitude of ads and other stuff I don't want.

**Comment by gorhill** [comment]
I can help if I can assess myself. Give me a URL.

**Comment by generallevy** [comment]
http://www.styleforum.net/t/230626/how-to-use-spoiler-function

Clicking on the Spoiler should reveal it, but it doesn't work. I believe it's because yui.yahooapis.com gets blocked. Not sure which list this is coming from.

I love how Ghostery has on/off switches for things it blocks (per site) but also understand the way uBlock blocks things is a little different.

**Comment by gorhill** [comment]
I am using the default filter lists here, and the spoilers expand fine. What are your filter lists?

**Comment by gorhill** [comment]
> I love how Ghostery has on/off switches for things it blocks (per site)

Yes, I agree Ghostery's UI is pretty slick.

The closest you can find in uBlock is dynamic filtering, which can be made available when you check _"I am an advanced user"_ in the settings. Once you have access to the dynamic filtering panel, you can override the block/allow status on a per-hostname basis, locally or globally. So this would allow you to un-block stuff from `yui.yahooapis.com` if you think it's where the problem is. ([An example of using dynamic filtering to unbreak a site](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#important-3)).

But unless one understand well how dynamic filtering works, I can't advise to use it, as I want it to be more a self-help tool.

There is a feature request in the pile to make it easy to create a filter from a log entry. This will come in time.

**Comment by generallevy** [comment]
yui.yahooapis.com seems to come from the hpHosts Ad and Tracking servers list, and of course if I disable that list the spoilers work.

BUT my main point here was that sometimes you want to switch off a filter per site. I actually used that feature in Ghostery quite a bit. However, I think performance is more important to me, so I will keep using uBlock and hope this feature gets implemented in the near future :)

Thanks a lot for your work!

**Comment by gorhill** [comment]
> sometimes you want to switch off a filter per site.

Well as said with dynamic filtering you can override any filter from the filter lists (globally or per-site). Though not as granular as static filtering, it's serve well one of its purpose: point-and-click to easily un-break web sites.

Otherwise it's issue #68, but I want to address other issues (like #520) to make sure that when I fix #68 it will will work smoothly.

**Comment by gorhill** [comment]
I will add an exception to `yui.yahooapis.com` as per issue #17. I don't know why, but sometimes hpHosts get re-hauled with countless false positives as a result.
