### ISSUE TITLE
How to unblock YouTube comments?

### ISSUE THREAD

**Issue by zarovnyaev** [uBlock-LLC/uBlock#592]
Hello. I installed μBlock in my Firefox browser and after this YouTube comments was blocked. How to add YouTube comments to whitelist?
Thanks.

**Comment by yupi2** [comment]
Put this into your rules:

```
www.youtube.com plus.googleapis.com * allow
```

**Comment by gorhill** [comment]
@zarovnyaev What filter lists are currently selected?

**Edit:** I just verified, and Youtube comments are **not** blocked when default settings are used.

**Comment by gorhill** [comment]
@yupi2 That works only if "advanced user" is enabled. Given the issue, I wouldn't suggest @zarovnyaev to enable "advanced user" mode.

**Comment by zarovnyaev** [comment]
@gorhill was blocked with all custom filters comented. μBlock started to block YouTube comments at once after after instalation.
@yupi2 this helps me. Thanks!

**Comment by gorhill** [comment]
@zarovnyaev uBlock comes with "advanced mode" disabled and there are no preset rules or custom filters. So you did enabled it and clicked to block 3rd-party frames. So you did this, it wasn't "I installed μBlock in my Firefox browser and after this YouTube comments was blocked".

**Comment by DonChino** [comment]
Just want to let everyone know that I came here looking for a solution to the YouTube Comments problem, because I also thought it was uBlock Origin. After seeing the developer blow his top so many times screaming that it is NOT his Add-On I decided to try and see if it was something else, because we have so many Add-Ons/Extensions loaded in our browsers nowadays. :)

Anyway, it turns out that it was - HTML5 Video Everywhere! - that was causing the problem with YouTube Comments. It never would have crossed my mind, since what does HTML5 VIDEO have to do with YouTube comments, but I disabled and restarted my Firefox browser to suddenly see my YouTube Comments come back. I do not have Flash installed so I MUST have something that forces HTML5 and stops AUTOPLAY, so that add-on works PERFECTLY but it turns out that it breaks YouTube Comments.

I hope someone else finds this useful and that way GORHILL can relax and focus on other "bugs"... :P

**Comment by hsmlei** [comment]
> 
> 
> Just want to let everyone know that I came here looking for a solution to the YouTube Comments problem, because I also thought it was uBlock Origin. After seeing the developer blow his top so many times screaming that it is NOT his Add-On I decided to try and see if it was something else, because we have so many Add-Ons/Extensions loaded in our browsers nowadays. :)
> 
> Anyway, it turns out that it was - HTML5 Video Everywhere! - that was causing the problem with YouTube Comments. It never would have crossed my mind, since what does HTML5 VIDEO have to do with YouTube comments, but I disabled and restarted my Firefox browser to suddenly see my YouTube Comments come back. I do not have Flash installed so I MUST have something that forces HTML5 and stops AUTOPLAY, so that add-on works PERFECTLY but it turns out that it breaks YouTube Comments.
> 
> I hope someone else finds this useful and that way GORHILL can relax and focus on other "bugs"... :P

Same here. I had tampermonkey installed. After disabling it the comments reappeared.
Oddly enough after enabling tampermonkey again the comments still appeared.

**Comment by esovan** [comment]
Just want to say this .. On a completely fresh install of chrome browser with ublock as the only addon; Comments were removed. When i disable ublock they come back.

Edit: After reinstalling ublock there was still a problem. But when i reset all settings in ublock the problem went away. Maybe some settings are stored somewhere. Anyway i recommend resetting all settings.

**Comment by Mikey1993** [comment]
@esovan , this is not the official repo of uBlock Origin, please see my post: https://github.com/uBlock-LLC/uBlock/issues/1833
