### ISSUE TITLE
Suggestion: make disabling/enabling uBlock on websites more simple

### ISSUE THREAD

**Issue by Matthewus** [uBlock-LLC/uBlock#608]
I think having two buttons wtih text, in this case, disable/enable uBlock for this hostname, and disable/enable uBlock for current site is much better than the power button. I think the element picker button should have text too.

**Comment by gorhill** [comment]
What about users who like it the current way?
- _You_ prefer another way
- Some other users prefer the current way
- I prefer the current way (minimalist)

I can't design to please everyone's contradicting opinions. Since subjectivity is involved, I make the final call.

On top of that your suggestion would cause a drastic change to the minimalist interface which has been like this since uBlock is born.

> I think the element picker button should have text too

There are tooltips.
