### ISSUE TITLE
How to change language?

### ISSUE THREAD

**Issue by peterbrinck** [uBlock-LLC/uBlock#622]
How do I change the language?

Right now, it chooses for me, but I want it in english

**Comment by Deathamns** [comment]
If the extension is translated to the language that your browser currently uses, then that will be picked, otherwise English. This is decided by the browser. You don't have control over this, neither extension developers (unless they implement a self-solution for localization).
If you want to change the language, you have to change the browser language.

**Comment by gorhill** [comment]
As @Deathamns said, set your browser to use English. How to do this depends on browser/OS, I am sure it's easy to find information about this when you search. I don't intend to implement a custom solution to bypass browser settings.

**Comment by bakancs** [comment]
but I'm not Spanish, I'm not in Spain, I wanna use it in English
