### ISSUE TITLE
host name not displayed in dynamic filtering frame, when inline-scripting is active..

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#630]
As, the tile says, visit below website. And make sure inline-scripting is active. Host name is not displayed. Not sure, if its a bug or not..See the pic, lifehacker.com is not listed in the pane..

http://lifehacker.com/ublock-the-memory-friendly-ad-blocker-is-now-availabl-1681818949/all

![ublock lifehacker](https://cloud.githubusercontent.com/assets/779630/5944251/78df7e00-a74b-11e4-82a4-566796a9d9c3.png)

Using v0.8.6.0-beta 6

Update 1: Same issue can be observed on Chrome (i have v0.8.5.7 )

**Comment by chrisaljoudi** [comment]
Hmm, it seems like this is consistent across all µBlock browser platforms.

Anyway, it _seems_ (to me) like this is not a bug. Dynamic Filtering will show the various domains/hosts from which resources are being grabbed for the current tab. That doesn't include the page's host itself, because µBlock doesn't currently have a concept of blocking pages that are explicitly "navigated to" — I believe you can't block the mainframe page request.

In the default configuration, there are XHR requests that go out to When the scripts are disabled (as your screenshot shows), some XHR requests to `lifehacker.com` occur (and they're fine):

![XHR](https://cloud.githubusercontent.com/assets/2351359/5944803/04d2d3c2-a6e7-11e4-8f95-9e2929712466.png)

However, when scripts are blocked as your screenshot shows, the scripts that perform those XHR requests are blocked, so the XHR requests never occur. Since there don't appear to be any other resources in the page that are loaded from `lifehacker.com`, it doesn't show up in the Dynamic Filtering list.

---

@gorhill what do you think?

**Comment by gorhill** [comment]
Definitely a bug.

This makes it impossible to override the more generic rules. Looking into this.

**Comment by gorhill** [comment]
Right, it's yet another side effect of fix to #516.
