### ISSUE TITLE
feature: disabling ad filters

### ISSUE THREAD

**Issue by atomGit** [uBlock-LLC/uBlock#641]
i can see where it would be useful to allow 1st/3rd party network requests, but completely disable ad blocking, perhaps by adding another "filters" row to the UI to make it easy

as a side note, the UI is clean and very simple but, as noted in wiki, requires a bit of reading to understand - i would suggest adding tool-tips and, especially, adding "1st party" and "3rd party" column headers to the UI for the images/scripts/etc. rows

one other thing i didn't want to open a ticket for ... it is easy enough to understand what the green and red buttons for network requests are for, but what is the purpose of the gray buttons?  i didn't see this mentioned in the wiki

**Comment by gorhill** [comment]
> would suggest adding tool-tips 

It's for advanced users, there is no tool-tips in advanced user mode. They quickly become annoying once you understand know how things work, which I expect an advanced user will figure after the required reading the wiki.

> adding "1st party" and "3rd party" column headers

The columns are not 1st-/3rd-party, they are global/local rules. Headers would occupy precious limited space, to remind advanced user of something that is easy to remember: left = global, right = local. I think it's pretty clear from the wiki.

> what is the purpose of the gray buttons? i didn't see this mentioned in the wiki

https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide#first-solution

Bottom-line is that I created the advanced-user mode so that I don't have to deal with issues being constantly opened every time a user has a question about how it works etc. I just do not have the time for this.

**Comment by atomGit** [comment]
if you don't want to deal with questions, then add tool-tips for advanced mode and make it an option to display them

as far as not adding column headers or tool-tips, that's equivalent to having a program with 2 check-boxes and no labels - what are they for? you have read the manual

it is easy enough, even for advanced users, to occasionally mistake the local/global columns - space is not a problem if you use tool-tips (and make them an option) - whether tool-tips are annoying is entirely relitive
