### ISSUE TITLE
[Firefox] how do I white list all local sites 192.168.*.*

### ISSUE THREAD

**Issue by TimTechDude** [uBlock-LLC/uBlock#669]
I have just switched from using ABP 2.6.7.

I used rule "@@||192.168._._^$document" to whitelist all local sites to stop interference with router interfaces.
This does not appear to work when placed in "My Filters" (which I checked was enabled)
What am I doing wrong?

Thanks

**Comment by gorhill** [comment]
uBlock does not support the `document` option, as this is used to disable completely a blocker, and I completely disagree with using a filter to disengage a blocker. What you need to use is a [whitelist directive in the _Whitelist_ tab in the dashboard](https://github.com/gorhill/uBlock/wiki/How-to-whitelist-a-web-site).

However I realize I didn't take into account that the target of whitelisting could be an IP address. Well it would work with an IP address, but what you want is `192.168.*/`, and currently a wildcard at the end of a hostname is not allowed (because it would be impossible to create an efficient dictionary).

So I need to extend the whitelisting code to support explicitly IP address, and in the case of IP address, the wildcard need to go at the end, when one is used.

**Comment by TimTechDude** [comment]
Thanks for the fast reply and for all your hard work!
I will just stick a few IP addresses in the whitelist for now, that works fine.

**Comment by Cr4z33** [comment]
Over 1 year has gone and we still need to enter single LAN IPs... :/

**Comment by JOduMonT** [comment]
@Cr4z33
https://github.com/gorhill/uBlock/issues/1578
- For 192.168.0.*, use /^https?://192\.168\.0\.\d+// (no need to escape forward slashes).
- For 10.0.*, use /^https?://10\.0\.\d+\.\d+//.
