### ISSUE TITLE
Opera 12 (engine Presto) don`t support

### ISSUE THREAD

**Issue by KarenArzumanyan** [uBlock-LLC/uBlock#672]
Opera 12 (engine Presto) don`t support
Please add support this browser.
Thanks.

**Comment by gorhill** [comment]
Is this browser still maintained, updated?

**Comment by harshanvn** [comment]
I don't think it is.
Also, there is a new browser being cooked up, called Vivaldi (https://vivaldi.com/), more targeted for advanced users, which is based on Opera 12 original's goal..I believe its spearheaded by opera's ex-cofounder or sth like that...

**Comment by lewisje** [comment]
The only platform that this is the latest version of Opera for is FreeBSD, but even that hasn't been updated in about 3 years, and until Chromium is ported to that platform, neither Vivaldi nor the new Opera will be available on it.

It would take a little work to port uBlock to old Opera (I think 12.10-12.17), because it uses a rather different API, the URLFilter API.

**Comment by KarenArzumanyan** [comment]
Opera 12 (engine Presto) is no longer being updated, but it is most useful browser, and then dos them very popular. If it is not very difficult to support, please do so.

**Comment by gorhill** [comment]
> If it is not very difficult to support, please do so

I marked the bug as available for somewhere else to take on. I just don't have the time to take more coding project. If anything, I need to find ways to take care of less stuff.

**Comment by Deathamns** [comment]
Presto Opera has its own content blocking engine, and with its extension API you can only add/remove filters to it. Requests cannot be intercepted, so basically there's nowhere to port the extension.

**Comment by gorhill** [comment]
> Requests cannot be intercepted

Alright, this settles the issue: cannot be ported.
