### ISSUE TITLE
whitelisted stuff in the Romanian List?

### ISSUE THREAD

**Issue by romanian2** [uBlock-LLC/uBlock#693]
in the  ROU:RO-LIST there are quite a few of whitelisted sites:

!Whitelist
@@||homebank.ro^$document
@@||profitshare.emag.ro/get_ads.php?*
@@||profitshare.ro/get_ads.php?*
@@||rezitests.ro/advertisement.js
@@AC_RunActiveContent.js
@@media.bestauto.ro
@@||promozone.ro^$document
@@||olx.ro/i2/ajax/ad/getcontact/*

olx.ro is the biggest romanian ad site
emag.ro is the biggest romanian online retailer
homebank.ro belongs to bcr.ro which is a major bank here
bestauto.ro is a car sales site
promozone.ro - I think the domain speaks for itself, and so on

I though the main purpose of this adblock plugin is to actually block these profitshare garbage clickbait links and such. 

are you getting paid for this? serious question. otherwise I suggest getting rid of all 3rd party default whitelists if you don't have the time to review each list individually so we can all avoid stuff like this getting through.

**Comment by gorhill** [comment]
This is a 3rd-party filter list, please report to the maintainer(s) of the list. http://www.zoso.ro/contact/

uBlock has no relation of any kind with any of the 3rd-party filter lists' maintainers. These lists are included for convenience.

**Comment by gorhill** [comment]
I can't possibly know everything about these 3rd-party filter lists. If you make the case that this list is misrepresenting what it does, I will remove it from the default set of lists without a second thought.

**Comment by romanian2** [comment]
but it IS "misrepresenting what it does", isn't it obvious? I subscribe to it and it doesn't block those profitshare scam links from the biggest online player$$$ in my country. what more proof do you need? also the maintainer basically told me to deal with it, how is that fair? 

and you didn't mention anything about my suggestion, why can't you just turn off the 3rd party's ability to whitelist? what is the point of a default 3rd party BLOCKLIST if it contains A WHITELIST?

**Comment by ghost** [comment]
An option should definitely be added to only include third-party blacklist or whitelist.

**Comment by gorhill** [comment]
> An option should definitely be added to only include third-party blacklist or whitelist

Dynamic filtering's purpose is to let the user have the last word. [Use it](https://github.com/gorhill/uBlock/issues/690#issuecomment-72904276).

**Comment by gorhill** [comment]
> but it IS "misrepresenting what it does", isn't it obvious?

No it's not. Contact the maintainer and ask him why these whitelists. Maybe they are there to prevent site breakage. I want the maintainer on the record as to why these whitelists are there, I don't want to presume malice.

**Comment by gorhill** [comment]
By the way, uBlock discard filters which come with the option `document`, so at least two of these filters are discarded.

**Comment by gorhill** [comment]
> An option should definitely be added to only include third-party blacklist or whitelist

This would render EasyList/EasyPrivacy/etc. unusable, as the exception filters in there are to workaround site breakage. Even uBlock uses exception filters to workaround some site breakage caused by the use of Peter Lowe's, hpHosts. Nobody would use this option because it would render the shipped filter lists unusable.

uBlock gives the user the tools if you don't like what is in a list. Dynamic filtering completely override static filtering when in use. Also, one can create a block filters with the `important` option to render impotent an exception filter.

For example, `||profitshare.emag.ro^$important` will prevent `@@||profitshare.emag.ro/get_ads.php?*` from ever taking effect.

**Comment by romanian2** [comment]
excuse me? site breakage? the only place where those rules are extremely convenient is on his personal website www.zoso.ro where emag.ro constantly pays him to advertise their products. everything is out in the open, his blog posts that are obvious advertisements, check it out:

http://www.zoso.ro/un-mesaj-pentru-emag/
http://www.zoso.ro/stiti-deja-cine-exacta-black-friday/

especially posts like this one: 
http://www.zoso.ro/telefoane-rugged-editia-2014/

every link to emag.ro goes through a profitshare loophole in your ublock, and he gets paid for those clicks. if this isn't "malice" I don't know what is.

the maintainer of the romanian block list has whitelisted his (most likely) number1 main source of income. 

"uBlock gives the user the tool if you don't like what is in a list."

yes, the highly tech savvy user, not the average user who installed your plugin because less ram and is suddenly surprised to see profitshare links left and right.

**Comment by gorhill** [comment]
> http://www.zoso.ro/un-mesaj-pentru-emag/
> http://www.zoso.ro/stiti-deja-cine-exacta-black-friday/
> http://www.zoso.ro/telefoane-rugged-editia-2014/

Thanks, that's what I needed.

**Comment by ghost** [comment]
> Dynamic filtering's purpose is to let the user have the last word. Use it.

Thanks, I am still new to the plugin.

**Comment by gorhill** [comment]
I will comment out all the entries and prevent the list from being downloaded from `http://www.zoso.ro/rolist/`.

What do you think of `@@AC_RunActiveContent.js`? Searching for it I found this: http://support.getadblock.com/discussions/problems/31541-chrome-error-this-page-requires-ac_runactivecontentjs.

**Comment by romanian2** [comment]
I guess whitelisting AC_RunActiveContent.js is fine, from what I've read it's an ancient dependency leftover from embedding flash content, maybe a lot of websites are still using it.

**Comment by zosoro** [comment]
so that is why rolist was not updating. some turd with a big mouth got his facts wrong and the owners of the plugin, instead of contacting me or just removing the list from their plugin, decided to just stop parsing the list. nice. 

let's see what the turd says:
- olx.ro is the biggest romanian ad site
  yes. they have a contact form which uses the filename ad.php. it is easy to whitelist the domain, as they don't run ads on their website, than to modify that rule. 
- homebank.ro belongs to bcr.ro which is a major bank here
  it belongs to ING and it's a banking website. it has some filenames that adblock/ublock blocks and people can't do payments unless the site is whitelisted. they dont run ads on the site. 
- bestauto.ro is a car sales site
  yes. their cdn, the place from where they serve images, is whitelisted, as the site does not work otherwise. they did not run ads when i whitelisted them. 
- promozone.ro - I think the domain speaks for itself, and so on
  it's a website that sells promotional stuff. they don't run ads. 
- emag.ro is the biggest romanian online retailer
  yes. they have "promo zones" where they circle discounted stuff. no ads. 

turd has a problem with me and lies badly cause that's what a good romanian does. good job, turd.
