### ISSUE TITLE
Does uBlock block social networks from tracking you through their embedded widgets?

### ISSUE THREAD

**Issue by lifyd** [uBlock-LLC/uBlock#698]
Something similar to ABP's feature as mentioned by the VentureBeat article: http://venturebeat.com/2014/06/26/adblock-plus-says-it-can-stop-facebook-from-tracking-you-for-targeted-ads/

**Comment by gorhill** [comment]
If you use a filter lists which purpose is to prevent tracking through social widgets, then yes it will protect you, as good as the filter list protect you. However _Fanboy Social_ is not hardcore enough if you want to completely prevent any remote connections to those social network.

As you can see in [these results](https://www.diffchecker.com/pz6rv6lq), using _FanBoy Social_ did not prevent connections to `facebook.com` and `twitter.com`. Ghostery did however (with all trackers enabled).

If you consider yourself an "advanced user", best protection you will get is through [dynamic filtering](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-quick-guide), as this completely override static filtering.

If working in [default-deny mode](https://github.com/gorhill/uBlock/issues/690#issuecomment-72904276), you just killed all tracking from whatever source by default. But you will have to un-break web sites on a case by case basis. Personally I find this easy enough and certainly worth it because it makes the browser so much faster by blocking all the useless stuff by default.

Otherwise in normal mode, it's to find the set of rules which will block connections to these ubiquitous remote servers. Something like:

```
* facebook.com * block
* facebook.net * block
facebook.com facebook.com * noop
facebook.com facebook.net * noop
* twitter.com * block
* twimg.com * block
twitter.com twitter.com * noop
twitter.com twimg.com * noop
[etc]
```

Ideally plenty of doc for dynamic filtering would help more people adopting it as a solution, but so far it looks like this task is all on me. Frankly I wish more people contributing to the doc.

**Comment by lifyd** [comment]
Thanks.

I don't mean to be too critical, but I feel that such a feature (prevention of social network tracking) is absolutely paramount to such a utility like uBlock.

**Comment by gorhill** [comment]
> I don't mean to be too critical

I don't understand why you say this.

As said, it's just a matter of using the proper static filter rules, or proper dynamic filter rules. Did you try _"Anti-ThirdpartySocial‎"_? It's all in the filters or rules.

I'm no longer sure I understand what the issue is about. Can you clarify?
