### ISSUE TITLE
"Connected to x distinct domain(s) out of y" gone in 0.8.7.0

### ISSUE THREAD

**Issue by tenkuu** [uBlock-LLC/uBlock#704]
0.8.6.0
![2015-02-05_20-52-30](https://cloud.githubusercontent.com/assets/2627419/6074722/8ce4e76c-ad79-11e4-936d-d8776e8377cd.png)
0.8.7.0
![2015-02-05_20-53-24](https://cloud.githubusercontent.com/assets/2627419/6074731/d322a566-ad79-11e4-88be-8ba29b1afbe4.png)

Firefox 35

**Comment by gorhill** [comment]
Yes, I added two more rows in 0.8.7.0 and I felt I had to remove that information-only row so as to give priority to the interactive rows.

But I do miss that information. I will be pondering how to bring it back, and my current thinking is to actually provide that information in the right-most pane of the popup, so that even non-advanced users are informed about this -- a good way to make people aware of the often out-of-control bloat.

**Comment by gorhill** [comment]
For translators:

![a](https://cloud.githubusercontent.com/assets/585534/6088464/ae20dd40-ae24-11e4-82b9-0c56fe30d88d.png)<br><sup>This was ibtimes.com if you wonder. It  becomes "98 out of 98" without a blocker...</sup>

Mind the limited horizontal space.

**Comment by gorhill** [comment]
This also ends up sort of addressing #76.
