### ISSUE TITLE
[0.8.7 - dev] Should 3rd party listed above image resource type?

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#707]
As the title says, i believe 3rd party tag in mini matrix UI should be listed above image tag, just for consistency sake..
As <code>all</code> and <code>3rd party</code> denotes of dealing with more than one request types...

![3rd party](https://cloud.githubusercontent.com/assets/779630/6076550/f22ef2f2-ae0a-11e4-9d92-39bb598ccdd2.png)

**Comment by gorhill** [comment]
No, by design.

Everything below `images` is party-based. This is consistent with uMatrix: in uMatrix, all types in the header row are party-less. The party-aware cells are in the left-most column. Here the UI is different, but the same concept of precedence is kept: the party-less cells are at the top, then comes the party-aware cells. The order in which the rows appear match the precedence logic used internally.

**Comment by harshanvn** [comment]
Ok, thanks. It makes sense now :) :+1:
