### ISSUE TITLE
uBlock isn't updating Dynamic Rules on Github in the popup

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#722]
<h1>Scenario:</h1>

1) Enter uBlock's issues page (https://github.com/gorhill/uBlock/issues), observe the connected domains count. (for me I am connected to **2** domains out of 3)

2) Enter 1st issue on the list, open the popup, whitelist the **page** by CTRL+click on the power button.

3) Close the current tab in the browser, and enter again the issues page by URL.

4) Enter to the 1st issue on the list (the one we have previously whitelisted), observe that we are getting now a different count of domains in the list (for me, I am connected to **3** domains out of 3)

5) Head back to the issues page with the mouse back button.

6) One would expect the dynamic rules to be as it was previously (**2** domains out of 3), but it hasn't been updated and still shows that I am connected to **3** domains out of 3 with static filters (previous stats)

~~*Note: The "domains connected" feature was very valuable in spotting this bug, it's unfortunate it will be dropped in v0.8.7.0 .~~

**Comment by gorhill** [comment]
> One would expect the dynamic rules to be as it was previously

Don't expect anything. "Expecting" is actually the bug.

uBlock reports exactly as per network traffic. Navigating on Github often does not cause full page reload, the content of pages are often loaded with javascript requests and refreshed incrementally, it's how the web site is designed. It's more and more common (happens on Youtube too).

Not a bug.

**Comment by Mikey1993** [comment]
But how about someone making a change to the dynamic rules via the popup, when thinking that the dynamic rules that are present to him in the popup are from the current page, when they actually not?

**Comment by gorhill** [comment]
> dynamic rules that are present to him in the popup are from the current page

They are from the current page: you just have to accept that the "current page" was built incrementally from an older page.

**Comment by Mikey1993** [comment]
So the popup will host the previous and the current page requests?
If this is the case, this is OK, beucase a user will have still get all the request in the popup, but the consistency that is built visiting the 99% of other sites is broken in this scenario - which is bad IMO. 

The average user doesn't have a clue about that, and this is why the current state of things is not ideal.

I would call this a consistency break, rather than a bug.

**Comment by gorhill** [comment]
> So the popup will host the previous and the current page requests?

Yes, for pages which are built incrementally. It happens here. It also happens when using Google Maps for example.

> the current state of things is not ideal

The current state **is what needs to be done**. Doing otherwise introduce a whole new pack of bugs. I actually fixed these a long time ago by respecting and reporting exactly what is happening internally. A long time ago, merely panning in Google Maps was causing all the stats in the popup to be reset. That made no sense, because in reality no page load is occurring, only an update to the current page. Just like here.

In any case, you are making an issue of a complete non-issue: dynamic filtering granularity is hostname-based, so it's a complete non-issue to worry about whether or not a dynamic rule should be set or not for a _given page_, as dynamic rules apply site-wide at the narrowest.

What is happening is what **must** happen, I just can't -- and won't -- debate this forever.

**Comment by Mikey1993** [comment]
> What is happening is what must happen, I just can't -- and won't -- debate this forever.

Sure thing, lets close this.

**Comment by gorhill** [comment]
Try other blockers if that helps, they behave just the same way.

**Comment by Mikey1993** [comment]
> Try other blockers if that helps, they behave just the same way.

That's ok, I believe you.

I understand that this is probabaly the best solution for this scenario to keep bugs from creeping by other scenarios (like Google Maps as you have mentioned).
