### ISSUE TITLE
divshare.com blocked even when whitelisted?

### ISSUE THREAD

**Issue by famewolf** [uBlock-LLC/uBlock#725]
As seen in screenshot: http://i.imgur.com/CiFGLKI.png    the two images below did not display.  
Images from divshare.com appear to be blacklisted.
Disabling uBlock causes them to show up fine.  Placing divshare.com into the whitelist did not correct the issue.  Only when uBlock was disabled would the images appear.  I tried unchecking each list, applying the updates and refreshing the page but was unable to get them to appear.  Actual post can be viewed at http://forums.bodhilinux.com/index.php?/topic/11715-share-your-desktop/page__st__20

Two images in question are:
http://www.divshare.com/img/display/26783291-f2c.jpg
http://www.divshare.com/img/display/26784651-3e9.jpg

Version used:  Pale Moon/Firefox

**Comment by gorhill** [comment]
I can see them all fine. You need to tell me all your uBlock settings which differ from default settings.

**Comment by gorhill** [comment]
Wait, I see `www.divshare.com` is in one of the [malware domain list](http://www.malwaredomainlist.com/) (I had disabled these lists).

If you want to counter this, you must create an exception filter, not a whitelist directive: the purpose of whitelisting is to disable uBlock for a specific site/page/etc. What you wanted is to counter a filter. You do this with an exception filter:

```
@@||www.divshare.com^
```

But since it's on a malware list, not really be recommended -- though sometimes there are false positive in these lists.

**Comment by famewolf** [comment]
Thanks for the quick followup!  I must have not flushed the cache properly when I unchecked the malware lists and refreshed.  Your hard work is greatly appreciated.
