### ISSUE TITLE
[Issues + Suggestion] Wrong count of active filters

### ISSUE THREAD

**Issue by tailHey** [uBlock-LLC/uBlock#73]
First issue: http://i.imgur.com/ogaBkeQ.png

39 581 filters used, but at least 64 975 from Fanboy's Ultimate List...

Suggestion: I think the feature to turn on the parsing of cosmetic filters should be at the bottom, not at the top.

Another "issue": The locales files don't include string for header tags so that they can be translated into foreign languages.

**Comment by gorhill** [comment]
It's because the [string in messages.json](https://github.com/gorhill/uBlock/blob/master/_locales/fr/messages.json#L76) needs to be translated to use the new English one, in which case the missing filters will be reported as cosmetic filters.

The header tags are there now, I forgot to bring in my changes from Crowdin before removing it.

**Comment by gorhill** [comment]
Fixed with 8bda84a6b67e3bb84a79d12bc1fdd9a5f0cbe401.
