### ISSUE TITLE
Extension download size is large

### ISSUE THREAD

**Issue by mubaidr** [uBlock-LLC/uBlock#74]
Hi!

Extension download size seems to be large, why not fetch only subscribed lists when enabled?

**Comment by gorhill** [comment]
It's only at install or update time. I don't see this as an issue. The extension update often lately because it's being developed, but at some point it's going to stabilize, and having the basic lists included will be even less of an issue.

Having basic lists included for me is important to ensure the extension will work reliably in case one or more lists can't be downloaded.

See related discussion: https://github.com/gorhill/httpswitchboard/issues/363.

There are other advantages which do not appear above. For instance, users can use Github's built-in differ to find out what changed in a list if they are curious.

I am pretty set on this one, I don't intend to change my mind.

**Comment by gorhill** [comment]
By the way, if it is a bandwidth issue, you could install the extension manually from the [releases page](https://github.com/gorhill/uBlock/releases), and this way you could update only when you want.
