### ISSUE TITLE
[Safari] Blob: type is included in 3rd party list, even though the path is first party

### ISSUE THREAD

**Issue by mike-to-spec** [uBlock-LLC/uBlock#741]
On this youtube video: https://www.youtube.com/watch?v=ooDWJzz4uFY

If you have 3p blocked, the video will not play, even though the file is still first party: The issue is this:

` −   * * 3p block    other   blob:https://www.youtube.com/b8b68f60-1fc8-4d2d-9eb3-300d7c1732af`

Once I noop;ed the 3p block on youtube, it did finally play on youtube.com as well as the embedded youtube videos on sites like Reddit. 

I don't know if this is intentional but it took quite a bit of time to figure this out on youtube as I didn't think it would be classified as third party.

**Comment by mike-to-spec** [comment]
Also, how do I manually approve this in _My Rules_?

**Comment by Betsy25** [comment]
That might be normal since the video itself is not on the domain youtube.com but rather is at : r7---sn-uxaxoxu-cg0s.googlevideo.com here.

[Full URL to actual video accessed from my system](https://r7---sn-uxaxoxu-cg0s.googlevideo.com/videoplayback?ip=2a02%3A1811%3Ae408%3A9500%3A993b%3Aef91%3A79cc%3Aba26&ratebypass=yes&mm=31&source=youtube&pl=33&mv=m&mt=1423487693&ms=au&id=o-AID13oIfgDZOrhOo40jFDUSO0w16pisIcEHUZvxv0pLQ&initcwndbps=2327500&key=yt5&sparams=dur%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Cmime%2Cmm%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&expire=1423509408&ipbits=0&fexp=907263%2C924637%2C927622%2C929305%2C930676%2C930825%2C933232%2C936100%2C943917%2C947225%2C948124%2C952302%2C952605%2C952612%2C952901%2C955301%2C957201%2C959701&signature=D64A432F491951A062737776BAED8510FCA6166A.DA2AD3EF82CB9E0AF81FF8099BB49DAB5B5DED12&sver=3&mime=video%2Fmp4&dur=48.947&requiressl=yes&upn=WvgjMeJndRw&itag=18&x-yt-ts=1423165413&x-yt-cl=85642102&ptk=youtube_none&cpn=XjLKRyAnuSufc1O7)

[uBlock useful rulesets](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-default-deny:-useful-rulesets)

**Comment by gorhill** [comment]
Youtube works fine using the [documented ruleset](https://github.com/gorhill/uBlock/wiki/Dynamic-filtering:-default-deny:-useful-rulesets):

```
# youtube.com
www.youtube.com content.googleapis.com * noop
www.youtube.com ggpht.com * noop
www.youtube.com google.com * noop
www.youtube.com googleusercontent.com * noop
www.youtube.com googlevideo.com * noop
www.youtube.com gstatic.com * noop
www.youtube.com plus.googleapis.com * noop
www.youtube.com youtube-nocookie.com * noop
www.youtube.com ytimg.com * noop
```

**Comment by gorhill** [comment]
By the way, I can't see that `blob:` thing with Firefox/Chromium. Is this a Safari-only thing?

Need @chrisaljoudi to check this.

If ever this really happens, then anything which is not a formal `http`/`https` request should not be subjected to dynamic fitlering.

**Comment by gorhill** [comment]
Ok, thinking of it, on Chromium, [only requests of type `http`/`https` are intercepted](https://github.com/gorhill/uBlock/blob/master/src/js/traffic.js#L354), and I beleive it's also the case for Firefox. This means there is no such narrowing on Safari. This needs to be addressed in the platform-sepcific code of Safari.
