### ISSUE TITLE
Slideshows on Wired.com don't work

### ISSUE THREAD

**Issue by fysics** [uBlock-LLC/uBlock#77]
See here: http://www.wired.com/2014/07/6-design-concepts-from-ideo-for-making-aging-easier/
The picture should advance when you click the arrow on the right side.

This is an issue I've seen with multiple adblockers. I believe it happens because the javascript used in the slideshow depends on functions available only inside a tracking script (google analytics, I believe). One possible fix would be to duplicate those functions sans tracking, any time that script is blocked.

**Comment by gorhill** [comment]
It does work for me, even with many more lists selected than the out-of-the-box ones. What browser? Any other add-ons which could interfere?

**Comment by fysics** [comment]
Well now it doesn't work even with all extensions disabled.

I'm on Chrome 37.0.2062.20 dev-m (64-bit) just fyi.

I'm closing this issue.

**Comment by elpres** [comment]
This is still an issue. I've been trying to triage the source of breakage for about half an hour and have to give up due to lack of time, but this site: http://www.wired.com/2015/11/the-most-nonsense-concepts-from-the-tokyo-motor-show/ works in Chromium (latest stable, Version 46.0.2490.80 (64-bit)) in Incognito mode with all plugins disabled, and with uBlock enabled but filtering off (blue off switch clicked so it's grey). As soon as I enable blocking, even removing all site rules (not sure about the proper term, I mean the global/site-specific blocking matrix in the popup) breaks the "advance right" error after the 5th slide. That would leave the 3rd party filter lists as the only source of blocking, and I think I've tried disabling each of them, with no effect. I'll do more testing tomorrow.

I did manage to unbreak the slideshow once, and had to noop googletagservices.com, but have since then decided to change my blocking strategy, and now this seems to be not enough.
