### ISSUE TITLE
Safari (Mavericks) Crash

### ISSUE THREAD

**Issue by carmelovazzana** [uBlock-LLC/uBlock#776]
Hi, while installing the extension Safari started to crash, now I can't even open the browser because down immediately while re-charging last pages opened. Is it possible to eliminate manually the extension? Or try to solve the problem in any other way?
Thanks in advance, Carmelo

P.S. I think that uBlock isn't compatible with Safari under Maverick.

**Comment by gorhill** [comment]
> I think that uBlock isn't compatible with Safari under Maverick

[Front page](https://github.com/gorhill/uBlock#safari):

> There are currently no plans to support older versions of Safari. It's not recommended that you install µBlock on them (do it at your own risk).

Safari pre-Yosemite has bugs which are behind the crash: dup of #593.

**Comment by RSully** [comment]
How can we uninstall it so the browser does not crash on launch?

**Comment by chrisaljoudi** [comment]
@RSully you can remove the safariextz file from `~/Library/Safari/Extensions/`.

**Comment by gitguys** [comment]
Why is this destructive extension still up on Apple's extensions page?  This needs to be pulled off of there ASAP.  It crash Safari and even screwed up other app I use that work with Safari's bookmarks when I tried to install this in Mavericks with Safari 7.1.3.

I've NEVER had any other extension or plugin on any other browser ever do something this severe.  If you guys want continued support from the Mac community, I would do everything possible to WARN people about this issue and make sure Apple pulls this off their extensions page.

Otherwise, you guys are in for a PR nightmare or perhaps worse.
