### ISSUE TITLE
[EasyPrivacy] Very.co.uk searching very slowly with uBlock activated

### ISSUE THREAD

**Issue by Nocturnalizer** [uBlock-LLC/uBlock#787]
Hi,

If you head over to very.co.uk (a shopping site) and type anything into the search box (I use 'Nintendo' as an example) it takes between 15-30 seconds for the search results to display when uBlock is activated. If I whitelist the site, reload the page and then search results will pop up instantly. Is there anything that can be done for resolve the issue short of whitelisting the site?

Thanks for any help!

EDIT: Just to add, the lists I'm using are the ones selected at default when installing uBlock and I've ticked 'Fanboy's Annoyances'. I've tried unticking the latter but it doesn't help.

**Comment by ghost** [comment]
Not an issue with uBlock, http://d3c3cq33003psk.cloudfront.net/opentag-56535-278157.js is being blocked by the /opentag- filter from EasyPrivacy. You can use this rule to work around it (@@||d3c3cq33003psk.cloudfront.net^$script,domain=www.very.co.uk) or disable EasyPrivacy.
Opentag is being blocked because it's a tracker (https://www.qubitproducts.com/tag-management), so reporting it to EasyPrivacy would defeat the purpose, as making an exception for this would open yourself up to being tracked.

**Comment by Nocturnalizer** [comment]
Ah, thanks for the info! I've been playing around with dynamic filtering and I've got the site loading fine even with most third party trackers blocked so maybe that's the best way around it for me personally.

**Comment by gorhill** [comment]
Cause: `/opentag-` in EasyPrivacy.

Report to maintainers of EasyPrivacy: https://forums.lanik.us/viewforum.php?f=64
