### ISSUE TITLE
Blocked requests popup only shows once in firefox

### ISSUE THREAD

**Issue by PalmerAL** [uBlock-LLC/uBlock#807]
For example:

Open https://github.com/gorhill/uBlock/issues/807

Click the eye icon to view blocked requests.

Close the window.

Click the eye icon a second time.

None of the requests are shown, just a blank window.
In console, gives this error:
<code>Security Error: Content at moz-nullprincipal:{1c57bf37-6c1f-ba43-a33d-aed05c38e723} may not load or link to chrome://ublock/content/devtools.html?tabId=panel-301-100.</code>

**Comment by gorhill** [comment]
By design.

Permanently storing logged requests in case they might be needed would cause uBlock's memory footprint to grow unduly.

The network logger logs network requests only when it is opened, and discard all that is logged when the tab is closed. This ensure that the logger uses memory only for those users which have an interest to watch network traffic.
