### ISSUE TITLE
[Firefox] Mouse cursor flickers while in selecting element mode

### ISSUE THREAD

**Issue by Mikey1993** [uBlock-LLC/uBlock#811]
Here is a short video showing the issue:

https://www.youtube.com/watch?v=SfuXwnjxTZM

This seems to show on Firefox, but not on Chrome (haven't checked Safari).

**Comment by gorhill** [comment]
"This video is private".

**Comment by Mikey1993** [comment]
Sorry, my bad.
It should show fine now.

**Comment by gorhill** [comment]
Issue is caused by quickly setting `pickerRoot.style.pointerEvents` to `'none'` then back to `''`. Somehow on Firefox, this is a large enough window for the browser to re-render the mouse cursor according to what is underneath.

Because of this, the issue extends to mere mouse cursor shape issue, this means that whatever is mouse hover-interactive will becoming interactive while the element picker is active, but in a broken way. For example, front page of http://www.cnet.com/.

Not sure what can be done.

**Comment by Deathamns** [comment]
Force `cursor: crosshair;` on `<html>` on the web-page while picking an element.

**Comment by gorhill** [comment]
Or `pointer-events` to `'none'` to avoid glitchy interaction?
