### ISSUE TITLE
popups are not blocked on playhd site..

### ISSUE THREAD

**Issue by harshanvn** [uBlock-LLC/uBlock#85]
hi Gorhill,

Looks like pop-ups are not blocked on playhd site any more.
Can you please take a look at it. Let me know if you need any info.

Thanks, Harsha

**Comment by gorhill** [comment]
Looks like it's a cat and mouse game. They (`playhd.eu`) changed the URL against which popups were tested in _EasyList_. I suppose the _EasyList_ crowd will have to fix that. I used a less specific filter to block the popups though, so that changing the URL won't have an effect:

`||playhd.eu^$popup`

But I wonder, if such a less specific filter wasn't used by the _EasyList_ crew, maybe it's because there might be a bad side-effect? I don't know that site enough to know what to test on it...

For now I added it in uBlock's filter, so you can force update from the _About_ tab. Will see how the _EasyList_ crew fix this one.

**Comment by harshanvn** [comment]
thanks for the quick fix gorhil :) 
I am not sure what is the reason behind adding more specific filters by easylist crew. Anyways adding popup deny to playhd site seems to be correct way.
This site is similar to other video streaming sites. It seems to have very good streaming rate from here in india.

I have one question here though. When the popup is blocked, i am not able to see its corresponding blocked request under statistics tab. Can it be logged? (if its an issue, i can create a new bug, i just don't want to create a new entry unnecessarily)

**Comment by gorhill** [comment]
> Can it be logged?

The logged requests are per tab. But then the tab is destroyed, so this means the logged requests are gone too.

**Comment by harshanvn** [comment]
hmm..ok.
I was thinking if there could be a way to improve logging in this respect (i.e., for pop-ups blocked scenario), like log the pop-up blocked under parent tab (i.e., pop-up originated tab)..just a thought..
If its not feasible to do. then its fine. not a big deal :)

Thanks!!

**Comment by gorhill** [comment]
Yes, I think it can be done. I could record a request for `document`/URL/filter in the source window stats.
