### ISSUE TITLE
Pepsi Contact Us broken

### ISSUE THREAD

**Issue by albert--** [uBlock-LLC/uBlock#855]
Broken sites:
https://cu.pepsico.com/gatorade
https://cu.pepsico.com/pepsi
https://cu.pepsico.com/sobe

http://i.imgur.com/ZTNXRCi.png
http://i.imgur.com/Vc7Amwj.png

**Comment by gorhill** [comment]
Looks fine here with default settings:

![d](https://cloud.githubusercontent.com/assets/585534/6314192/01252210-b9a3-11e4-8c03-876d9637326d.png)

What are **all** the settings which differ from default ones? Also browser/version.

**Comment by albert--** [comment]
Firefox 35.0.1, µBlock 0.8.8.2
http://i.imgur.com/gZtR0rO.png
and Easylist Germany

**Comment by gorhill** [comment]
The only 3rd-party filter list for which I provide support is Peter Lowe's. Any other 3rd-party filter list(s) which break a web site, you will have to report to their respective maintainer(s) so that they fix their list if they agree it needs fixing.

Breakage is not unexpected when you uses so many filter lists, especially the hosts file-based ones. Dynamic filtering is there to help users workaround that sort of breakage.

**Comment by gorhill** [comment]
Using the dynamic filtering pane, one can see that a lot of network requests were blocked for `secure.footprint.net`, so locally whitelisting `secure.footprint.net` fixes the issue.

![d](https://cloud.githubusercontent.com/assets/585534/6314612/88dc5312-b9b3-11e4-84ef-8ca8de139100.png)

If you're going to use all hosts file-based lists, you should familiarize yourself with dynamic filtering, or I would suggest you do not select these hosts file-based lists: breakage is expected from their use.
