### ISSUE TITLE
uBlock doesn't block sfw files that get loaded dynamically

### ISSUE THREAD

**Issue by ABPShillNoShillingHere** [uBlock-LLC/uBlock#910]
Hello,

the filter rule
`|https://fbstatic-a.akamaihd.net/*.swf`
doesn't work on Facebook.
The videos play anyway.

Normally it blocks videos from the Facebook News Feed (in Adblock Edge this rule works).
It's the only reason keeping me from using uBlock.

**Comment by ABPShillNoShillingHere** [comment]
what the flying fuck

**Comment by gorhill** [comment]
I need a test case to reproduce on my side. uBlock blocks whatever network requests which match the filters, "loaded dynamically" should make no difference.

**Comment by ABPShillNoShillingHere** [comment]
Okay, then use that rule in uBlocks custom rules and visit your Facebook feed. The videos will start playing.

I have no other website where I can show you this behaviour though.

**Comment by gorhill** [comment]
What version of uBlock are you using? This bug was fixed yesterday: #903. It's fixed in 0.9.8.1.

**Comment by ABPShillNoShillingHere** [comment]
I downloaded the latest version 0.8.9.1 from here (GitHub).

**Comment by gorhill** [comment]
I don't have a Facebook account, that's why I need a web page. Anyways, I found one: https://www.facebook.com/video.php?v=781508688605093&set=vb.514608705295094&type=2&theater.

I tried your rule, `|https://fbstatic-a.akamaihd.net/*.swf`, and the video got blocked:

![d](https://cloud.githubusercontent.com/assets/585534/6430964/19a58468-bfef-11e4-82ff-76ad0e03282c.png)

Using 0.8.9.1.

**Comment by gorhill** [comment]
Actually, I realize if uBlock created a selfie while you have the bug, the selfie won't  be invalidated with the new version, meaning the buggy filter is still in the selfie. My bad. Workaround is to toggle on/off the _"Parse and enforce cosmetic filters"_ option, click _"Apply changes"_, then toggle back to its previous state, or just change the selection of lists somehow, and revert, in order to force an invalidation of the selfie.

**Comment by ABPShillNoShillingHere** [comment]
Nice, you respond very fast. :+1: 

I just tried it again, not updated uBlock (as I already had latest) nor anything else and it really works now.

Thanks, now also I can see if uBlock really is better than the others or not. :+1:

**Comment by gorhill** [comment]
> Nice, you respond very fast

Well, if I happen to be in front of the computer, I will usually.
