### ISSUE TITLE
[Firefox] Update

### ISSUE THREAD

**Issue by mikhaelkh** [uBlock-LLC/uBlock#925]
Add autoupdate option to Firefox version. One way is to put new versions on https://addons.mozilla.org. Other way is to avoid mozilla market, like [HTTPS Everywhere](https://www.eff.org/https-everywhere).

**Comment by gorhill** [comment]
Dup of #922.

**Comment by mikhaelkh** [comment]
#922 only suggests to get updates through mozilla market. I suggest to avoid that and use similar update mechanizm that is used in HTTPS Everywhere, which is unavalible in mozilla market, but recieves updates automatically.

**Comment by gorhill** [comment]
The project has no home server, and asking Github to act as one could be seen as abuse from Github (bandwidth). So it will have to be AMO.

**Comment by hackel** [comment]
I'm curious, why do you think this kind of auto-update feature would be an abuse of service, while projects like composer, bower, npm, etc. all use GitHub as a repository for their packages and updates and millions of users are downloading software from it all the time?  Is it the automatic update checking that is the problem?  I don't think anyone wants to abuse GitHub.  Hopefully there can be some better solution, though!

**Comment by chrisaljoudi** [comment]
@hackel 

> bower, npm, etc. all use GitHub as a repository for their packages and updates 

Hmm? Why do you believe that's true? 

Pretty sure the `npm` registry (which is how you install/update `bower` or update `npm`) uses a CDN — they've used MaxCDN in the past, and I think they're currently with [Fastly](www.fastly.com).

**Comment by mikhaelkh** [comment]
[YouTube Center Developer Version](https://github.com/YePpHa/YouTubeCenter/wiki/Developer-Version) updates through GitHub (Firefox and Chrome versions)

**Comment by chrisaljoudi** [comment]
Regardless of which projects use this and which don't:

I've looked into this more, and it appears that (**currently**) GitHub is [happy to serve the binary `Releases` artifacts](https://help.github.com/articles/distributing-large-binaries/). Though surprising, it's quite nice of them. 

There were points where they disabled that feature, but they have brought it back since. [A subtle thing to note is that GitHub still indeed does **not** want people hot linking to raw source files from the tree](http://blog.rodneyrehm.de/archives/35-Including-Data-From-Github.html).

As far as I can tell, they're using Amazon AWS S3 to serve the actual binaries.

CC @gorhill ^ this might be good to know.

That said, there's one more trick that would be needed for doing direct Firefox auto-updates properly. [Mozilla states that auto-updates need a manifest file](https://developer.mozilla.org/en-US/Add-ons/Install_Manifests#updateURL) which must be served with an appropriate mime-type. I don't know where that'd be hosted for uBlock.

**Comment by chrisaljoudi** [comment]
To add: right now, for Safari, I'm handling the hosting for the update manifest as well as the uBlock Safari builds.

I'd be happy to host the Firefox update manifest if @gorhill and @Deathamns decide direct updates from GitHub Releases are the way to go.

**Comment by hackel** [comment]
@chrisaljoudi I'm not that familiar with npm, so I'm sure you're right, but I believe composer directly queries the list of tags from github for each project to determine the available versions.  Web developers don't go around automatically updating their dependencies, though (at least I hope!), so it's not the best comparison.  Thanks for offering to host the manifest, that would be great.

Perhaps this is a feature that could be added to https://github.com/diegocr/GitHubExtIns so that it works for all extensions.
