### ISSUE TITLE
popup not blocked for film-stream.org

### ISSUE THREAD

**Issue by ale82to** [uBlock-LLC/uBlock#927]
Popup not blocked on http://film-stream.org/serietv/
Every time I navigate to that site I get a popup window with the URL: http://www.aznotizie.com/

**Comment by gorhill** [comment]
It's just that there is no filter for `aznotizie.com`. One needs to be added by EasyList maintainers, so please report the issue to them: https://forums.lanik.us/viewforum.php?f=62 (so that everbody benefit from the fix).

They will probably add this filter: `||aznotizie.com^$popup`, use it as custom filter meanwhile.
