### ISSUE TITLE
Returning Images

### ISSUE THREAD

**Issue by petersmith67** [uBlock-LLC/uBlock#941]
When I use element picker(eye dropper) the image is blocked fine.When I reload the page the image/element returns.I would mention the page but it may be against the rules.Thanks in advance for any suggestions.Fresh ublock install Firefox.Ublock Settings/Filters are stock and updated.

**Comment by harshanvn** [comment]
may be image id is randomly generated. Try selecting the parent element where image is resided (if it is!). Am not sure, just a random guess. Since, url to the offending element is not provided..

**Comment by petersmith67** [comment]
The site is 4 chan /g/.The image is the top one.Some times it is animated or static.ABP blocks the image permenently when adding the rule.I like Ublock better but returned to ABP because of this issue.Thanks.I currently am using Ublock with ABP removed from addons.Also would it be possible to remove the placeholder(image box) after removing the image.ABP doesnt remove the box either.

**Comment by sn260591** [comment]
@petersmith67, if I understand correctly, you selected a filter by default. Use the second option in cosmetic filters, it will hide the same placeholder.

![02](https://cloud.githubusercontent.com/assets/10724977/6504744/7e3c3dfe-c34b-11e4-8fb0-2316cf159efe.png)

**Comment by petersmith67** [comment]
Excellent! Thanks sn260591.Definetly sticking with Ublock.Iam not sure if ABP can do the same,but I like Ublock better.Seems snappier.

**Comment by gorhill** [comment]
It's just a matter of creating the proper filters:

```
||s.4cdn.org/image/title/
boards.4chan.org###bannerCnt.title.desktop
```

Now the only annoying part is that the element picker has to be launched twice, once for the network filter, then again for the cosmetic filter. This is issue #781.

**Edit:** Notice I removed the variable part of the URL in the network filter, it's because the image URL changes every time, so you have to create the filter with only the part which doesn't change.
