### ISSUE TITLE
Firefox version missing! :)

### ISSUE THREAD

**Issue by Waboru** [uBlock-LLC/uBlock#96]
Hello,

I really like uBlock, it's the best Adblocker I've seen so far.

Sadly, Firefox has just worse Adblockers in comparison to Chrome now. They are using too much memory, can be laggy sometimes and you can't trust some of them (Adblock Plus for example).

Could you please make a version for Firefox? This is my favorite browser and I'm sure many people will love it.
Firefox deserves a better Adblocker an no one seems to do this better than you guys.

Please add Firefox support in future, I'd love you for this. :+1:

**Comment by tailHey** [comment]
Hello everyone!

I agree with @Waboru. Besides, HTTPSB/µMatrix would also be benefic for Gecko-based browsers ^^

**Comment by gorhill** [comment]
I need a twin, or two.

**Comment by tailHey** [comment]
@gorhill : Haven't you already thought about turning HTTPSB into a proxy thing? Why not trying to do so with µMatrix to begin?
If only it was easy and lightning fast to port an addon from Chromium-based browsers to Gecko-based ones :/

**Comment by tailHey** [comment]
After all, as you know as much as we do, there are many FF users around the Web

**Comment by gorhill** [comment]
Somebody will have to pitch-in. There is so much one dev can do in his hobby time. If somebody would start to proactively port to Firefox, I would totally work with him/her to explain and also to refactor whatever needs to be to create a common core.

**Comment by Waboru** [comment]
Could you guys share this idea to some devs that work with firefox addons? Probably we'll find someone who is interested.

**Comment by gorhill** [comment]
> Could you guys share this idea to some devs that work with firefox addons

I am the kind of person who prefers to not ask. I believe whoever comes forward on his own will be the most motivated, and that kind of volunteer will even likely come forward _after_ a good chunk of the work is done.

**Comment by kurtextrem** [comment]
You could try the AdGuard Beta for Firefox: http://forum.adguard.com/showthread.php?2225-Adguard-for-Chrome-Firefox-Opera-beta-1-0-3
(It's not as good as uBlock/uMatrix, but it's an improvement over ABP)

**Comment by gorhill** [comment]
Just be aware that Adguard will send the domain of the URLs you browse to its own server, i.e. `https://sb.adtidy.org/safebrowsing-lookup-domain.html?domain={page hostname}`. I noticed this when running the benchmark. It seems to happen the first time a specific domain is browsed, not sure if and when it repeats (maybe there is a countdown to avoid pinging too much `adtidy.org`).

Given the URL, best guess is that it is for its _"Phishing and malware protection"_, but I can't easily find information about this. In my opinion this should be **prominently disclosed** right aside whatever settings triggers that on, given the privacy implications. In case people wonder, I did not have any of the settings to report to Adguard turned on.

Edit: Ok, I just tried without _"Phishing and malware protection"_ turned on, and the requests to Adguard server stopped, so that confirms turning on _"Phishing and malware protection"_ causes this.

**Comment by Waboru** [comment]
I tried Adguard and dislike it even more than Adblock Plus for Firefox. I can't add my own filter lists and everything felt sluggish and even more RAM consuming than ABP. I don't trust this company, too. Seems also suspicious to me.

I really hope uBlock will someday be available for Firefox.

**Comment by Betsy25** [comment]
Count me in on that. Having this become true would cause some serious headlines in webbrowser-land.

**Comment by gorhill** [comment]
Dup of #27.

**Comment by testitor** [comment]
ublock for firefox please

**Comment by logos88** [comment]
A firefox version would be awsome!

**Comment by diegocastro** [comment]
+1 for this.

**Comment by gorhill** [comment]
@Deathamns is there a way for me to answer feedback on [AMO](https://addons.mozilla.org/en-US/firefox/addon/ublock/)?

**Comment by Deathamns** [comment]
@gorhill Do you have an account?

**Comment by gorhill** [comment]
Yes: https://addons.mozilla.org/en-US/firefox/user/gorhill/

**Comment by Deathamns** [comment]
Actually e-mail address is what was needed. So, maybe you got an e-mail with ownership granted message or something?

**Comment by gorhill** [comment]
Got it, thanks (I had not looked into my inbox yet today).
