### ISSUE TITLE
The Element Hider doesn't work on some websites

### ISSUE THREAD

**Issue by JBey4you** [uBlock-LLC/uBlock#99]
I just find out that the Element Hider feature -- which is great by the way -- doesn't work on some websites. For an example, 9to5Mac.com: the eye to activate the feature doesn't appear at all.

![capture decran 2014-07-25 a 20 12 02](https://cloud.githubusercontent.com/assets/7979756/3706237/39e9ff34-1427-11e4-84a6-f41811a58a6c.jpg)

On MacWorld.com, it's an another thing. I can activate the Element Hider feature, although it does nothing when I choose a element (in that case the autoplay video on the right).

![capture decran 2014-07-25 a 20 13 21](https://cloud.githubusercontent.com/assets/7979756/3706256/6bc614f2-1427-11e4-9ac1-6c02f8c2bf27.jpg)
<em>I'm clicking, but it does nothing</em>

Am I alone?

PS: Since I'm talking about MacWorld, the header doesn't work with uBlock. If I click on the logo or a section (News, Reviews, How-to, etc), it does absolutely nothing. It works with uBlock disabled.

**Comment by gorhill** [comment]
Ok I fixed for `9to5Mac.com`. I forgot hostname labels can start with a digit.

The other problem is.... The click doesn't work because they use an event listener on the whole document, and they cancels the click event if they can't track your action on the site (something like that). Not the first site I see doing this. The whole site is bent on tracking what you do, and if you happen to actually block the embedded tracker, links won't work etc so that this discourage people from blocking their abuse (right-click is workaround in such case).

Anyways, I suppose I have to put the event listener at the root rather than the overlay.

**Comment by gorhill** [comment]
Ok second part will take more time to fix, if there is any fix: they destroy the click event, so the element picker never receives it, even if I register the event listener on the root of the document. ABP has same problem.

**Comment by gorhill** [comment]
Looks like it works on MacWorld.com now.
